### ISSUE TITLE
expressionEvaluationOptions property missing from 2019-10-01/Microsoft.Resources.json

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#1009]
Docs for expressionEvaluationOptions:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#expression-evaluation-scope-in-nested-templates

Removed with this PR:

https://github.com/Azure/azure-resource-manager-schemas/commit/3eb617e26b6abed4923cbf346831731d7467a561#diff-2268fae0f09d027108277946cefd0f06

**Comment by anthony-c-martin** [comment]
Thanks @neilpeterson - this is being generated from swagger, so I've raised it against the swagger repo.

**Comment by neilpeterson** [comment]
Thanks Anthony - I should have started with Swagger, appreciate you picking it up.
