### ISSUE TITLE
Microsoft.Network/dnsZones

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/azure-resource-manager-schemas#101]
Is this missing? I see reference for it here
https://msdn.microsoft.com/en-us/library/azure/mt163590.aspx

I see examples of using it here
https://github.com/Azure/azure-quickstart-templates/tree/master/101-azure-dns-new-zone

But when I attempt to view if from inside the schema listed in that example or the current schema available I don't see it.

"id": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",

```
              { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/publicIPAddresses" },
              { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/virtualNetworks" },
              { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/loadBalancers" },
              { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/networkSecurityGroups" },
              { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/networkInterfaces" },
              { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/routeTables" },
              { "$ref": "http://schema.management.azure.com/schemas/2015-11-01/Microsoft.Network.json#/resourceDefinitions/trafficManagerProfiles" },
```

I think this is why i'm getting an error when I attempt to deploy dns recordsets to azure in my templates.

my template, I use nested templates and dynamically build the template I push to azure, when I get to this step the deployment fails with the following

New-AzureRmResourceGroupDeployment : DeploymentNotFound: Deployment 'DnsTemplate' could not be found.
At F:\Projects\Lowes\ops\Azure\Templates\ServiceDeployment\Scripts\Deploy-AzureResourceGroup.ps1:144 char:1
- New-AzureRmResourceGroupDeployment -Name $Name -ResourceGroupName $Re ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], CloudException
  - FullyQualifiedErrorId : Hyak.Common.CloudException,Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

{
  "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ZoneName": {
      "type": "string",
      "metadata": {
        "description": "The name of the DNS zone to be created."
      }
    },
    "RecordName": {
      "type": "string",
      "metadata": {
        "description": "The name of the DNS record to be created.  The name is relative to the zone, not the FQDN."
      }
    },
    "IpAddress": {
      "type": "string"
    }
  },
  "resources": [
    {
      "type": "Microsoft.Network/dnsZones",
      "name": "[concat('/',parameters('ZoneName'), concat('/A/', parameters('RecordName')))]",
      "apiVersion": "2015-05-04-preview",
      "location": "global",
      "properties": {
        "TTL": 3600,
        "ARecords": [
          {
            "ipv4Address": "[parameters('IpAddress')]"
          },
        ]
      },
      "dependsOn": [
      ]
    }
  ]
}

**Comment by wenwu449** [comment]
@vladca, can you add the dnsZones schema?
@jeffpatton1971 , schema is not required for the deployment to succeed, so this is not the failure reason. Also, as this is a collaboration repo for schema, deployment questions like this may not get attention in time. I would suggest you post template usage questions in MSDN forum to get more prompt responses.

**Comment by jeffpatton1971** [comment]
@wenwu449 Thanks for the reply, I posted here because I think that is the issue. I've had limited success in the msdn forums, but i'll give it a go. My understanding was in order for a resource to be consumed you had to be able to find it? which is why the schema lists where each of the resources is, and perhaps differentiates based on the api version? Am I wrong?

**Comment by jeffpatton1971** [comment]
@wenwu449 Just checking the schema against what I know works. These are all the things I use on a regular basis and they are all listed in the schema, how can dnszones not be listed in the schema and still work?

                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/publicIPAddresses" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/virtualNetworks" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/loadBalancers" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/networkSecurityGroups" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/networkInterfaces" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/routeTables" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-11-01/Microsoft.Network.json#/resourceDefinitions/trafficManagerProfiles" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Storage.json#/resourceDefinitions/storageAccounts" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Compute.json#/resourceDefinitions/availabilitySets" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Compute.json#/resourceDefinitions/extensions" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Compute.json#/resourceDefinitions/virtualMachines" },
                  { "$ref": "http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Compute.json#/resourceDefinitions/virtualMachineScaleSets" },

**Comment by wenwu449** [comment]
schema is now not used by service provisioning the Azure resource, so it is not required for the deployment. As the user discovery, MSDN documents would be a complete set for the APIs and resource definitions.
Still we are trying our best to have schema for every resource supported for deployment. Thanks for reporting the absence of the schema!

**Comment by jeffpatton1971** [comment]
What is the status of this? I find links to say use dnszones in your templates and still I cannot find it in the recommended shcemas.

Supported Resources Page
https://azure.microsoft.com/en-us/documentation/articles/resource-manager-supported-services/#networking
Note that this page says dns is resource manager enabled and gives the link for msdn recommended schema version.

http://schema.management.azure.com/schemas/2015-08-01/deploymentTemplate.json

jpatton@bastion:~$ curl -s http://schema.management.azure.com/schemas/2015-08-01/deploymentTemplate.json
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:9c7c1c92-0001-0075-7acf-65886c000000
Time:2016-02-12T19:54:33.7761046Z</Message></Error>

**Comment by jeffpatton1971** [comment]
Ok here is what I get when I attempt to use the dns resources
https://gist.github.com/jeffpatton1971/95e2b97bd7cfb20b10ba#file-error-txt

that gist has the sample project I created in vs2015 in order to test this out. I have used the recommended schema version per MSDN as well as the schema version that can be found on the quickstarts. Each of those fails with the same error

New-AzureRmResourceGroupDeployment : DeploymentNotFound: Deployment 'DnsTemplate' could not be found.

So, I ran this twice the first run in the error.txt file shows no error and the fun fact here is I have the template out the URLS, feel free to check those as they work just fine. So I know that the error is not in my code, I call the ip template the same way I call the dns template and the ip template just works. 

I think the problem is that the recommended schema 404's and the "documented" schema doesn't contain dns settings.

**Comment by wenwu449** [comment]
@jeffpatton1971, you are using a wrong schema link in one of your template, 2015-08-01 is the apiVersion for dnszone(to replace the "2015-05-04-preview" text), it should not be used in schema link.

If you have tried to deploy with the sample template for dns you found on GitHub, you shall understand schema is not a requirement for a deployment.

I agree schema does help a lot to write a template, we will work with the DNS team on the schema.

Meanwhile please understand this is a schema collaboration repo, questions about how to write a template and how to deploy may not be answered in time.
Thanks for your understanding.

**Comment by jeffpatton1971** [comment]
Wenjun,

I get that you think this is a template writing issue, and I understand that you feel that schemas are not required. But I will have to disagree, firstly, I’m fully capable of writing templates, this is not my issue, this template was pulled from the quick start samples, and second, ANY OF THE OTHER SCHEMA”S I click on simply open in a web browser, except this one.

This is why I brought the issue up. This seems to be a problem. Why do the other schema’s open and this one fails to. Why when I open the recommended schema do I not see DNS settings in it? This also seems to be a problem.

I don’t appreciate your closing this ticket as I don’t think this issue is resolved.

**Comment by wenwu449** [comment]
Jeff,

Can you try to change the line 2 of https://gist.github.com/jeffpatton1971/95e2b97bd7cfb20b10ba#file-dns-json to 
`"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json" `
or 
`"$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json"`
and try to deploy again?

Do you mind to share us the output of a deployment with this change?

Thanks
Wenjun

**Comment by jeffpatton1971** [comment]
Interesting turn of events, I can't right now as I'm about to leave for the day, but I should be able to tomorrow.

**Comment by jeffpatton1971** [comment]
Ok fellas, here's where we're at. I have created a template (https://gist.github.com/jeffpatton1971/e070035b568224e5ea84) to deploy five machines that will host our website. I have added in the code for the dns entry stuff, per the quickstart template listed earlier in this thread. I have changed the schema for the deployment to 2014-04-01-preview and I was happy to see the following when I deployed my vm's

VERBOSE: 3:25:37 PM - Resource Microsoft.Network/dnszones 'irisbylowes.com' provisioning status is succeeded
VERBOSE: 3:25:43 PM - Resource Microsoft.Network/dnszones/a 'irisbylowes.com/dev-web' provisioning status is succeeded

but when I attempted to view that record it failed.

nslookup dev-web.irisbylowes.com
Server:  dsldevice.attlocal.net
Address:  192.168.1.254

*** dsldevice.attlocal.net can't find dev-web.irisbylowes.com: Non-existent domain

honestly I didn't expect this to work right away, so I went to powershell.

(Get-AzureRmDnsRecordSet -ZoneName irisbylowes.com -ResourceGroupName dnsresourcegroup) |Where-Object -Property Name -Like 'dev*' |Select-Object -Property Name

Name
----
dev-bc
dev-bh
dev-bhon
dev-bi
dev-billing
dev-bm
dev-chronos
dev-ibl
dev-icst
dev-iiv
dev-iivfb
dev-marathon
dev-metrics
dev-mon
dev-newhub
dev-ops-marathon
dev-sfw
dev-ssr
dev-svp
dev-svr
dev-svu

in theory the resource I created was dev-web, so it should have appeared here but it did not.

**Comment by jtuliani** [comment]
Hi Jeff.  I tried a deployment using the schema you gave in your last comment.  The DNS part worked fine, I can see both the zone and the dev-web record set (now made easier by our new, shiny, DNS portal experience!)

Don't forget that using nslookup to verify won't work unless you either a) specify the Azure DNS name servers assigned to your zone explicitly, or b) delegate the domain to the Azure DNS name servers assigned to your zone.  Might that be the problem here?

Regarding publishing the schema...yes, that is on our must-do list as we get the Azure DNS service ready for GA.

**Comment by tdeheurles** [comment]
hey,
@jeffpatton1971 the schema works for me too ... I can't find the difference with yours ...

Here is the sample used:
```json
{
            "type": "Microsoft.Network/dnszones",
            "name": "testzone.local",
            "apiVersion": "2015-05-04-preview",
            "location": "global",
            "properties": {}
        },
        {
            "type": "Microsoft.Network/dnszones/a",
            "name": "testzone.local/test",
            "apiVersion": "2015-05-04-preview",
            "location": "global",
            "properties": {
                "TTL": 3600,
                "ARecords": [
                    {
                        "ipv4Address": "10.0.0.1"
                    },
                    {
                        "ipv4Address": "10.0.0.2"
                    }
                ]
            },
            "dependsOn": [
                "Microsoft.Network/dnszones/testzone.local"
            ]
}
```

@jtuliani is it possible to have just a copy or a not official list of possibilities for the DNS schema ?

**Comment by jtuliani** [comment]
When we publish the schema, it will be for the GA API version, which has some small tweaks relative to the Preview API version.  You can infer most of what you need from our [REST API documentation on MSDN](https://msdn.microsoft.com/en-us/library/azure/mt163862.aspx?f=255&MSPPError=-2147217396).  The template you posted previously looks OK from a DNS perspective, are you still having trouble with it?

**Comment by tdeheurles** [comment]
@jtuliani :
- Thanks for the API, I will give it an eye.
- This example works. It was in order to show a working example to @jeffpatton1971. 

Also seen an issue this morning with the portal template extraction failing on DNS (not surprising)

**Comment by jeffpatton1971** [comment]
Hey all, had to scrub some of my URLs somewhere I forgot to scrub out servernames of back-end stuff. I'll need to go through and check the rest of my things. 

At any rate, @jtuliani I'm looking forward to when this happens, as I'm actually getting almost the exact same error when I attempt to export a dns zone as a template. see the attached image, as that's gold jerry!
![schema-dns-error-portal](https://cloud.githubusercontent.com/assets/1192315/15183902/b05afb88-1758-11e6-8d28-ebc16d23bc4b.PNG)

**Comment by ifeoluwaokunoren** [comment]
Example of schema for dnszones: https://github.com/Azure/azure-resource-manager-schemas/blob/001c0a7ee838bc53008204886561ee1ffe554f78/schemas/2019-04-01/deploymentTemplate.json#L250
Closing issue - please open a new issue if this is still a problem.
