### ISSUE TITLE
Update Schema for Network RP to 2020-05-01

### ISSUE THREAD

**Issue by ssripadham** [Azure/azure-resource-manager-schemas#1027]
Please update the schema to 2020-05-01. I am updating ARM Template 
https://github.com/Azure/azure-quickstart-templates/pull/7671 & the older version of the schema is missing models.

![image](https://user-images.githubusercontent.com/4796246/84181905-6f497200-aa3e-11ea-9328-0accb339a45f.png)

**Comment by neilpeterson** [comment]
@ssripadham thanks for taking the time to open this issue. The schema looks good to go and needs to be added to the extension schema package. I've opened an extension issue to address. 

https://github.com/microsoft/vscode-azurearmtools/issues/825

Closing this one in lieu of the extension issue.

Thanks
