### ISSUE TITLE
Schemas for 2020-06-01

### ISSUE THREAD

**Issue by ahamad-MS** [Azure/azure-resource-manager-schemas#1032]
What is the ETA for the generation of 2020-06-01 scehams? 

For example, Event Grid Swagger for 2020-06-01 is published since 05/27/20: https://github.com/ahamad-MS/azure-rest-api-specs/blob/master/specification/eventgrid/resource-manager/Microsoft.EventGrid/stable/2020-06-01/EventGrid.json

**Comment by apclouds** [comment]
Hi @ahamad-MS this will get picked up next week.

**Comment by apclouds** [comment]
@ahamad-MS this has been deployed.

**Comment by ahamad-MS** [comment]
thank you @apclouds
