### ISSUE TITLE
Microsoft.Azure.CreateUIDef throws error when deploying in non-empty resource group

### ISSUE THREAD

**Issue by galiacheng** [Azure/azure-resource-manager-schemas#1042]
Affected application: Azure application offer using Microsoft.Azure.CreateUIDef.

Steps to reproduce:

1. create a new resource group, and add any resource to that resource group, such as virtual network.
2. deploy [Jenkins ](https://ms.portal.azure.com/#create/azure-oss.jenkinsjenkins) to that resource group.

Error happens: "this resource group contains existing resource"

I checked into the http request and found that, a request with the following command checks if the resource group is empty, and a response gets back with resource list. If the resource group has any kind of resource, error happens.
```
Microsoft_Azure_CreateUIDef.ValidationsGenerator.isResourceGroupEmpty
```

**Comment by apclouds** [comment]
@galiacheng this issue is not particular to ARM schemas. @alex-frankel do you if this would be an issue on the managed application side?

**Comment by alex-frankel** [comment]
Hi @galiacheng - this is by design. Managed Applications can only be deployed to an empty resource group.

**Comment by galiacheng** [comment]
@alex-frankel   @apclouds  It also happens on azure application, not managed application. We have an azure WebLogic offer, source code is https://github.com/wls-eng/arm-oraclelinux-wls/blob/develop/src/main/arm/createUiDefinition.json, offer link is https://portal.azure.com/#create/oracle.20191001-arm-oraclelinux-wls20191001-arm-oraclelinux-wls.
This offer deploys one WebLogic server node, we hope to allow customer to deploy several nodes in one resource group, it it not feasible as the error happens.
Do you have any suggestion for such kind of requirements? Thank you!

**Comment by alex-frankel** [comment]
Adding @ehissey - I think any marketplace offer will be subject to the same restriction. Evan, do you know if that is correct?
