### ISSUE TITLE
Need schema for Microsoft.ServiceBus

### ISSUE THREAD

**Issue by jbinard** [Azure/azure-resource-manager-schemas#105]
The schema are missing for Microsoft.ServiceBus provider for the following resource types:

namespaces:
- 2014-09-01

checkNamespaceAvailability:
- 2014-09-01
- 2015-08-01

operations:
- 2014-09-01
- 2015-08-01

**Comment by justinyoo** [comment]
I second. This schema is missing in the repository.

**Comment by antmarti-microsoft** [comment]
checkNamespaceAvailability and operations are not resources that can be deployed with templates, which is why they have been omitted from the schema.

For namespaces, our recommendation is to use a more recent API version with a published schema.
