### ISSUE TITLE
2018-05-01/subscriptionDeploymentTemplate.json requires output property "value"

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#1064]
When producing a dynamic list of outputs, an output property of 'value' is not required - [docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-outputs?tabs=azure-powershell#dynamic-number-of-outputs).

This is confirmed when looking at [2019-04-01/deploymentTemplate.json](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-04-01/deploymentTemplate.json#L1886).

However when looking at [2018-05-01/subscriptionDeploymentTemplate.json](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2018-05-01/subscriptionDeploymentTemplate.json#L620), this property is being enforced. 

This is causing a validation issue when using the ARM Tools VS Code extension. Extension issue with example can be found here https://github.com/microsoft/vscode-azurearmtools/issues/695#issuecomment-663235893 .

Thanks

**Comment by StephenWeatherford** [comment]
@armleads-azure, @apclouds, @anthony-c-martin, @jorgecotillo Status?  Thanks!

**Comment by StephenWeatherford** [comment]
@armleads-azure, @apclouds, @anthony-c-martin, @jorgecotillo. Guys??

**Comment by MarcusFelling** [comment]
@armleads-azure, @apclouds, @anthony-c-martin, @jorgecotillo - Can you help with a status update on this?

**Comment by anthony-c-martin** [comment]
As you mentioned, looks like it was missed as part of #824. I'll create a PR to replicate these changes.
