### ISSUE TITLE
Deployment template metadata

### ISSUE THREAD

**Issue by BernieWhite** [Azure/azure-resource-manager-schemas#1079]
The `metadata` property of a template and parameter files is valid. While ignored by Azure Resource Manager (ARM) it is demonstrated and valid for storing additional information.

[Our docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#metadata) indicate _"your JSON editor may warn you that the property isn't valid"_, however this can easily be fixed by adding a metadata property to the deployment and parameter file schema.

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "comments": "This template was developed for demonstration purposes.",
    "author": "Example Name"
  }
}
```

**Comment by BernieWhite** [comment]
@anthony-c-martin Any thoughts?

**Comment by BernieWhite** [comment]
@bmoore-msft Related to added `metadata` within schema.

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin Any thoughts?

This sounds like a good suggestion to me.
