### ISSUE TITLE
Microsoft.Web/sites/{name}/config/web

### ISSUE THREAD

**Issue by bcorkovic** [Azure/azure-resource-manager-schemas#110]
Looking at a schema, only "netFrameworkVersion" and "phpVersion" are available on 2015-08-01 and 2014-06-01. Is it possible to extend other parameters available through resources.azure.com like virtual applications/directories and remote debugging?

Is there any guidance on how to make pull requests?

**Comment by wenwu449** [comment]
Thank you @bcorkovic for helping on improving the schemas!
We have some basic guides about how to make change on schemas at https://github.com/Azure/azure-resource-manager-schemas/blob/master/README.md, please take a look and let us know if it is helpful.

**Comment by ifeoluwaokunoren** [comment]
Fix here: 
https://github.com/Azure/azure-resource-manager-schemas/pull/761
