### ISSUE TITLE
Microsoft.Authorization apiVersion is outdated in the schema

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#114]
The schema for `Microsoft.Authorization` Resource Provider lists only the `2015-01-01` apiVersion, but this version is not supported by the platform.  We need an updated schema to match platform support.

<img width="596" alt="screen shot 2016-03-08 at 8 45 11 am" src="https://cloud.githubusercontent.com/assets/466713/13611014/a7d2e74a-e51d-11e5-844d-77ab274daa21.png">
<img width="590" alt="screen shot 2016-03-08 at 8 32 33 am" src="https://cloud.githubusercontent.com/assets/466713/13611015/a7f04862-e51d-11e5-87fe-efe707bc894b.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ifeoluwaokunoren** [comment]
Schema published here: https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-01-01/Microsoft.Authorization.json

Closing since this is an old issue, please open a new issue if this is still a problem.
