### ISSUE TITLE
Deploy a node.js site using Azure Resourse Manager

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-resource-manager-schemas#119]
I'm struggling with a ARM deployment script for my node.js application. If I point to a repo with an MVC application it all works fine, but not using an node.js app.

Are there any specific settings for node.js sites? Here is the resource part of my script:

```
{
      "apiVersion": "2015-08-01",
      "name": "[parameters('nodeName')]",
      "type": "Microsoft.Web/sites",
      "location": "[resourceGroup().location]",
      "tags": {
        "[concat('hidden-related:', resourceGroup().id, '/providers/Microsoft.Web/serverfarms/', parameters('nodeName'))]": "Resource",
        "displayName": "Website"
      },
      "dependsOn": [
        "[concat('Microsoft.Web/serverfarms/', parameters('nodeName'))]"
      ],
      "resources": [
        {
          "apiVersion": "2015-08-01",
          "name": "web",
          "type": "sourcecontrols",
          "dependsOn": [
            "[resourceId('Microsoft.Web/Sites', concat(parameters('nodeName')))]"
          ],
          "properties": {
            "repoUrl": "https://github.com/microServiceBus/microservicebus.node.git",
            "branch": "master",
            "IsManualIntegration": true
          }
        }
      ],
      "properties": {
        "name": "[parameters('nodeName')]",
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', parameters('nodeName'))]",
        "siteConfig": {
          "appSettings": [
            {
              "Name": "hubUri",
              "Value": "[parameters('hubUri')]"
            },
            {
              "Name": "nodeName",
              "Value": "[parameters('nodeName')]"
            },
            {
              "Name": "organizationaId",
              "Value": "[parameters('organizationaId')]"
            }
          ]
        }
      }
    }
```

**Comment by bmoore-msft** [comment]
@davidebbo - any ideas?

**Comment by davidebbo** [comment]
Most likely this is unrelated to ARM deployment, and you'd see the same thing if you were to git push the same repo directly to the site. If so, I'd track this as a Web App issue ([forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview)) instead of here.

**Comment by wmmihaa** [comment]
@davidebbo Are you sure? The same script works if it points to a repo with an MVC app and I can deploy the repo if I don't use ARM.

**Comment by davidebbo** [comment]
You mean that same Node repo deploys and runs fine to Azure if you git push it directly? The MVC app is not relevant at this point.

**Comment by wmmihaa** [comment]
Yes it does

**Comment by davidebbo** [comment]
Can you be more specific about what doesn't work? Are you getting an error? At deployment time or runtime?

**Comment by wmmihaa** [comment]
This is my repo:https://github.com/microServiceBus/microservicebus.node

Clicking the "Deploy to Azure" button takes me to the portal and I can set up the app host plan and site, but then fails with:..... CRAP IT WORKS!

(sorry for taking your time, but it was failing before)

**Comment by davidebbo** [comment]
lol

**Comment by bmoore-msft** [comment]
David occasionally has that effect on things...

**Comment by wmmihaa** [comment]
@davidebbo Actually it didn't work. I was still referencing the mvc repo. The deploy error is:

OPERATION ID64118E5D90CE25C4
TRACKING ID1387fd5e-ee68-47cb-bb60-36e6f18bc772
STATUSConflict
PROVISIONING STATEFailed
TIMESTAMP3/12/2016, 12:34:21 AM
DURATIONPT40.1409026S
TYPEMicrosoft.Web/sites/sourcecontrols
RESOURCE ID/subscriptions/9055cad6-bd6a-46af-a38d-b0aeebf4cbcc/resourceGroups/74ff8902-2057-499a-bca8-36a699c2458f/providers/Microsoft.Web/sites/74ff8902-2057-499a-bca8-36a699c2458f/sourcecontrols/web
STATUSMESSAGE{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'."
  }
}
RESOURCE74ff8902-2057-499a-bca8-36a699c2458f/web

**Comment by davidebbo** [comment]
I see this error in your Kudu logs:

```
    <step title="Error occurred" date="2016-03-11T23:34:04.307" type="error" text="One or more errors occurred." stackTrace="   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass18_1.&lt;PerformBackgroundDeployment&gt;b__2()
   at Kudu.Contracts.Infrastructure.LockExtensions.TryLockOperation(IOperationLock lockObj, Action operation, TimeSpan timeout)
   at Kudu.Services.FetchHandler.&lt;&gt;c__DisplayClass18_0.&lt;PerformBackgroundDeployment&gt;b__1()" innerText="Warning: Permanently added &apos;github.com,192.30.252.129&apos; (RSA) to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

D:\Program Files (x86)\Git\bin\git.exe fetch origin --progress" innerStackTrace="   at Kudu.Core.Infrastructure.Executable.Execute(ITracer tracer, String arguments, Object[] args)
   at Kudu.Core.SourceControl.Git.GitExeRepository.&lt;&gt;c__DisplayClass30_0.&lt;FetchWithoutConflict&gt;b__0()
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry)
   at Kudu.Core.SourceControl.Git.GitExeRepository.ExecuteGenericGitCommandWithRetryAndCatchingWellKnownGitErrors[T](Func`1 func)
   at Kudu.Core.SourceControl.Git.GitExeRepository.FetchWithoutConflict(String remote, String branchName)
   at Kudu.Core.SourceControl.Git.LibGit2SharpRepository.FetchWithoutConflict(String remoteUrl, String branchName)
   at Kudu.Services.ServiceHookHandlers.ServiceHookHandlerBase.Fetch(IRepository repository, DeploymentInfo deploymentInfo, String targetBranch, ILogger logger)
   at Kudu.Services.FetchHandler.&lt;PerformDeployment&gt;d__12.MoveNext()" />
```

What's interesting is that it's using ssh, even though it's a public repo. From Kudu:

```
D:\home\site\repository>git remote -v
origin	git@github.com:microServiceBus/microservicebus.git (fetch)
origin	git@github.com:microServiceBus/microservicebus.git (push)
```

Are you an admin on this repo? If you click on Settings on GitHub, and Deploy Keys, are there any?

**Comment by wmmihaa** [comment]
Yes there are

**Comment by davidebbo** [comment]
Oh, I see the problem. Note how the remote had `git@github.com:microServiceBus/microservicebus.git` instead of `git@github.com:microServiceBus/microservicebus.node.git`. There must be a but in the hookup that gets confused when repo name has a period.

As a test, can create another repro with the same code but a dot less name to verify this theory?

/cc @suwatch

**Comment by wmmihaa** [comment]
sure... I'll be back shortly

**Comment by suwatch** [comment]
right on @davidebbo.   We have a bug.  The intention is to strip out `.git` suffix.  However, the code is too eager and strip out `.anything`.   We will fix it and should be available in our next update (ETA 2 weeks from now if not earlier).

**Comment by wmmihaa** [comment]
I forked the repo and updated the deploymentscript. - All works.

**Comment by wmmihaa** [comment]
@davidebbo Is there anything else I can do or test. It's getting late...(CET)

**Comment by wmmihaa** [comment]
@suwatch could you keep me in the loop for any changes?

**Comment by davidebbo** [comment]
@wmmihaa thanks, we have all the info we need now. It should be fixed in 2 or 3 weeks. If you find that it's not, feel free to ping this issue.

**Comment by wmmihaa** [comment]
@davidebbo Has this issue been implemented yet?

**Comment by suwatch** [comment]
@wmmihaa  we have rolled out the fix over the weekend.  Majority of regions should have the fix.   Please try it out and let us know.

**Comment by antmarti-microsoft** [comment]
As per suwatch's update, this has been fixed. Please open a new issue if this is still a problem.
