### ISSUE TITLE
Schema is missing for resource Microsoft.KeyVault/vaults with apiVersion "2019-09-01"

### ISSUE THREAD

**Issue by Yvand** [Azure/azure-resource-manager-schemas#1195]
The resource reference for apiVersion "2019-09-01" is documented here:
https://docs.microsoft.com/en-us/azure/templates/Microsoft.KeyVault/2019-09-01/vaults
Is it possible to add its corresponding schema?

**Comment by michal-halenka-datasentics** [comment]
This is probably duplicate of #759

**Comment by anthony-c-martin** [comment]
FWIW we could probably onboard KeyVault for [automatic schema generation](https://github.com/Azure/azure-resource-manager-schemas/tree/master/generator#onboarding-teams-to-autogeneration-pipeline) once https://github.com/Azure/azure-rest-api-specs/pull/11964 has been merged.

**Comment by anthony-c-martin** [comment]
Fixed by #1525
