### ISSUE TITLE
Schema for Microsoft.AAD/domainServices is missing the sku property

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-resource-manager-schemas#1196]
The schema for `Microsoft.AAD/domainServices` is missing the `sku` property.

The `sku` property is also missing from the ARM [template reference](https://docs.microsoft.com/azure/templates/microsoft.aad/allversions) too.

I believe `Microsoft.AAD/domainServices` has been on-boarded to autogenerate the ARM template schema so I checked the API specs ... and the `sku' property is missing from the API specs too.

When deploying an Azure AD Domain Services instance via the Portal, the ARM template created by the Portal sets the `sku` property.

@apclouds

**Comment by stephaniezyen** [comment]
Should be fixed now.
