### ISSUE TITLE
Schema is missing for resource Microsoft.Web/sites with apiVersion "2020-06-01"

### ISSUE THREAD

**Issue by rjsalaz** [Azure/azure-resource-manager-schemas#1227]
The resource reference for api version "2020-06-01" is documented here:
[https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites)
Can it be added to the corresponding schema?

**Comment by anthony-c-martin** [comment]
Fixed by #1691
