### ISSUE TITLE
Microsoft.KeyVault/vaults API version 2019-09-01 is not recognized by Schema 2019-04-01

### ISSUE THREAD

**Issue by zendu** [Azure/azure-resource-manager-schemas#1252]
My ARM template:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
...
  "resources": [
    {
      "type": "Microsoft.KeyVault/vaults",
      "apiVersion": "2019-09-01",
      "name": "[variables('keyVaultName')]",
      "location": "[variables('location')]",
...
```

Error message:
For full schema validation, consider updating the value to one of the following: "2014-12-19-preview", "2015-06-01", "2016-10-01". It is possible that the current resource version is valid but that a schema has not been generated. For more information see https://aka.ms/arm-tools-apiversion.

![image](https://user-images.githubusercontent.com/4323295/95411361-2d8ce300-08db-11eb-86dc-a47c3663b7bb.png)

**Comment by stephaniezyen** [comment]
Should be fixed now.
