### ISSUE TITLE
Microsoft.DevTestLab - can't find resource provider location

### ISSUE THREAD

**Issue by rcfontana** [Azure/azure-resource-manager-schemas#135]
I got the following error message when trying to create a custom image under DevTestLab:

New-AzureResourceGroupDeployment : 12:47:48 - Resource Microsoft.DevTestLab/labs/virtualMachines 'testlab/lab2' failed with message 'No registered resource provider found for location 'westeurope' and API version '2015-05-01-preview' for type 'labs/virtualMachines'. The supported api-versions are '2015-05-21-preview'. The supported locations are 'eastus, westus, westeurope, eastasia, eastus2, japaneast, japanwest, centralus'.'

If I try the suggested API version I get pretty much the same error.

**Comment by ifeoluwaokunoren** [comment]
Closing this issue since this not the current API version for this resource provider.
Please raise another issue if you still encounter this problem.
