### ISSUE TITLE
Schemas for Azure Container Service are missing

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#139]
Schemas for Azure Container Service are missing

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by wenwu449** [comment]
Schema for Microsoft.ContainerService has been added.

**Comment by ig-sinicyn** [comment]
Upping this, need a schema for 
```
"apiVersion": "2017-08-31"
"type": "Microsoft.ContainerService/managedClusters"
```
