### ISSUE TITLE
Schemas for VM Scale Sets are missing

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#140]
Schemas for VM Scale Sets are missing

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by wenwu449** [comment]
We have schemas for VM Scale Sets for apiVersion "2015-05-01-preview" and "2015-06-15", product team is working on schemas for latest apiVersions.

**Comment by pcgeek86** [comment]
@wenwu449 Thanks -- I tried to export an ARM Template in the Azure Portal and got errors about the VMSS schema missing.

**Comment by antmarti-microsoft** [comment]
Schemas containing virtualMachineScaleSets have since been published; closing. Please open a new issue if this is still a problem.
