### ISSUE TITLE
Storage Account Type is not auto-completed in Visual Studio Code

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#141]
Storage Account Type is not auto-completed in Visual Studio Code properly.

![image](https://cloud.githubusercontent.com/assets/466713/14689749/d936103c-0705-11e6-9971-6fd9d290f493.png)

https://github.com/Microsoft/vscode/issues/5574

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by wenwu449** [comment]
Similar issue with #138.

**Comment by pcgeek86** [comment]
@wenwu449 Sorry, forgot I filed that other one. Feel free to merge them if appropriate.

**Comment by antmarti-microsoft** [comment]
accountType is no longer a property for storageAccounts - closing due to age.
