### ISSUE TITLE
Export Template

### ISSUE THREAD

**Issue by ErenAtolgan** [Azure/azure-resource-manager-schemas#1411]
Hello

I have question when I export template from Azure the schema value is 
https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#
and not 
https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#
So the lasts versions are not referented. It is possible to change it ?
Sorry if it is not good topic.

**Comment by anthony-c-martin** [comment]
That's a great point, thank you for bringing this to our attention!

Note that we're not using this repo to track issues with Export, but I have added it to the internal backlog we have for the Export feature and we should get round to fixing this soon.
