### ISSUE TITLE
Schema for DNS Zones is missing

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#143]
Tried exporting an ARM template with DNS Zones in it, and received error:

> The schema of resource type 'Microsoft.Network/dnszones' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by antmarti-microsoft** [comment]
This schema has since been published and DNS Zones are now exportable.
