### ISSUE TITLE
Missing schema for Microsoft.Web/sites with API version 2020-06-01 or 2019-08-01

### ISSUE THREAD

**Issue by konopkap** [Azure/azure-resource-manager-schemas#1434]
I'm using the latest  schema 
```"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"```
but it seems to not recognized last two API's for Microsoft.Web/sites (the last suggested API is 2018-11-01 which is 2 version behind the latest one according to the docs https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites)
![image](https://user-images.githubusercontent.com/52398735/102772962-b5d23e80-4388-11eb-8cbc-93c9d30c4891.png)

I'm using the ARM Tools extension and according to their wiki (https://github.com/microsoft/vscode-azurearmtools/wiki/Unrecognized-Resource-API-Version) I'm opening issue here.

How can I use the latest API for Microsoft.Web/sites?

**Comment by ggonzalez94** [comment]
Looking forward to this. I've been authoring some templates that use app services heavily and I dont want to loose that nice intellisense support but using api from 2018 also seems a bit odd :/

**Comment by konopkap** [comment]
When can I expect any answer>

**Comment by konopkap** [comment]
Hello? Is anyone here to look through this issue?

**Comment by apclouds** [comment]
@naveedaz @Azure/azure-app-service-control-plane can you please investigate on your end?

**Comment by manu4rhyme** [comment]
+1
I'm also facing the same issue

**Comment by louisobasohan** [comment]
+2 same here

**Comment by konopkap** [comment]
@apclouds anyone has investigated it? It's a huge handicap in our everyday work.

**Comment by konopkap** [comment]
@apclouds, @naveedaz any update?

**Comment by anthony-c-martin** [comment]
Fixed by #1691
