### ISSUE TITLE
Microsoft.Portal Resource Provider missing schemas

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#144]
Tried exporting an ARM JSON Template that defines an Azure Dashboard resource, and received error:

> The schema of resource type 'Microsoft.Portal/dashboards' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by adamabdelhamed** [comment]
Hi Trevor,

This is on our radar.  No ETA to share, but it shouldn't be too long.

Thanks,
Adam

**Comment by rzellner** [comment]
Any updates on this?  I have a client that would like to be able to create a custom dashboard as part of an ARM template deployment.

Thanks.

**Comment by thepenguinmaster** [comment]
Same here. Any ability to add dashboard elements via API would be outstanding and make Dashboard customization a worth while feature for our organization. Otherwise we have little interest in dashboard customization.

**Comment by bdschaap** [comment]
Any update on when this will be supported?

**Comment by avishnyakov** [comment]
Same-same, @adamabdelhamed 

Lack of documentation on Microsoft.Portal/dashboards prevents automation scenarios. We pretty much need to reverse-engineer tons of JSON in order to scale and automate dashboard creation for services and apps. All similar to what @pcgeek86  and @rzellner described.

Guidance on this would be appreciated.

**Comment by ifeoluwaokunoren** [comment]
Schema available here: https://github.com/Azure/azure-resource-manager-schemas/blob/44b774b962da4d10bb2dd3635346da286d1406ef/schemas/2019-04-01/autogeneratedResources.json#L44
