### ISSUE TITLE
Missing schema for Microsoft.RecoveryServices vaults/backupPolicies 2019-06-15

### ISSUE THREAD

**Issue by MarcusFelling** [Azure/azure-resource-manager-schemas#1450]
Discovered in https://github.com/microsoft/vscode-azurearmtools/issues/1131

**Comment by MarcusFelling** [comment]
@leni-msft will https://github.com/Azure/azure-resource-manager-schemas/pull/1229 fix this? If so, who is on point to review?

**Comment by MarcusFelling** [comment]
@jorgecotillo @anthony-c-martin Can you lend a hand?

**Comment by anthony-c-martin** [comment]
> @jorgecotillo @anthony-c-martin Can you lend a hand?

The PR you linked should fix this. I added some comments and will wait for Lei to respond.

**Comment by anthony-c-martin** [comment]
#1451 has now been merged to fix this. The schema is available here:
https://github.com/Azure/azure-resource-manager-schemas/blob/55af2a64aacd674e58063a0d0108160f74d4642d/schemas/2019-06-15/Microsoft.RecoveryServices.Backup.json#L64
