### ISSUE TITLE
Azure Automation schemas are missing

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#147]
> The schema of resource type 'Microsoft.Automation/automationAccounts' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)

![image](https://cloud.githubusercontent.com/assets/466713/14937465/2028a7ea-0ec5-11e6-83bf-3c792d43f412.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by nneubauer** [comment]
+1, I have opened an issue #1908 on the quickstarts repo as well for that.

**Comment by animetauren** [comment]
+1, I noticed that there was a PR for this schema a bit back: #41 but got closed. This schema would be very helpful for cloud tasks and automation.

**Comment by wenwu449** [comment]
Microsoft.Automation schema has been added.
