### ISSUE TITLE
Regression: "Microsoft.RecoveryServices/vaults" no longer lists most api versions

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-resource-manager-schemas#1470]
@anthony-c-martin 

The newest schema no longer lists any Microsoft.RecoveryServices/vaults versions other than 2016-06-01.

Even the most recent one is missing (2018-01-10).

Previous (a month or two ago):
![image](https://user-images.githubusercontent.com/6913354/105112552-221f8b00-5a78-11eb-99e3-c4dacfa6c87c.png)

Current:
![image](https://user-images.githubusercontent.com/6913354/105112444-e5539400-5a77-11eb-8d0c-84055207b99c.png)

**Comment by StephenWeatherford** [comment]
This will block me from updating the schemas in the ARM extension

**Comment by anthony-c-martin** [comment]
@apclouds, @jorgecotillo FYI

The RecoveryServices swagger specs only declare support for the 2016-06-01 API version, so automatic schema generation has done the right thing. We may need to back out the onboarding regardless if we can't get a fix in for this quickly.

**Comment by anthony-c-martin** [comment]
#1451 is the PR which removed these API versions. @leni-msft - please could you take a look?

**Comment by StephenWeatherford** [comment]
@leni-msft We're going to need to ship the ARM tools extension for vscode again in the next couple of weeks.  If this isn't fixed before then, users will start getting false positives for usages of all of these (including the most recent api version).

**Comment by leni-msft** [comment]
hi @StephenWeatherford , which root schema is ARM tools extension using? I'll try to restore some references of old RecoveryService schemas authored manually.
@anthony-c-martin pls let me know if there's better way to resolve this quickly.
