### ISSUE TITLE
Missing schemas for Microsoft.Web Resource Provider

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#148]
> The schema of resource type 'Microsoft.Web/connections' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)
> 
> Could not get resources of the type 'Microsoft.Web/sites/config'. Resources of this type will not be exported. (Code: ExportTemplateProviderError)
> 
> Could not get resources of the type 'Microsoft.Web/sites/extensions'. Resources of this type will not be exported. (Code: ExportTemplateProviderError)

![image](https://cloud.githubusercontent.com/assets/466713/14937476/80a9db8e-0ec5-11e6-97f7-adfbbaafd3ab.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by MathieuDiepman** [comment]
Having the same issue; not sure where to start fixing it.

```
Export template operation completed with errors. Some resources were not exported. Please see details for more information. (Code: ExportTemplateCompletedWithErrors)
 •Could not get resources of the type 'Microsoft.Web/sites/config'. Resources of this type will not be exported. (Code: ExportTemplateProviderError)

•Could not get resources of the type 'Microsoft.Web/sites/extensions'. Resources of this type will not be exported. (Code: ExportTemplateProviderError)

```

**Comment by Shivu1042** [comment]
Having the same issue.. is there any work around for this.

**Comment by MathieuDiepman** [comment]
Yes. deploy from visual studio, find the deployment in azure and export the template from the deployment instead of the actual web api component

**Comment by Shivu1042** [comment]
thanks. There are no errors this way. But i m still not able to see the connection between the app service related resources to vnet in any of the templates. My objective is to create a template which has app service resources and a vnet resource to which the app service is linked. Any help greatly appreciated. 

Thanks

**Comment by arturoqu** [comment]
hey Matthieu 👍 
Can you please elaborate a bit more?, do you mean create the template in VS and then deploy  from VS then go to the portal to export the template, that way?

Thanks.

**Comment by MathieuDiepman** [comment]
exactly; the trick was to export from the _deployment_ on the portal instead of the automation section of the resource group on the portal
Basically select the resource group, select deployments, select the deployment you want and you can view the template from there

**Comment by kiazhi** [comment]
Hit the same issue. Yes. If the person has deployed from his ARM template using JSON, follow @MathieuDiepman's method by selecting Resource Group name > Deployments option and it will get you there to view the template. But if someone is a newbie that uses GUI deployment or had made changes to the environment and decided to extract the current configuration... That is an issue because "Config" and "SiteExtensions" are not generated.

**Comment by bgoldman69** [comment]
this is a terrible work around.

**Comment by bgoldman69** [comment]
I would go so far as to give zero stars for effort here Microsoft.

**Comment by julienlau** [comment]
nightmare...

**Comment by oviliz** [comment]
...I love M$...

**Comment by ifeoluwaokunoren** [comment]
These resource types have since been added to the template schema.
