### ISSUE TITLE
API / schema versioning strategy for Microsoft.Sql resource provider

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-resource-manager-schemas#1486]
The [Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#preview-versions) describe the use of _preview_ APIs and states _preview_ APIs are not subject to the  same stability or lifecycle guarantees as generally available APIs. Additionally the guidelines state preview APIs should be retired within 12 months.

When deploying SQL resources via ARM tempalte from the Microsoft.Sql resource provider, the most recent _stable_ API version is `2015-05-01` (almost 6 years ago) and all subsequent API versions have been marked as _preview_.

What strategy is the Microsoft.Sql resource provider team taking when versioning their API / schema?
Is there any documentation describing how customers should interpret the Microsoft.Sql API versions to identify stable and preview APIs?

**Comment by apclouds** [comment]
Hi @MWL88  this is an RP specific issue relating to their process of releasing preview api versions. We will discuss internally with the SQL team to see what can be done here.

**Comment by metaxasa** [comment]
Hi @apclouds - is there anything you can share about the outcome of those discussions? Alternatively, should we be raising an issue elsewhere in order to get this resolved? Thanks!

**Comment by metaxasa** [comment]
Looks like there's at least two other RPs in a similar situation:

[Authorizations](https://github.com/Azure/azure-rest-api-specs/issues/12419)
[Stream Analytics](https://github.com/Azure/azure-rest-api-specs/issues/14242)
