### ISSUE TITLE
Not able to access  https://schema.management.azure.com/schemas/2020-09-01/Microsoft.NetApp.json# 

### ISSUE THREAD

**Issue by rakeshrocks** [Azure/azure-resource-manager-schemas#1488]
2020-09-01 schema under  https://schema.management.azure.com/schemas/ is updated automatically as NetApp Schema's are atuo-generated , but I could not access  https://schema.management.azure.com/schemas/2020-09-01/Microsoft.NetApp.json# 
This was not the case with older schema's. Could you please help us why this link is broken?

**Comment by apclouds** [comment]
@rakeshrocks this should be addressed by eod.

**Comment by rakeshrocks** [comment]
please let us know if 2020-09-01 or later date are published. We are waiting for them to be published so that we can write azure policy based on the new Microsoft.NetApp.json

**Comment by apclouds** [comment]
@rakeshrocks sorry for the delay. There was an issue in our schemas publishing job. We are working on a fix to rollout this week.

**Comment by anthony-c-martin** [comment]
The latest schemas have been pushed to schema.management.azure.com and I'm able to access https://schema.management.azure.com/schemas/2020-09-01/Microsoft.NetApp.json.
