### ISSUE TITLE
Microsoft.KeyVault/vaults/secrets stores new version on each deployment

### ISSUE THREAD

**Issue by stan-sz** [Azure/azure-resource-manager-schemas#1494]
A template to store a KV secret using Microsoft.KeyVault/vaults/secrets on a redeployment with the same secret value always creates a new version of the secret (despite the secret value being the same as in older version). All such versions are enabled, which will make a bit more work when the secret will have to be renewed/invalidated.

This is also brought up in https://stackoverflow.com/questions/58823588/how-to-update-a-secret-in-azure-key-vault-only-if-changed-in-arm-templates-or-ch.

Any template param to skip creating new version if the secret's value is the same?

**Comment by jlichwa** [comment]
I tried to reproduce, but if secret you are passing has exactly same parameters, new version is not created.
I used below script and my vault has only one secret version after multiple redeployements:
```
{
            "type": "Microsoft.KeyVault/vaults/secrets",
            "apiVersion": "2019-09-01",
            "name": "[concat(parameters('keyVaultName'), '/', parameters('secretName'))]",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[resourceId('Microsoft.KeyVault/vaults', parameters('keyVaultName'))]"
            ],
            "properties": {
                "value": "[parameters('secretValue')]"
            }
}
```
If ANY of parameters is different then new version is created and that is expected behavior.

**Comment by stan-sz** [comment]
Indeed. I must have had some variance in the secret value. Thanks for confirming!
