### ISSUE TITLE
ClearDB database location formatting

### ISSUE THREAD

**Issue by Cloudenius** [Azure/azure-resource-manager-schemas#150]
For most of the resources I deploy with JSON, I use the following code to specify a location:

`"location": "[resourceGroup().location]",`

This will deploy the resource in to the same location as the Resource Group. If you deploy the resource in - for example - West-Europe, this will create a parameter "westeurope". When you deploy a ClearDB database, the format of the location "westeurope" is not accepted. For ClearDB databases, the region needs to be formatted like "West Europe". At this time, I have to manually specify this parameter as "West Europe".

Is it possible to accept the "westeurope" format for ClearDB databases?

**Comment by antmarti-microsoft** [comment]
ClearDb has since been deprecated; closing issue.
