### ISSUE TITLE
Miss schema for providers in rest-api-specs/2020-09-01-hybrid.json

### ISSUE THREAD

**Issue by v-tsun** [Azure/azure-resource-manager-schemas#1508]
Hey, this is azure stack team. we have specs https://github.com/Azure/azure-rest-api-specs/blob/master/profile/2020-09-01-hybrid.json for azure stack. But we are still missing schema for microsoft.compute with api version 2020-06-01 and microsoft.keyvault with api version 2019-09-01.

**Comment by bganapa** [comment]
@anthony-c-martin to help route this issue.

**Comment by anthony-c-martin** [comment]
I've created #1510 & #1511 for the individual RPs. In future, please create a single issue for each missing schema as they must be handled independently by each team.
