### ISSUE TITLE
What is happening with on-boarding all RPs for schema autogeneration?

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-resource-manager-schemas#1513]
A few weeks ago most active PRs in the [Onboard all RPs for schema autogeneration](https://github.com/Azure/azure-resource-manager-schemas/projects/1) project were moved to the `Done` column and closed ... not merged.

There are still a few significant RPs that have not been onboarded. For example, Microsoft.Compute, most of Microsoft.Network and Microsoft.Web.

What is the current plan for onboarding all RPs for schema autogeneration? Thanks

**Comment by apclouds** [comment]
@MWL88 we are planning on walking through the autogenerated schemas for these RPs this semester. It was not done automatically given the complexity of these RPs and high impact a broken schema would cause. Our goal is to have all remaining RPs onboarded by 6/1.
