### ISSUE TITLE
Missing schema for Microsoft.Storage 2021-01-01

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-resource-manager-schemas#1515]
RP Microsoft.Storage appears to be onboarded for schema auto-generation but the schama for the latest API version is missing.

**Comment by anthony-c-martin** [comment]
This is because it has been missed from the config at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/readme.azureresourceschema.md. I've raised https://github.com/Azure/azure-rest-api-specs/issues/13112. @leni-msft FYI

**Comment by MWL88** [comment]
The PR (Azure/azure-rest-api-specs#13114) associated with the issue (Azure/azure-rest-api-specs#13112) reference in an earlier comment was merged yesterday.

How long does the process take for the updated OpenAPI specs to be published as updated ARM JSON schema on schema.management.azure.com?

**Comment by stephaniezyen** [comment]
Merged as per the PR above.
