### ISSUE TITLE
ARM Storage resource provider error

### ISSUE THREAD

**Issue by ayushgorya** [Azure/azure-resource-manager-schemas#154]
I am trying to get storage accounts metrics for my storage account using Azure Insights.

for the resource uri "/subscriptions/{0}/resourceGroups/{1}/providers/Microsoft.Storage/storageAccounts/{2}/api-version=2015-05-01-preview"

i am getting error as 
"NoRegisteredProviderFound: No registered resource provider found for location 'eastus' and API version '2015-07-01' for type 'storageAccounts'. The supported api-versions are '2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, eastus2stage, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, "

Can someone please help to investigate.

Also the Microsoft.Storage resource provider is registered with my subscription.

Thanks,
Ayush Gorya

**Comment by QuasarSE** [comment]
Try with ?api-version... rather than /api-version...

**Comment by antmarti-microsoft** [comment]
As QuasarSE mentioned, it looks like a problem with the URL format. Please re-open this if still an issue.
