### ISSUE TITLE
Missing schema for Microsoft.Compute: virtualMachines/extensions type AzureDiskEncryption

### ISSUE THREAD

**Issue by matsest** [Azure/azure-resource-manager-schemas#1545]
routed from [twitter](https://twitter.com/satya_vel/status/1369664904555241475)

- resource type: "Microsoft.Compute/virtualMachines/extensions"
- Extension properties:
  - publisher: Microsoft.Azure.Security
  - type: AzureDiskEncryption

For validation of templates using the VS Code ARM tools extension, the validator seems to only find "type: IaasAntimalware" for validation if publisher is set to "Microsoft.Azure.Security".

![image](https://user-images.githubusercontent.com/10927304/110650039-78789280-81ba-11eb-8efb-f217d8a67b16.png)

The schema for this specific extension type is published on msdocs [here](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/azure-disk-enc-windows#schema-v22-no-aad-recommended) but I can't seem to find it in this repo or in https://github.com/Azure/azure-rest-api-specs - so I guess that's why the validation fails. This is similar for all the suggested API versions.

**Comment by anthony-c-martin** [comment]
Thanks for raising this!
