### ISSUE TITLE
Microsoft.Security/pricings API Version 2018-06-01 Schema Missing

### ISSUE THREAD

**Issue by BenJ-Wisco** [Azure/azure-resource-manager-schemas#1683]
Microsoft.Security/pricings API Version 2018-06-01 Schema Missing which is the latest according to the [ARM Template reference page](https://docs.microsoft.com/en-us/azure/templates/microsoft.security/2018-06-01/pricings?tabs=json)

In VS Code I receive the following

For full schema validation, consider updating the value to one of the following: "2017-08-01-preview". It is possible that the current resource version is valid but that a schema has not been generated. For more information see https://aka.ms/arm-tools-apiversion.

Since 2018-06-01 is very different than 2017-08-01-preview, it would be awesome if it could be brought in

**Comment by stephaniezyen** [comment]
Related: #1749
