### ISSUE TITLE
CreateUiDefinition: How to create Button ?

### ISSUE THREAD

**Issue by sarthakvijayvergiya** [Azure/azure-resource-manager-schemas#1684]
How can we add button like 'Find Device' shown below image ?
![image](https://user-images.githubusercontent.com/18403281/117122997-1a2ff080-adb4-11eb-9307-fb8d1281574a.png)

**Comment by sarthakvijayvergiya** [comment]
@quinn-mchugh Can you help us ?

**Comment by QuinnMcHugh** [comment]
@sarthakvijayvergiya There's no ability in CreateUiDefinition to add buttons. The list of ready-made controls available can be seen here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/create-uidefinition-elements

**Comment by sarthakvijayvergiya** [comment]
@quinn-mchugh Thanks for the promptly response, but then how the partners are using in marketplace templates and there are many I am attaching few for your reference..
Is there any other latest schema exist ?

![image](https://user-images.githubusercontent.com/18403281/117158912-752a0d80-addd-11eb-8ec3-a245ef234496.png)

https://portal.azure.com/#create/1604376875527.wedx-iot-edge-noderedplan-nodered-node12-iot-edge
https://portal.azure.com/#create/azure-media-services.live-video-analytics-edgelive-video-analytics-edge
https://portal.azure.com/#create/aveva.iotviewmoduleiotview

**Comment by QuinnMcHugh** [comment]
These Marketplace offers aren't using no-code CreateUiDefinition for their solution. The publishers have created a Portal extension and written custom code (HTML/JS) to obtain this behavior. For further Portal or CreateUiDefinition questions, I'm adding @garykeong who is the owner for this area

**Comment by sarthakvijayvergiya** [comment]
Thanks @QuinnMcHugh for the useful information.
