### ISSUE TITLE
Unable to load scheme. No schema request available

### ISSUE THREAD

**Issue by richredgrave** [Azure/azure-resource-manager-schemas#1700]
Hi,
All ARM deployments are currently failing for me suddenly today with the error that no schema request is available

![image](https://user-images.githubusercontent.com/47722074/117826398-0b3fb700-b268-11eb-9c68-aa09d2d263b7.png)

for reference, I am using uksouth and version 2019-04-01

Anyone else getting this too?

**Comment by apclouds** [comment]
Hi @richredgrave this is a known issue that impacts the Portal editor only. It does not prevent you from deploying. We recommend using the VSCode ARM Tools Extension when authoring/debugging your ARM templates to get the latest intellisense and validation.
