### ISSUE TITLE
Serialization Issues with Microsoft.Azure.Management.Compute.Models and Microsoft.Azure.Management.Network.Models

### ISSUE THREAD

**Issue by chchadha** [Azure/azure-resource-manager-schemas#1734]
When attempting to make a put request (i.e [Create VM](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate) or [Create NIC](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/createorupdate)). The API returns bad request due to not finding the properties. For example, 
```

[JsonProperty(PropertyName = "properties.ipConfigurations")]
public IList<NetworkInterfaceIPConfiguration> IpConfigurations { get; set; }
//API Will throw a bad request because it can't find properties.ipConfgurations
//However if the model was structured as ....
public class NetworkInterface
{
  public NetworkInterfaceProperties Properties{get;set;}
}
public class NetworkInterfaceProperties
{
    public IList<NetworkInterfaceIPConfiguration> IpConfigurations { get; set; }
}
//API is able to process the request.
```

**Comment by apclouds** [comment]
@chchadha closing this issue as it does not pertain to ARM schemas. You might want to open this issue in the https://github.com/Azure/azure-sdk repo instead.
