### ISSUE TITLE
Missing Azure Cycle Cloud and Cloud Service -Classic (in azure-mgmt) jar 

### ISSUE THREAD

**Issue by braveamita** [Azure/azure-resource-manager-schemas#1740]
I am looking for these two services (Cycle Cloud and Cloud Service -Classic) jar for integrating my application with Azure cloud.
Unable to find any SDK jar related to these services. Is there any specific reason to not providing these services jars.

**Comment by apclouds** [comment]
Please raise this issue in the SDK repo https://github.com/Azure/azure-sdk instead as we do not track/handle these type of issues here.
