### ISSUE TITLE
Need overall Azure Services relationship Doc

### ISSUE THREAD

**Issue by braveamita** [Azure/azure-resource-manager-schemas#1741]
Looking for relationship Azure Services documents which give the clear picture of inter depended services. I have checked the Microsoft Azure Document, it gives the relationship for each service.

**Comment by apclouds** [comment]
Hi @braveamita here is a link to our [ARM Template Reference](https://docs.microsoft.com/en-us/azure/templates/) that defines the properties available per each api version. For your question, I believe you are looking for the https://github.com/MicrosoftDocs/azure-docs repo
