### ISSUE TITLE
Microsoft.Security/pricings 2018-06-01 not available

### ISSUE THREAD

**Issue by BenJ-Wisco** [Azure/azure-resource-manager-schemas#1749]
[Microsoft.Security/pricings](https://docs.microsoft.com/en-us/azure/templates/microsoft.security/2018-06-01/pricings?tabs=json) 2018-06-01 is not available for validation or Intellisense

**Comment by anthony-c-martin** [comment]
@BenJ-Wisco - this should be working, as long as you're using the subscription template schema in your template (`"$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#"`).

Please reopen this if you're still seeing this issue with the subscription template schema.
