### ISSUE TITLE
The latest API version for resource Microsoft.RecoveryServices/vaults/backupstorageconfig fails to deploy if the Microsoft.RecoveryServices/vaults resource is declared in the same template

### ISSUE THREAD

**Issue by MWL88** [Azure/azure-resource-manager-schemas#1754]
Deploying the template below, to an empty resource group, fails with a strange error. The `vaults` resource is successfully created, however, the `vaults/backupstorageconfig` resource fails.

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "rsvName": {
      "defaultValue": "[concat('a', uniqueString(resourceGroup().id))]",
      "type": "String"
    },
    "resourceLocation": {
      "defaultValue": "[resourceGroup().location]",
      "type": "String"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.RecoveryServices/vaults",
      "apiVersion": "2021-01-01",
      "name": "[parameters('rsvName')]",
      "location": "[parameters('resourceLocation')]",
      "sku": {
        "name": "RS0",
        "tier": "Standard"
      },
      "properties": {}
    },
    {
      "condition": true,
      "type": "Microsoft.RecoveryServices/vaults/backupstorageconfig",
      "apiVersion": "2018-12-20", // 2016-12-01
      "name": "[concat(parameters('rsvName'), '/vaultstorageconfig')]",
      "properties": {
        "storageModelType": "LocallyRedundant",
        "crossRegionRestoreFlag": false
      },
      "dependsOn": [
        "[resourceId('Microsoft.RecoveryServices/vaults', parameters('rsvName'))]"
      ]
    }
  ],
  "outputs": {}
}
```

The error message is:
```
Could not perform the operation as VM no longer exists.
Stop protecting virtual machine without deleting backup data. More details at http://go.microsoft.com/fwlink/?LinkId=808124  (Code:ResourceNotFound)
```

If I wait about 60 seconds and _just_ redeploy the template, the template deploys successfully.

If I now update the API version for the `Microsoft.RecoveryServices/vaults/backupstorageconfig` resource to be `2016-12-01` (instead of `2018-12-20`) and deploy the template to a new empty resource group, the deployment is successful.

I want to deploy and configure Recovery Services Vault resources declaratively, via an ARM template, but the requirement (with API version `2018-12-20`) to wait about 60 seconds between creating the vault resource and setting its storage configuration makes the declarative approach quite difficult.

According to the OpenAPI specs for the `vaults/backupstorageconfig` resource and the ARM template IntelliSense in VS Code, I need to use the later API version to be able to set the cross region restore configuration and the zonal storage replication configuration.

How should I configure the `vaults/backupstorageconfig` resource using the latest API version so it is deployable in a template that also declares the `vaults` resource?

**Comment by apclouds** [comment]
Hi @MWL88 this is a service issue, not an issue in schemas. We added the service contacts above.
