### ISSUE TITLE
Schema for Microsoft.Devices/IotHubs missing

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-resource-manager-schemas#179]
I tried to download the template from Azure Portal, but got the below error.

The schema of resource type **'Microsoft.Devices/IotHubs' is not available**. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)

Thanks,
Pradebban Raja

**Comment by ifeoluwaokunoren** [comment]
Hi,
Schema for microsoft.devices/iothubs exists for 2018-04-01 api version here: https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2018-04-01/Microsoft.Devices.json
Closing issue, please reopen if this is still an issue.
