### ISSUE TITLE
Onboarding Microsoft.Purview to Schema Auto-Generation

### ISSUE THREAD

**Issue by meco0597** [Azure/azure-resource-manager-schemas#1844]
Microsoft.Purview is doing the GA sign off review for control plane and we need to onboard ourselves to the schema auto generation. Could we please get some help on this? 

Here is a link to the swagger for the schema generation: [Purview GA Control Plane Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/resource-manager/Microsoft.Purview/stable/2021-07-01/purview.json)

**Comment by anthony-c-martin** [comment]
Here's the PR to onboard: https://github.com/Azure/azure-resource-manager-schemas/pull/1845

@jorgecotillo mind taking a look?

**Comment by anthony-c-martin** [comment]
Onboarding is done!
