### ISSUE TITLE
error thrown for extensionResources which is required for extendedLocation

### ISSUE THREAD

**Issue by junczhan** [Azure/azure-resource-manager-schemas#1877]
![image](https://user-images.githubusercontent.com/89912021/131658076-901bafd3-e7f5-4dcb-80bd-58deeb0e5214.png)

**Comment by junczhan** [comment]
email me junczhan@microsoft.com if you need more info

**Comment by anthony-c-martin** [comment]
@junczhan - `extensionResources` isn't a valid ARM Template JSON property, so the validation is correct here. I'll close this issue and follow up via email.
