### ISSUE TITLE
Microsoft.Authorization/roleAssignments is not recognized

### ISSUE THREAD

**Issue by 50Wliu** [Azure/azure-resource-manager-schemas#1889]
I'm coming here from https://github.com/microsoft/vscode-azurearmtools/issues/1366. When writing an ARM template in VS Code, Microsoft.Authorization/roleAssignments shows as an unknown type:
![Microsoft.Authorization/roleAssignments unknown type](https://user-images.githubusercontent.com/2766036/132524837-fb321e21-a7f0-4812-ae0d-2742597239af.png)

Which is odd, because I do see it in the schemas: https://github.com/Azure/azure-resource-manager-schemas/blob/main/schemas/2015-07-01/Microsoft.Authorization.Authz.json (but under unknown_resourceDefinitions instead of resourceDefinitions, could that have something to do with it?)

**Comment by anthony-c-martin** [comment]
@StephenWeatherford - this resource should exist in the list of available resources (see here: https://github.com/Azure/azure-resource-manager-schemas/blob/53e06b4e3b361c011b643ef1262a23189490add8/schemas/common/autogeneratedResources.json#L1514)

This was added *relatively* recently - is it possible that the latest ARM tools release took place before this was added? Is there a way to easily check?

**Comment by StephenWeatherford** [comment]
Good to know, quite likely then.  We can't currently pick up new schemas until Bhavya makes changes to accept the symbolic name changes.  I'll go ahead and close this out for now, thanks.
