### ISSUE TITLE
Onboarding Microsoft.ExtendedLocation to Schema Auto-Generation

### ISSUE THREAD

**Issue by aditimalladi** [Azure/azure-resource-manager-schemas#1914]
Microsoft.ExtendedLocation is going GA and would like to onboard RP for Schema Auto Generation. 
Could we please get help with this? 
Here is the Swagger to onboard with autogen: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/extendedlocation/resource-manager/Microsoft.ExtendedLocation/stable/2021-08-15/customlocations.json

Happy to assist with any follow ups! Thanks.

**Comment by anthony-c-martin** [comment]
Thanks for raising this! I've created PR #1915 to enable this.
