### ISSUE TITLE
Missing Schema Microsoft.HDInsight

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-resource-manager-schemas#192]
There is no template for HDInsight event though the template it is accepted when you push to the portal.

**Comment by ppanyukov** [comment]
Quick ping. Any progress on this? Authoring ARM templates for HDInsight is very difficult without schema.

**Comment by arturoqu** [comment]
I am having this issue as well, after creating a deployment thru the portal and trying to export the template, for re-use, any fix or workaround???

**Comment by antmarti-microsoft** [comment]
The Microsoft.HDInsight schema has since been published, so this should no longer be occurring. Please open a new issue if this is still a problem.
