### ISSUE TITLE
Expected "array" green squiggles when passing array JSON ARM

### ISSUE THREAD

**Issue by aeschli** [Azure/azure-resource-manager-schemas#193]
_From @lwsrbrts on July 5, 2016 22:12_

- VSCode Version: 1.2.1
- OS Version: Windows 10 Build 14372

Steps to Reproduce:

1. Define a parameter of type array in the appropriate parameters section of the template.
2. In a section that requires an array, pass only the parameter instead of starting and ending with square brackets.

This specifically relates to an issue I see when using the dnsServers setting to define the DNS servers to use when creating a NIC.

In the following piece of code, the dnsServers value doesn't validate, despite it being passed as an array - I appreciate this may not even be possible to fix given the types declared may simply not be validated at this level.

```
"parameters": {
    "onPremDNSServers": { 
      "type": "array"
    }
},
"resources": {

    {
      "apiVersion": "2015-06-15",
      "type": "Microsoft.Network/networkInterfaces",
      "name": "[concat(parameters('BEvirtualMachineNames')[copyIndex()],'-nic')]",
      "location": "[resourceGroup().location]",
      "copy": {
        "name": "BEnicLoop",
        "count": "[length(parameters('BEvirtualMachineNames'))]"
      },
      "dependsOn": [
      ],
      "properties": {
        "ipConfigurations": [
          {
            "name": "ipconfig1",
            "properties": {
              "privateIPAllocationMethod": "Static",
              "privateIPAddress": "[concat(parameters('BEsubnetIPPrefix'),copyIndex(parameters('BEnicStartingAddress')))]",
              "subnet": {
                "id": "[variables('BEsubnetRef')]"
              }
            }
          }
        ],
        "dnsSettings": {
          "dnsServers": "[parameters('onPremDNSServers')]"
        }
      }
    }
}
```
Despite the green squiggles, the ARM template will deploy successfully, it seems that just because there are no square brackets immediately after `"dnsServers":` - the green squiggles appear with `Incorrect type. Expected "array"`

The full ARM template (which works when deployed) is attached. Line 153 gives the green squiggles.

[azuredeploy.zip](https://github.com/Microsoft/vscode/files/348739/azuredeploy.zip)

_Copied from original issue: Microsoft/vscode#8776_

**Comment by aeschli** [comment]
The schema at http://schema.management.azure.com/schemas/2015-08-01/Microsoft.Network.json#/resourceDefinitions/networkInterfaces specifies that dnsServers is an array of type string.

**Comment by QuasarSE** [comment]
It's just that neither VS Code or Visual Studio intellisense have any notion that what looks like a string in the source could later be treated by ARM's template processing as an array or object, based on the expression result.  i.e., at the Intellisense level, there is no evaluation of the string contents to determine an eventual "type".  

If you have the VS Code extension for ARM templates loaded, it contributes by being able to parse out the contents of expression strings, checking that you haven't blundered by misspelling "parameters" or adding an extra parenthesis.  But the extension, (at least so far), can't override Intellisense flagging schema "violations" like the string vs. array issue you mention.

**Comment by wenwu449** [comment]
Microsoft.Network manifest needs a fix to allow expression for dnsServers

**Comment by wenwu449** [comment]
Fix released.
