### ISSUE TITLE
Missing/Incorrect values in deploymentTemplate.json

### ISSUE THREAD

**Issue by QuasarSE** [Azure/azure-resource-manager-schemas#194]
The 2015-01-01 (at least) version of deploymentTemplate.json has the following issues which result in valid templates being tagged as invalid.

1. **resourceLocations** is incomplete.  e.g., the Canadian locations are missing 
2. **Output parameter types** are defined to include secureString, but not secureObject.
3. The expression/pattern value which specifies permitted template function names which can be specified in an expression string (e.g. "[...]") is **missing the functions: deployment, skip and take**, as well as permitting the open-ended range of list* functions which are described in the docs (https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/)

**Comment by wenwu449** [comment]
All are valid issues, we will put fixes. Thanks for reporting them.

**Comment by QuasarSE** [comment]
Also now needs the newly-GA'd: ‘West US 2’ and ‘West Central US’ regions.

**Comment by wenwu449** [comment]
Fix released.
