### ISSUE TITLE
Onboard Microsoft.DocumentDB for automatic schema generation

### ISSUE THREAD

**Issue by frrossms** [Azure/azure-resource-manager-schemas#2061]
The resource provider Microsoft.DocumentDB is currently opted out of schema autogeneration. We would like to opt back in. Please let me know (internal username frross) what I need to do to make that happen.

**Comment by anthony-c-martin** [comment]
@frrossms - Microsoft.DocumentDB is actually currently opted in - see https://github.com/Azure/azure-resource-manager-schemas/blob/480dffb7abe4bb6d46fdfeb62c7c5bfad71e6146/onboarded-report/result.json#L274-L279

Are you seeing issues with the automatic generation?

**Comment by frrossms** [comment]
I guess the dashboard was running behind or something. It looks like it's functioning now. Thanks!
