### ISSUE TITLE
Schema autogeneration pipeline failed due to summary.log not found

### ISSUE THREAD

**Issue by leni-msft** [Azure/azure-resource-manager-schemas#2084]
cmderr	[generateScript.sh] Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/azure-resource-manager-schemas_tmp/schm_azspc/summary.log'

https://github.com/Azure/azure-rest-api-specs/pull/16953/checks?check_run_id=4404634703

**Comment by leni-msft** [comment]
@jorgecotillo or @anthony-c-martin would you be able to take a look? It seems a regression issue.

**Comment by jorgecotillo** [comment]
Hey Lei, I am not able to repro, I just run:

npm run generate-all -- --local-path "C:\azupdate\azure-rest-api-specs" --output-path "C:\tmp\output.json" --readme-files "C:\azupdate\azure-rest-api-specs\specification\recoveryservicesbackup\resource-manager\readme.md"

Locally and it worked for me, I'll try with linux to see if I find a different behavior.

**Comment by jorgecotillo** [comment]
Forgot to mention that I ran it from main branch.

**Comment by leni-msft** [comment]
Hi Jorge, I could repro in github codespace - a clean environment:
```
npm run generate-all -- --local-path ../azure-rest-api-specs --readme-files specification/recoveryservicesbackup/resource-manager/readme.md
```
please try cleaning your temp folder, specifically `path.join(os.tmpdir(), 'schm_azspc')`

**Comment by jorgecotillo** [comment]
Yeah, you were right, cleaning or using a different temp folder repro the issue, I just created a PR: #2087 that fixes the issue.

Thanks for bringing this to our attention.
