### ISSUE TITLE
Missing Schema: Microsoft.Web/sites/slots

### ISSUE THREAD

**Issue by DustinVenegas** [Azure/azure-resource-manager-schemas#215]
There is no stand-alone template for Microsoft.Web/sites/slots entries. There is also no schema data for adding this to a Microsoft.Web/sites resources[] entry.

**Comment by sergsalo** [comment]
any plans to add this?

**Comment by DustinVenegas** [comment]
I do not currently @sergsalo and I'm unsure how these are triaged.

**Comment by stephlocke** [comment]
I presume this would include webjobs & functions as well?

**Comment by ifeoluwaokunoren** [comment]
This has since been added to the template schema.
