### ISSUE TITLE
CosmosDB Container conflict on partitionkey with version when deploying - can not run ARM deployment with same values

### ISSUE THREAD

**Issue by santo2** [Azure/azure-resource-manager-schemas#2172]
Given I have a container that was created by code,
And I have exported the template, and converted it to bicep
And In the ARM template I see there is a version in the partitionkey property
When I try to deploy this container via "az deployment group create (mode incremental)"
Then the deployment results in status "conflict" on the container resource

Note: I see this only happens for the containers which have a version. 
I tried both providing or NOT providing the version but the conflict remains.
All other containers are deployed without any issues

error:
```
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Message: {"code":"BadRequest","message":"Message: {
			"Errors":["Document collection partition key cannot be changed."]}\\r\\nActivityId: 49070528-bfaf-49e4-9ed6-ef453cfb1e9b,......."

```

exported template of the container:
```
"resource": {
        "id": "PhysicalZone",
        "indexingPolicy": "....."
        "partitionKey": {
            "paths": [
                "/_partitionKey"
            ],
            "kind": "Hash",
            "version": 2
        },
        "conflictResolutionPolicy": "...."
    }
}
```

template bicep (I simplified it to make this thread a little shorter)
```
param deployServerlessCosmosDb bool

module cosmosdb './modules/CosmosDb.bicep' = if(!deployServerlessCosmosDb) {
  name: 'cosmosdb'
  params: {
    
  }
}
```

cosmosdb.bicep:
```
var cosmosDbServerName = 'accenv'

resource cosmosDbServer 'Microsoft.DocumentDB/databaseAccounts@2021-07-01-preview' = {
  kind: 'GlobalDocumentDB'
  name: cosmosDbServerName
  location: resourceGroup().location
  properties: {
    createMode: 'Default'
    locations: [
      {
        locationName: resourceGroup().location
        failoverPriority: 0
      }
    ]
    enableAnalyticalStorage: true
    analyticalStorageConfiguration: {
      schemaType: 'WellDefined'
    }
    databaseAccountOfferType: 'Standard'
    consistencyPolicy: {
      defaultConsistencyLevel: 'Session'
      maxIntervalInSeconds: 5
      maxStalenessPrefix: 100
    }
    diagnosticLogSettings: {
      enableFullTextQuery: 'None'
    }
  }
}

resource pdb 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2021-07-01-preview' = {
  parent: cosmosDbServer
  name: 'pdb'
  properties: {
    resource: {
      id: 'pdb'
    }
  }
}

module container_pz 'CosmosDbContainers/cosmosDbContainer.pz.bicep' = {
  name: 'pz'
  params: {
    databaseName: pdb.name
    serverName: cosmosDbServerName
    isServerless: false
  }
}

```

container bicep:
```
param serverName string
param databaseName string
param isServerless bool

resource cosmosDbServer 'Microsoft.DocumentDB/databaseAccounts@2021-10-15' existing = {
  name: serverName
}

resource database 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2021-07-01-preview'  existing = {
  parent: cosmosDbServer
  name: databaseName
}

resource container_PhysicalZone 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2021-07-01-preview' = {
  parent: database
  name: 'PhysicalZone'
  properties: {
    resource: {
      id: 'PhysicalZone'
      defaultTtl: -1
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          {
            path: '/*'
            indexes: [
              {
                kind: 'Spatial'
                dataType: 'Point'
              }
              {
                kind: 'Range'
                dataType: 'String'
                precision: -1
              }
              {
                kind: 'Range'
                dataType: 'Number'
                precision: -1
              }
            ]
          }
        ]
        excludedPaths: [
          {
            path: '/"_etag"/?'
          }
        ]
      }
      partitionKey: {
        paths: [
          '/_partitionKey'
        ]
        kind: 'Hash'
        version: 2
      }
      conflictResolutionPolicy: {
        mode: 'LastWriterWins'
        conflictResolutionPath: '/_ts'
      }
    }
  }
}

resource containerThrougputSettings_PhysicalZone 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings@2021-07-01-preview' = if (!isServerless) {
  parent: container_PhysicalZone
  name: 'default'
  properties: {
    resource: {
      throughput: 400
      autoscaleSettings: {
        maxThroughput: 4000
      }
    }
  }
}

```

parameters: 
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "environment": { "value": "Acceptance" },
      "deployServerlessCosmosDb":{ "value": false }
    }
  }
```

sidenote: 
Also I see that when I run a what-if deployment on this structure, the what-if is ignoring that I have the cosmosDB and container, and provides no feedback (* to indicate that this resource is not in the template)

**Comment by santo2** [comment]
is this the correct place to post? I don't see a a very fast response time on the last mentioned issues

**Comment by stephaniezyen** [comment]
Not a schemas issue, looks like it's being tracked in the bicep issue mentioned above.

**Comment by santo2** [comment]
@stephaniezyen it is a schema issue and has been discussed with the PG team via a support request in the azure portal. RamaRag mentioned this is a known issue but it does not have a high priority and he would be updating us on this ticket, so could you please re-open this until it's fixed?

the latest version of the schema gives the issues mentioned above. We went back to schema version 2020-04-01 and removed the partitionkey.

extra note for people who have this issue: this is because it was exported as an ARM template after creation, which adds the partitionkey to the template, although it's a fixed partitionkey and didn't need to be in the template. The key is to remove it from the ARM template and keep schema version 2020-04-01

**Comment by jorgecotillo** [comment]
@santo2 when you say PG - do you mean CosmosDB team right? just to be fully sure.
If there's a ticket on their side, we'll reach out to them to get a tentative ETAs, since is not on our control we cannot guarantee a specific fix date. 

The way that Schemas are generated is a complex process but in this specific case what the generation does is, it looks at all properties from the PUT body (one of them is partitionKey) and exposes them, then Export template looks at these properties and simply exports them - this is because a property(ies) that can be PUT are meant for an end user to modify or leave them as-is (a.k.a. no-op).

This situation here is a little complex, because it seems like a green field deployment works as expected (first time you PUT a partitionKey it works), but subsequent deployments fail because partitionKey is not meant to be updated, so the fix is not a simple remove partitionKey from the Schema but rather treat partitionKey (on the backed) as a no-op in an update - which technically goes against ARM API patterns but there are exceptions and this might be one of them.
