### ISSUE TITLE
missing ARM schema for Microsoft.StreamAnalytics / streamingjobs ?

### ISSUE THREAD

**Issue by tinkerbotfoo** [Azure/azure-resource-manager-schemas#219]
Would be great to be able to provision streamanalytics/ streamjobs via ARM.

**Comment by ifeoluwaokunoren** [comment]
Schema present here: https://github.com/Azure/azure-resource-manager-schemas/blob/001c0a7ee838bc53008204886561ee1ffe554f78/schemas/2019-04-01/deploymentTemplate.json#L685
