### ISSUE TITLE
ARM Provisioning multiple Nics and getting a reference to them in the output

### ISSUE THREAD

**Issue by KMeuleman** [Azure/azure-resource-manager-schemas#224]
Hi all,

I am provisioning an AvailabilitySet and a NetworkSecccurityGroup using s standard syntax (e.g.)

 "resources": [
    {
      "type": "Microsoft.Compute/availabilitySets",
      "name": "[parameters('availabilitySetName')]",
      "apiVersion": "[variables('apiVersion')]",
      "location": "[variables('location')]",
      "tags": {
        "displayName": "AvailabilitySet",
      },
      "properties": {
        "platformUpdateDomainCount": 20,
        "platformFaultDomainCount": 3
      },
      "dependsOn": [ ]
    },
     {
      "type": "Microsoft.Network/networkSecurityGroups",
      "name": "[parameters('networkSecurityGroupName')]",
      "apiVersion": "[variables('apiVersion')]",
      "tags": {
        "displayName": "NetworkSecurityGroup",
      },
      "location": "[variables('location')]",
      "comments": "SecurityRules need to be refined manually !",
      "properties": {
        "securityRules": [ ]
      },
      "dependsOn": [ ]
    },

and I am outputting  a reference to them for the PowerShell script that starts the provisioning has a handle to the object for further manipulation, if needed:

  "outputs": {
    "availabilitySet": {
      "value": "[reference(parameters('availabilitySetName'))]",
      "type": "object"
    },
    "networkSecurityGroup": {
      "value": "[reference(parameters('networkSecurityGroupName'))]",
      "type": "object"
    },
  }

In the same json, I am providing a number of Network Interfaces and corresponding VMs using a well known "copy" syntax:
    {
      "apiVersion": "[variables('apiVersion')]",
      "type": "Microsoft.Network/networkInterfaces",
      "name": "[concat(parameters('serverNamePrefix'), padLeft(copyIndex(parameters('offset')),3,'0'), variables('nicName'))]",
      "location": "[variables('location')]",
      "tags": {
        "displayName": "NetworkInterface",
      },
      "properties": {
        "ipConfigurations": [
          {
            "name": "ipconfig1",
            "properties": {
              "privateIPAllocationMethod": "Dynamic",
              "subnet": {
                "id": "[variables('subnetRef')]"
              }
            }
          }
        ],
        "dnsSettings": {
          "dnsServers": "[parameters('dnsServers')]"
        },
        "networkSecurityGroup": {
          "id": "[resourceId('Microsoft.Network/networkSecurityGroups',parameters('networkSecurityGroupName'))]"
        }
      },
      "dependsOn": [
        "[resourceId('Microsoft.Network/networkSecurityGroups', parameters('networkSecurityGroupName'))]"
      ],
      "copy": {
        "name": "nicCopy",
        "count": "[parameters('vmCount')]"
      }
    },

and 

```
  "copy": {
    "name": "vmCopy",
    "count": "[parameters('vmCount')]"
  },
```

Is there a working syntax that allows me to output references to the provisioned Nics and VMs as well ?

Kind regards and have a nice day and night.

**Comment by ifeoluwaokunoren** [comment]
Hi,
You can use the reference function: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#reference
