### ISSUE TITLE
Link to latest schema broken

### ISSUE THREAD

**Issue by reutsharabani** [Azure/azure-resource-manager-schemas#225]
This [link ](http://schema.management.azure.com/schemas the) shows up in the repository's description as the link you will "publish the latest schemas to":

![broken link azure resource manager template](https://cloud.githubusercontent.com/assets/1097197/18304841/380e0902-74d4-11e6-932b-6d8e9f44f7b2.PNG)

This link is broken, this is what the endpoint returns:

![broken link azure resource manager template content](https://cloud.githubusercontent.com/assets/1097197/18304870/6224e1d4-74d4-11e6-9cb3-33076aba2818.PNG)

Can this be fixed? Currently most examples you have that use these schemas are outdated (01-01-2015 are the latest I've found).

**Comment by switj** [comment]
Any update on this?

**Comment by ifeoluwaokunoren** [comment]
Hello,
We're tracking reliability improvements internally, and we use Github issues to track issues found in this repo.
