### ISSUE TITLE
Schema Microsoft.Insights/webtests doesn't validate Locations

### ISSUE THREAD

**Issue by DustinVenegas** [Azure/azure-resource-manager-schemas#227]
The `Microsoft.Insights/webtests` component does not validate the `properties.Locations` array. Deploying a deployment with invalid locations succeeds but does not output an error even though no locations are added.

**Comment by ifeoluwaokunoren** [comment]
Validation was added in 2017, so this has been resolved.

Sample response: {"code":"BadRequest","message":"Value cannot be null.\r\nParameter name: 'properties.Locations[1].Id' - 'us-ca-sjc-azp' is not a supported location","innererror":{"diagnosticcontext":"2075aa52-f6ae-46a4-8915-dac2448e9b23","time":"2019-08-15T23:49:16.9704813Z"}}

**Comment by mpmatti** [comment]
Is this issue already fixed? I cannot find anywhere the list of acceptable location names. The documentation is poor.
