### ISSUE TITLE
Missing Schema: Microsoft.Web/sites/siteextensions

### ISSUE THREAD

**Issue by DustinVenegas** [Azure/azure-resource-manager-schemas#236]
The Schema for Microsoft.Web/sites/siteextensions is missing. There is no record of it in the microsoft.web schema. This is a valid schema used to deploy Application Insights and other site extensions.

**Comment by ifeoluwaokunoren** [comment]
Fix here: https://github.com/Azure/azure-resource-manager-schemas/pull/761
