### ISSUE TITLE
Microsoft.Web schema missing support for deployment slots

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-resource-manager-schemas#244]
I'm looking into how to define deployment slots for app services, but finding conflicting info (what little there is) on the interwebz. Would be great if this was be baked into the schema _and_ documented as well.

**Comment by naveedaz** [comment]
It is part of the 2016-08-01 api schema for app services. You should be able to use something like the following snippet.
{
  "type": "Microsoft.Web/sites/slots",
  "apiVersion": "2016-08-01",
  "name": "[concat(parameters('SiteName'), '/', parameters('SlotName')]",
  "location": "[resourceGroup().location]"
  "dependsOn": [
  "[resourceId('Microsoft.Network/sites', parameters('SiteName'))]"
  ]
}
