### ISSUE TITLE
Microsoft.Sql schema 2014-04-01-preview missing Collation

### ISSUE THREAD

**Issue by OzBob** [Azure/azure-resource-manager-schemas#257]
https://github.com/Azure/azure-resource-manager-schemas/blob/15534a69026cd9357b3db825a6cdb51457406233/schemas/2014-04-01-preview/Microsoft.Sql.json

does not contain actual Collations supported in Azure.

SQL_Latin1_General_CP1_CI_AS

Is not listed but is valid during ARM deployment.

yet, when corrected to be valid (according to the schema results in ARM in VS) the deployment fails, with the error: "'SQL_Latin1_General_Cp1_CI_AS_KI_WI' is not a supported collation."

**Comment by OzBob** [comment]
The big question is how do the team that 'owns' SQL Server on Azure who set the concrete supported Collations know to update these schema files?

**Comment by ifeoluwaokunoren** [comment]
We're deprecating the 2014-04-01-preview schema. Customers are encouraged to use  **2014-04-01** api-version or later preview version instead.
