### ISSUE TITLE
Onboard autogen for resource type connector in ServiceLinker

### ISSUE THREAD

**Issue by qianwens** [Azure/azure-resource-manager-schemas#2672]
Service connector team added a new tracked resource type "connectors" in RP servicelinker, it is not in the auto-gen list now, please help onboard this new resource type
https://github.com/Azure/azure-resource-manager-schemas/blob/main/generator/autogenlist.ts#L778
 {
        basePath: 'servicelinker/resource-manager',
        namespace: 'Microsoft.ServiceLinker',
        resourceConfig: [
            {
                type: 'linkers',
                scopes: ScopeType.Extension,
            },
        ],
    },

connector resource uri: "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.ServiceLinker/locations/{location}/connectors/{connectorName}"

connector swagger path:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/servicelinker/resource-manager/Microsoft.ServiceLinker/preview/2022-11-01-preview/servicelinker.json#L354

**Comment by qianwens** [comment]
Hi team, this issue has pending Triage for 5 days, could you please help take a look ASAP?

**Comment by anthony-c-martin** [comment]
I've kicked off https://github.com/Azure/azure-resource-manager-schemas/actions/runs/3631690270 which should re-generate your schemas.

**Comment by anthony-c-martin** [comment]
@qianwens please take a look over #2698 and confirm whether the config looks correct.

**Comment by qianwens** [comment]
> I've kicked off https://github.com/Azure/azure-resource-manager-schemas/actions/runs/3631690270 which should re-generate your schemas.

Thanks @anthony-c-martin , it seems this run you kicked off is failed, could you please help take a look?
