### ISSUE TITLE
ARM Template Function: Guid.NewGuid() function needed

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-resource-manager-schemas#268]
ARM RBAC role assignment names must be unique GUIDs. This basically makes it impossible to have a generic template that can create arbitrary new RBAC roles.

1. Why does ARM RBAC role assignment need to be a user-specified unique GUID? That is very atypical.

2. In lieu of fixing the RBAC API, can we get an ARM template function that will generate a new random GUID?

So far, I've been making the RBAC role assignment name a parameter and wrapping the template with a script that injects output `uuidgen` into the parameters file... but this is far from ideal.

cc: @yangl900

**Comment by davidjrh** [comment]
While we wait for a solution, I have implemented this workaround that is working for me: https://github.com/davidjrh/azurerm-newguid

**Comment by colemickens** [comment]
Nifty! cc: @rjmax

**Comment by lzandman** [comment]
Yes, we need this!

**Comment by antmarti-microsoft** [comment]
This has since been implemented. See https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-string#guid for more information!

**Comment by colemickens** [comment]
We're actually coming up on the 2 year anniversary of it being deployed - I had gone in and implemented it myself. (though, it also should have never been necessary and isn't anymore either :laughing:)
