### ISSUE TITLE
Questions about Template Export algorithm

### ISSUE THREAD

**Issue by LianwMS** [Azure/azure-resource-manager-schemas#2680]
Hi All,

We are service connector team. Service Connector have a resource linker which is not a tracked resource. It's an extension resource, which may support App Service, Spring APP and Container APP now. We want to add the support about "Template Export" in portal. That means, is an App Service Instance contains the "linker" resource, the arm template exported can contain the "linker" resource. 

I am watching the following doc about export template.
https://armwiki.azurewebsites.net/rp_onboarding/process/template_schemas.html#template-export-algorithm

Since linker is not a tracked resource. We should follow: "Find all the known proxy children types for that tracked resource (using the schemas dictionary), and perform collection gets against the RP for each (again using the API version from the schemas dictionary)." 

We want to understand, how to "find“ in your algorithm here. How "linker" can be found here?

**Comment by anthony-c-martin** [comment]
Extension resources are not supported by Export - "child" resources refers purely to ARM's notion of "child" - e.g. `Microsoft.Network/virtualNetworks/subnets` is a child resource of `Microsoft.Network/virtualNetworks`.

Happy to discuss further via email if you like - my alias is antmarti.

**Comment by anthony-c-martin** [comment]
Closing this issue as it's not strictly related to schemas.
