### ISSUE TITLE
Microsoft.Advisor opt-in for autogeneration

### ISSUE THREAD

**Issue by patrinid** [Azure/azure-resource-manager-schemas#2722]
Following the instructions noted in 
https://github.com/Azure/azure-resource-manager-schemas/tree/main/generator#onboarding-to-the-autogeneration-pipeline

We would like to onboard Microsoft.Advisor resource provider for schema autogeneration. We have the swagger spec of our RP checked into: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/advisor/resource-manager

**Comment by jportugal0** [comment]
Folks, can we have someone take a look at this PR? Thanks.
