### ISSUE TITLE
schema for Microsoft.Network/applicationGateways 2015-06-15 missing

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/azure-resource-manager-schemas#273]
Referenced in lot of examples in GitHub template but the schema is missing and therefore auto-complete failing on Visual Studio Code
Also found when deploying from the portal a newer version is used:
"type": "Microsoft.Network/applicationGateways",
            "name": "[parameters('applicationGatewayName')]",
            "apiVersion": "2016-08-01",

**Comment by hiraldesai** [comment]
Not only the autocomplete fails but I'm not able to find examples of how to add custom probe through template. Can someone please provide the schema?

**Comment by hiraldesai** [comment]
Actually, never mind - I found it [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/applicationgateways)

Although, it would be nice to have it published here so that Azure portal doesn't complain about it when you're trying to import Automation Script from the portal.

**Comment by Tadimsky** [comment]
Ping. Can we get the schema for Application Gateways setup and deployed?

**Comment by Tadimsky** [comment]
@Tiano2017 @DeepakRajendranMsft is this something you can do? It'd be really nice if we could work with Application Gateways in VS Code. Looks like #361 had a request for this to be added.

**Comment by Tiano2017** [comment]
@DeepakRajendranMsft  would you help on this?

**Comment by Tadimsky** [comment]
Ping. @DeepakRajendranMsft

**Comment by MikhailTryakhov** [comment]
@number213 @EvgenyAgafonchikov  please review

**Comment by number213** [comment]
Fixed by https://github.com/Azure/azure-resource-manager-schemas/pull/674
