### ISSUE TITLE
Comments field

### ISSUE THREAD

**Issue by ljt91** [Azure/azure-resource-manager-schemas#277]
Would it be possible to allow "comment" field's in the JSON?

When I'm viewing the automation scripts in the portal it seems that the field is allowed in the templates however when trying to deploy with "comment" in my code I receive a validation errors.

Error: Code=InvalidRequestContent; Message=The request content was invalid and could not be deserialized: 'Could not find member 'comment' on object of type 'TemplateResource'. Path 'properties.template.resources[0].comment', line 354, position 21.'.

Thanks,
Lyon Till

**Comment by 4c74356b41** [comment]
you could use a "description" field for that, the only draw back it would be visible as a tooltip to the deploying user

**Comment by ljt91** [comment]
This is being added across the Resource Providers and I can now add "comments" in my templates.
