### ISSUE TITLE
ARM template function: merge(object1, object2)

### ISSUE THREAD

**Issue by russcam** [Azure/azure-resource-manager-schemas#279]
I propose the addition of a template function that is able to merge two objects returning a new object that is the product of the merge, similar in nature to the way [jQuery.extend()](https://api.jquery.com/jquery.extend/) with function works, with deep copying.

Some examples:

```javascript
merge({one:'hello'}, {two: 'world'}) // -> {"one": "hello", "two": "world"} 
```
```javascript
merge({one:'hello'}, {one: 'world'}) // -> {"one": "world"} 
```

Often, parameters to a template will be collected and a variable object composed of those parameters, where each parameter key/value forms a property name and value in the composed object. For a complex ARM template that takes advantage of branching linked templates, the composed variable object may be a parameter to the linked template and, within the linked template. it can be useful to build a variable object composed of the properties of the passed object parameter and some new properties. To do this currently requires referencing each parameter object property separately, copying it over to a property on the variable object, and adding any additional properties as needed. This would be much simpler and less error-prone with a `merge(object1, object2)` function.

A real example for this is an ARM template that can deploy to Linux or Windows VMs. There could be common configuration options such as number of disks to attach to each VM, but then different configuration options such as configuring Azure Disk Encryption on the different OSes (i.e. different extension name, `type` and `typeHandler`). A well constructed template would keep the differing configuration options within the linked template to which they apply, and the common configuration options in an outer template that calls the linked template, passing in the common configuration options as a parameter. Within the linked template then, there may be additional linked templates to which both common and different configuration options should be passed as a parameter, so being able to merge configuration options into one object easily would help.

**Comment by 4c74356b41** [comment]
i think there is a `union()` function @russcam

**Comment by russcam** [comment]
Thanks @4c74356b41, [union](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-array#union) looks promising. Fairly sure this didn't exist when the issue was opened! Do you know if it does deep copying?

**Comment by 4c74356b41** [comment]
sorry, didnt test that, but you can take default example and test it. should be 1 minute exercise.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-array#union

**Comment by antmarti-microsoft** [comment]
As confirmed by @4c74356b41, `union()` supports this behavior, and does support deep cloning.
