### ISSUE TITLE
New resources missing from schema

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/azure-resource-manager-schemas#280]
The schema of resource type 'Microsoft.Compute/disks' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)
The schema of resource type 'Microsoft.DevTestLab/schedules' is not available. Resources of this type will not be exported to the template. (Code: ResourceTypeSchemaNotFound)

So i assume it is not possible to create those with arm templates yet?

**Comment by rjmax** [comment]
Managed disks can be created via templates; the schemas should be online in the near future.  I'll forward to the team so that they can provide a more precise ETA.

**Comment by 4c74356b41** [comment]
yeah, I figured I can create those without specifying any storage, right? so if i do that it will create managed disk(s), right?

**Comment by mscloudops** [comment]
@rjmax Hi ! And for 'Microsoft.DevTestLab/schedules' ? Is there any workaround to automate Auto-shutdown VM settings with ARM template ?

**Comment by 4c74356b41** [comment]
@mscloudops I don't know such a way, but you can do this with [powershell](http://4c74356b41.com/?p=5698), but you could replicate that with the rest api.

**Comment by mscloudops** [comment]
@4c74356b41 Thanks for your answer ! Your PS solution meets my need 👍

**Comment by 4c74356b41** [comment]
this particular issue is long solved.
