### ISSUE TITLE
Documentation references datafactories in ARM templates, but they appear to be removed

### ISSUE THREAD

**Issue by AlexKeySmith** [Azure/azure-resource-manager-schemas#285]
It looks like data factory was removed from arm templates: #235 but it looks like in the docs it's still mentioned: https://docs.microsoft.com/en-us/azure/data-factory/data-factory-build-your-first-pipeline-using-arm#data-factory-entities-in-the-template 

Have I misunderstood something or is the documentation inaccurate now?

**Comment by ravbhatnagar** [comment]
@bgold09 who was looking into this.

**Comment by bgold09** [comment]
That article is about how to author an ARM template deployment that includes data factories, which works without having these schemas. The part that does not work and is not supported is exporting data factories to an ARM template, which requires the schemas to be in this repo.

**Comment by AlexKeySmith** [comment]
Thanks @bgold09 when you say export, do you mean from the Azure Portal? Does the azure portal use this repo when knowing how to perform exports?

Does not having them in this repo also affect intellisense when authoring in Visual Studio, I'm unsure?

**Comment by AlexKeySmith** [comment]
Hi, I patched together the ARM schema's using commits pre to the removal and hosted them locally to give me validation and intellisense.

I'm finding this indispensable, as the feedback loop when deploying ARM templates to Azure is very long, to find out I've made a minor mistake.

This is exaggerated as the templates can be very large for datafactories, I'm finding only trivial data factories lead to small ARM templates.

Is the portal somehow reliant on these schema's being present in this repo to expose the export feature?

If not, would it be possible to re-include the schemas as I think they will be a massive aid to day to day development.

Thanks for your help.

**Comment by bgold09** [comment]
If the schemas are in this repo then they eventually are used (in a different form, not directly from this repo) by the export template API. As such, adding them here would not be the right thing to do even for authoring, since it would result in a broken export experience for V1 data factories. 

That said, this will eventually be supported in [ADF V2](https://docs.microsoft.com/en-us/azure/data-factory/); this is a distinct service from the original V1 service you're using and is currently in public preview. I'd recommend taking a look at that and see if it will meet your needs.

If you have more questions, @hvermis should be able to help

**Comment by hvermis** [comment]
CC: @deata

**Comment by ckittel** [comment]
So, for building arm templates for V2, should we simply infer them from https://github.com/Azure/azure-quickstart-templates/tree/master/101-data-factory-v2-blob-to-blob-copy @hvermis ?  I agree with @AlexKeySmith in that having schema support when authoring these goes a long ways.

**Comment by hvermis** [comment]
@ckittel We are currently working on adding schemas for ADF V2 to this repo and then adding the support for the export fromthe portal. At this point you can infer them from the link you mentioned and use them.

**Comment by AlexKeySmith** [comment]
V2 looks great, but because it's in preview we can't use it yet I'm afraid for our production work, although we're beginning to experiment with it.

I noticed the author / deploy has autocomplete, is that powered by json schema in the background?

Just looking for a source of an up to date schema we could repurpose for authoring in visual studio, perhaps we could create a spin of repo / hosting until V2 is released?

**Comment by AlexKeySmith** [comment]
Sweet I can see they're work in progress, looking forward to it :-)

https://github.com/Azure/azure-resource-manager-schemas/pull/390

**Comment by Kampfgnom** [comment]
Can someone give an update on this issue?

Nowadays the vscode support for the schemas is so good that having a working schema really adds value.

Thank you :)

**Comment by raojk** [comment]
Hi could please let me know is it possible to generate data factory ARM template using Azure power shell . When i was tried with Az power shell to generate ARM template for required data factory I am getting below eerors.

WARNING: ExportTemplateCompletedWithErrors : Export template operation completed with errors. Some resources were not exported. Please see details for more information.
WARNING: ResourceTypeSchemaNotFound : The schema of resource type 'Microsoft.Databricks/workspaces' is not available. Resources of this type will not be exported to the template.
WARNING: ResourceTypeSchemaNotFound : The schema of resource type '**Microsoft.DataFactory/factories**' is not available. Resources of this type will not be exported to the template.
WARNING: ResourceTypeSchemaNotFound : The schema of resource type 'Microsoft.Portal/dashboards' is not available. Resources of this type will not be exported to the template.

**Comment by ifeoluwaokunoren** [comment]
This [PR](https://github.com/Azure/azure-resource-manager-schemas/pull/776) fixes the issue for missing schemas for DataFactory - which means intellisense now works in either VSCode or Visual Studio.
As for trying to export DataFactory resources using template export: ARM currently doesn't support this - as a work-around please go to https://adf.azure.com/ to export microsoft.datafactory resources. You can also find more details [here](https://docs.microsoft.com/en-us/azure/data-factory/copy-clone-data-factory)
