### ISSUE TITLE
2015-05-01-preview resources availability

### ISSUE THREAD

**Issue by codespare** [Azure/azure-resource-manager-schemas#3]
Hello, could you post the resource types introduced in the 2015-05-01 version?
Thanks!

**Comment by yangl900** [comment]
hello, which resource provider are you referring to?

**Comment by codespare** [comment]
Microsoft.Compute, .Network and .Storage. They are referenced in the quickstart templates at https://github.com/Azure/azure-quickstart-templates for instance.

**Comment by yangl900** [comment]
The team are working on it, will publish very soon.

**Comment by codespare** [comment]
Do you think it would be possible to post those even if they are still undergoing edits? That would be useful even in flux. Using a distinct 'dev' branch or similar so that people don't start opening issues for those maybe?

**Comment by virklba** [comment]
Microsoft.Compute, .Network and .Storage services went GA today.  Expecting to see the corresponding schema's here...

PS "very soon" > 25 days???

**Comment by codespare** [comment]
I concur, a recent tally suggests there are 569 (resource types x versions) across Azure services, 199 current. Any logistic support dealing with that, either here or on a directory browsable http endpoint would help, very directly facilitating Azure development in the field.

**Comment by trondhindenes** [comment]
Any updates on the Iaas schema? This is almost ridiculous.

**Comment by yangl900** [comment]
The Microsoft.Compute, Microsoft.Network and Microsoft.Storage schema has been merged and published today. Sorry for the delay and thank you for your patient.
