### ISSUE TITLE
The latest API version for Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies is missing

### ISSUE THREAD

**Issue by martooo1936** [Azure/azure-resource-manager-schemas#3081]
I cannot using Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies's latest API version in my ARM template as it complains that the version is not recognized as a valid one. The version I want to target is: 2023-11-01. The latest available according to the ARM extension is: 2023-04-01

**Comment by anthony-c-martin** [comment]
Please could you raise this against https://github.com/Microsoft/vscode-azurearmtools? I don't have the permissions to transfer to this repo.
