### ISSUE TITLE
Microsoft.Sql is missing several child resources

### ISSUE THREAD

**Issue by toddbrownmcis** [Azure/azure-resource-manager-schemas#309]
[Microsoft.Sql/servers/auditingPolicies](https://msdn.microsoft.com/en-us/library/azure/mt604383.aspx)
[Microsoft.Sql/servers/auditingSettings](https://msdn.microsoft.com/en-us/library/azure/mt771861.aspx)
Microsoft.Sql/servers/communicationLinks
[Microsoft.Sql/servers/connectionPolicies](https://msdn.microsoft.com/en-us/library/azure/mt604439.aspx)
[Microsoft.Sql/servers/elasticPools](https://msdn.microsoft.com/en-us/library/azure/mt163596.aspx)
[Microsoft.Sql/servers/securityAlertPolicies](https://msdn.microsoft.com/en-us/library/azure/mt652113.aspx)

[Microsoft.Sql/servers/databases/auditingPolicies](https://msdn.microsoft.com/en-us/library/azure/mt604471.aspx)
[Microsoft.Sql/servers/databases/auditingSettings](https://msdn.microsoft.com/en-us/library/azure/mt695939.aspx)
[Microsoft.Sql/servers/databases/dataMaskingPolicies](https://msdn.microsoft.com/en-us/library/azure/dn912660.aspx)
[Microsoft.Sql/servers/databases/securityAlertPolicies](https://msdn.microsoft.com/en-us/library/azure/mt674917.aspx)

... and probably several others that aren't documented at [Azure SQL Database REST API Reference](https://msdn.microsoft.com/en-us/library/azure/mt163571.aspx) but are in [Azure/azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/tree/master/src/ResourceManagement/Sql/SqlManagement/Generated)

**Comment by ravbhatnagar** [comment]
@jaredmoo who is working on including the missing types from this schema.

**Comment by jaredmoo** [comment]
- [ ] Microsoft.Sql/servers/auditingPolicies
- [ ] Microsoft.Sql/servers/auditingSettings
- [ ] Microsoft.Sql/servers/communicationLinks
- [ ] Microsoft.Sql/servers/connectionPolicies
- [ ] Microsoft.Sql/servers/elasticPools
- [ ] Microsoft.Sql/servers/securityAlertPolicies
- [ ] Microsoft.Sql/servers/databases/auditingPolicies
- [ ] Microsoft.Sql/servers/databases/auditingSettings
- [ ] Microsoft.Sql/servers/databases/dataMaskingPolicies
- [ ] Microsoft.Sql/servers/databases/securityAlertPolicies

**Comment by jaredmoo** [comment]
PRs:
1. #323
2. #326

**Comment by ifeoluwaokunoren** [comment]
Closing issue - since resourceTypes all have schemas published.
