### ISSUE TITLE
Missing Schema for Microsoft.StreamAnalytics/StreamingJobs

### ISSUE THREAD

**Issue by MCKLMT** [Azure/azure-resource-manager-schemas#311]
Hi,

When you author a template for Azure Stream Analytics the schema is missing. In result, the autocomplete is not working in VSCode or Visual Studio. :(
Try to open this template in VSCode: https://github.com/Azure/azure-quickstart-templates/blob/master/101-streamanalytics-create/azuredeploy.parameters.json

Thanks in advance,
Mickaël

**Comment by ifeoluwaokunoren** [comment]
Schema exists here: https://github.com/Azure/azure-resource-manager-schemas/blob/001c0a7ee838bc53008204886561ee1ffe554f78/schemas/2019-04-01/deploymentTemplate.json#L685
