### ISSUE TITLE
Some of the array functions missing

### ISSUE THREAD

**Issue by antmeehan** [Azure/azure-resource-manager-schemas#315]
Hi,

It seems that some of the array functions (as defined https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-array) are missing from the schema. Eg,

* union
* intersection

Are there plans to add them?

Thanks.

**Comment by ifeoluwaokunoren** [comment]
Thanks! These have since been added - closing out the issue.
