### ISSUE TITLE
Dependency on location for SqlDatabases

### ISSUE THREAD

**Issue by BerendWouters** [Azure/azure-resource-manager-schemas#324]
I am trying to create a new sql database on an existing Sql Server using ARM templating.
This server is in a RG with multiple other servers, and in a different location. I can define a dependsOn for that sql server, but it'd still have to define the sql database's location. Why is that the case?
Is there a workaround to find the location of the provided Sql server (and not use the resourceGroup().location option defined in many examples)? I cannot use reference since that'd throw an exception.
Snippet:
```
"resources": [
    {
      "type": "Microsoft.Sql/servers/databases",
      "kind": "v12.0,user",
      "name": "[concat(parameters('server_name'),'/',parameters('db_name'))]",
      "apiVersion": "2014-04-01-preview",
      "location": "[parameters('location')]", // What should I use here?
      "dependsOn": [
        "[concat('Microsoft.Sql/servers/', parameters('server_name'))]"
      ],
      "properties": {
        "edition": "Standard",
        "status": "Online",
        "collation": "SQL_Latin1_General_CP1_CI_AS",
        "maxSizeBytes": "268435456000",
        "elasticPoolName": "[parameters('elasticpool_name')]",
        "containmentState": 2,
        "readScale": "Disabled",
        "failoverGroupId": null
      }
    },
```

**Comment by BerendWouters** [comment]
Any update on this?

**Comment by ifeoluwaokunoren** [comment]
You should be able to use the reference function to get the resource properties and access location.
Please check here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#reference
