### ISSUE TITLE
ApiVersion 2015-06-15  for Microsoft.Storage does it work?

### ISSUE THREAD

**Issue by sjkp** [Azure/azure-resource-manager-schemas#33]
If i try to create a storage account with the following:
```json
{
             //Add Azure storage account  
            "apiVersion": "2015-06-15",
            "location": "[parameters('siteLocation')]",
            "name": "[parameters('newStorageAccountName')]",
            "type": "Microsoft.Storage/storageAccounts",
            "properties": {
                "accountType": "[parameters('storageAccountType')]"
            }            
        }
```
I get 
New-AzureResourceGroup : 18:41:07 - Resource Microsoft.Storage/storageAccounts 'azuredkwebsitestorage' failed with mess
age 'No registered resource provider found for location 'westeurope' and API version '2015-06-15' for type 'storageAcco
unts'. The supported api-versions are '2015-05-01-preview, 2014-12-01-preview'. The supported locations are 'eastus, ea
stus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, no
rtheurope'

But if I try to get the versions supported by the provider:
```json
providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]
```
I actually get version 2015-06-15 , is this on purpose? 

It is not a big issue as I just use an older API version but, it's not logical to me.

**Comment by yangl900** [comment]
thanks for reporting! The storage api-version "2015-06-15" is intended for future release (very soon!). it accidentally showed up in providers('Microsoft.Storage', 'storageAccounts') output because of a configuration error. Please keep use the preview version before the new version released.

**Comment by sjkp** [comment]
Thanks for the explanation.
