### ISSUE TITLE
JSON Endpoints Schema to SQL Server

### ISSUE THREAD

**Issue by MrGoogol** [Azure/azure-resource-manager-schemas#337]
Hello, Nice resource, I was not aware azure platform was open sourced:)
I found documentation (https://msdn.microsoft.com/en-us/library/mt704137(v=sql.105).aspx) about json but I am not able to create tables using:

DECLARE @json NVARCHAR(MAX)
SET @json='****';
SELECT *
FROM OPENJSON(@json);

How would one import the Endpoints json schema to SQL server tables?

**Comment by jaredmoo** [comment]
Hi @mike121, this repository is related to Azure Resource Management deployment templates and is not the best place for T-SQL help. I suggest checking the documentation at https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql
