### ISSUE TITLE
comments property is missing from the top schema (ARMResourceBase?)

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-resource-manager-schemas#34]
e.g.

      "apiVersion": "2015-05-01-preview",
      "type": "Microsoft.Network/virtualNetworks",
      "name": "[parameters('virtualNetworkName')]",
      "location": "[variables('VMLocation')]",
      "comments": "test",

**Comment by wenwu449** [comment]
I just tried it in VS 2015, the "comments" property is in the list now. Can you try it again?

**Comment by bmoore-msft** [comment]
yep - I tried a few different resources and it shows for all of them...

**Comment by wenwu449** [comment]
Thanks for the verification!
