### ISSUE TITLE
Missing Schema: 'Microsoft.Logic/integrationAccounts'

### ISSUE THREAD

**Issue by Geoff603** [Azure/azure-resource-manager-schemas#340]
Integration Accounts may still be in preview, but is there an ETA on adding schemas for Integration Accounts, Partners, Agreements, etc?  I'm interested in maintaining partners and related details from Visual Studio in order to keep histories and allow scripted deployments.

**Comment by ToMakeSense** [comment]
@Geoff603 there's one version there, you can find it under `schemas/2016-06-01/Microsoft.Logic.json`
![image](https://user-images.githubusercontent.com/6244148/54083688-1afaa280-4362-11e9-9165-1c8daaebc822.png)
