### ISSUE TITLE
Microsoft.ServiceBus is missing forwardTo for subscriptions

### ISSUE THREAD

**Issue by brianharwell** [Azure/azure-resource-manager-schemas#343]
I can't set up forwarding from a subscription to another topic. 

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding

I understand there is a workaround. I am requesting this feature be supported.

**Comment by ifeoluwaokunoren** [comment]
This issue is resolved and is supported in Service Bus api-version 2017-04-01. Here is the relevant doc: https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/2017-04-01/namespaces/topics/subscriptions#template-format
