### ISSUE TITLE
The schema of resource type 'Microsoft.OperationalInsights/workspaces' is not available

### ISSUE THREAD

**Issue by CurtisLusmore** [Azure/azure-resource-manager-schemas#345]
Please add the schema for Microsoft.OperationalInsights/workspaces, and if necessary for the [upgraded](https://azure.microsoft.com/en-us/blog/announcing-the-new-and-improved-azure-log-analytics/) schema as well.

**Comment by shane-day** [comment]
Be great if this was supported - makes automatic deployment orchestration possible!

**Comment by Steven-N** [comment]
Agreed. This is documented but it doesn't seem to work.

https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces

https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-template-workspace-configuration

Is there a workaround for these issues?

**Comment by CurtisLusmore** [comment]
The issue for me is that the `Export-​Azure​Rm​Resource​Group` cmdlet doesn't include OMS workspaces in the exported template because the schema is unavailable.

**Comment by kiazhi** [comment]
Requiring the `Microsoft.OperationalInsights/workspaces` schema to be added.

Discovered that the documentation by @tfitzmac contains invalid `retentionInDays` property name for `WorkspaceProperties` object below that does not work.
- https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces

Instead, replacing the `retentionInDays` property name to `retention` property name for `WorkspaceProperties` object updated by @bwren in the documentation below works for me.
- https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-template-workspace-configuration

**Comment by MarcelMeurer** [comment]
Is there any plan to update https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json ?

I can not export an OMS workspace from Azure nor can build an arm template with visual stuido.

**Comment by ifeoluwaokunoren** [comment]
Schema available here: [https://github.com/Azure/azure-resource-manager-schemas/blob/001c0a7ee838bc53008204886561ee1ffe554f78/schemas/2015-01-01/deploymentTemplate.json#L1001](2015-01-01/deploymentTemplate.json)
