### ISSUE TITLE
deployment schema doesn't support most logical functions

### ISSUE THREAD

**Issue by Porges** [Azure/azure-resource-manager-schemas#347]
`and`, `or`, `not`, and `if` from [the documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-logical) do not appear in the schema at `https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#`.

**Comment by BernieWhite** [comment]
Is this still an issue? Seems to work for me.

**Comment by jrr** [comment]
They appear to have arrived with this PR: https://github.com/Azure/azure-resource-manager-schemas/pull/341 , and are now in the published schema.

As a result, my editor now offers tooltips instead of squiggles. 

@Porges ready to close the issue?

**Comment by Porges** [comment]
Seems fixed now, thanks @QuasarSE  :)
