### ISSUE TITLE
Schema 2017-02-28-preview with Microsoft.TimeSeriesInsights is missing

### ISSUE THREAD

**Issue by alexmarshall132** [Azure/azure-resource-manager-schemas#349]
Schema 2017-02-28-preview with Microsoft.TimeSeriesInsights is missing in the code base. Can we please get this added ?

**Comment by ifeoluwaokunoren** [comment]
Schemas available for a more recent version: 
https://github.com/Azure/azure-resource-manager-schemas/blob/001c0a7ee838bc53008204886561ee1ffe554f78/schemas/2019-04-01/deploymentTemplate.json#L715
