### ISSUE TITLE
Microsoft.MachineLearning schema says OwnerEmail is optional but deployment fails in Azure Automation Runbook if not specified.

### ISSUE THREAD

**Issue by alvaradojl** [Azure/azure-resource-manager-schemas#366]
The schema for Machine Learning specifies that OwnerEmail is optional but when not specicfied it results in an error: `"Owner Email missing in request"`

**Comment by ifeoluwaokunoren** [comment]
PR to resolve this - https://github.com/Azure/azure-rest-api-specs/pull/6968
