### ISSUE TITLE
Microsoft.Scheduler/jobCollections/jobs request uri with arguments fails

### ISSUE THREAD

**Issue by ichesa** [Azure/azure-resource-manager-schemas#369]
Hi everyone,

I'm facing a problem when I deploy a template to build a scheduler job with an URI in which I want to pass two arguments.

I want to set as the uri something like "/api/triggeredwebjobs/MyJob/run?arguments=arg1%20arg2"

This works well when typing this through the Azure portal and the job starts without errors, but using an Azure template I see that in the uri the '?' character has been encoded to '%3F', what makes the job to fail because, the route does not exist.

I can't understand why is doing this since, no other character (like '/') is being encoded when deploying the template (at least I can't see it through the Azure portal).

Is this maybe a bug, or is it something I'm maybe doing wrong?

Greetings.

**Comment by ifeoluwaokunoren** [comment]
Cleaning up old issues - please open a new issue with more details if this problem still exists - thanks.
