### ISSUE TITLE
serverfarms with dynamic sku template validity

### ISSUE THREAD

**Issue by jrr** [Azure/azure-resource-manager-schemas#382]
I'm writing a template to provision a dynamic service plan for an Azure Function App. Here's my current template:

```
{
  "type": "Microsoft.Web/serverfarms",
  "apiVersion": "2015-04-01",
  "name": "[parameters('dynamicServicePlanName')]",
  "location": "[resourceGroup().location]",
  "properties": {
      "name": "[parameters('dynamicServicePlanName')]",
      "computeMode": "Dynamic",
      "sku": "Dynamic"
  }
}
```

This provisions successfully, but produces a validation error in VS Code: it squiggles the value of _apiVersion_, saying _Value is not accepted. Valid values: "2015-08-01"._

If I do what it says, and update to 2015-08-01, then I get this error when I try to provision:

```
Deployment failed. Correlation ID: 3e28a375-abbd-4b21-9cf3-304b37369c3b. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"Code\": \"BadRequest\",\r\n  \"Message\": \"The parameter sku has an invalid value.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"The parameter sku has an invalid value.\"\r\n    },\r\n    {\r\n      \"Code\": \"BadRequest\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"51008\",\r\n        \"MessageTemplate\": \"The parameter {0} has an invalid value.\",\r\n        \"Parameters\": [\r\n          \"sku\"\r\n        ],\r\n        \"Code\": \"BadRequest\",\r\n        \"Message\": \"The parameter sku has an invalid value.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
          }
        ]
      }
    ]
  }
}
```

The top of my template is referencing this schema: 

`  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",`

Am I doing something wrong, or is there an issue with the schemas?

**Comment by tlisiecki** [comment]
This is a mystery for me as well.
The parameter
```
      "sku": "Dynamic"
```
 seems to be valid only if you specify the "apiVersion": "2015-04-01". 
Why isn't it a valid option in newer api version? Is it deprecated?
The are multiple newer versions abailable...

```powershell
> ((Get-AzureRmResourceProvider -ProviderNamespace Microsoft.Web).ResourceTypes | Where-Object ResourceTypeName -eq serverfarms).ApiVersions
2017-08-01
2016-09-01
2016-03-01
2015-08-01
2015-07-01
2015-06-01
2015-05-01
2015-04-01
2015-02-01
2014-11-01
2014-06-01
2014-04-01-preview
2014-04-01
```

**Comment by naveedaz** [comment]
Please use the following excerpt. Notice that the sku property is outside the "properties" property and is not a plain string. 

{
  "type": "Microsoft.Web/serverfarms",
  "apiVersion": "2015-08-01",
  "name": "[parameters('dynamicServicePlanName')]",
  "location": "[resourceGroup().location]",
  "sku": {
        "name": "Y1"
    },
  "properties": {
      "name": "[parameters('dynamicServicePlanName')]",
  }
}
https://stackoverflow.com/questions/47522539/server-farm-service-plan-skus
