### ISSUE TITLE
DevTestLab Artifacts - Cannot run as different user elevated

### ISSUE THREAD

**Issue by jt000** [Azure/azure-resource-manager-schemas#401]
I've been working on a script to setup test environment for my team using DevTestLabs, but unfortunately have run into a roadblock, which I haven't been able to work around. During machine setup, I need to run an application elevated as a domain joined user. I've worked on this for the past couple of days & the best I can do is below (assume the `echo` is my application that I need to run) :

```
$cmd = "Start-Process -FilePath cmd -ArgumentList (\""/C\"", \""echo HELLO %USERDOMAIN%\%USERNAME%! > $outFile\"") -WorkingDirectory C:\ -Verb runAs -Wait"
Start-Process powershell.exe -ArgumentList $cmd -Wait -Credential $credential -NoNewWindow -WorkingDirectory C:\
Get-Content $outFile | foreach {Write-Output $_}
```

This works when run manually, but pops up the UAC dialog. Obviously, this won't work as an artifact. 

**Suggestion:** Is there any chance you'd be willing to add a property to [ArtifactInstallProperties](https://github.com/Azure/azure-resource-manager-schemas/blob/91a87cb1aec8e0e6280cf9bcd63dc6002cdb257b/schemas/2016-05-15/Microsoft.DevTestLab.json#L1067), which would allow for passing a user to run the artifact as?

An example usage might be something like:

```
"artifacts": [
  {
    "artifactId": "[resourceId('Microsoft.DevTestLab/labs/artifactSources/artifacts', parameters('labName'), 'public repo', 'windows-domain-join-new')]",
    "parameters": [
      { "name": "domainAdminUsername", "value": "[parameters('username')]" },
      { "name": "domainAdminPassword", "value": "[parameters('password')]" },
      { "name": "domainToJoin", "value": "[parameters('domainToJoin')]" },
      { "name": "ouPath", "value": "[parameters('ouPath')]" }
     ]
  },
  {
    "artifactId": "[resourceId('Microsoft.DevTestLab/labs/artifactSources/artifacts', parameters('labName'), 'privaterepo549', 'my-custom-artifact)]",
    "runAsUsername": "[parameters('username')",
    "runAsPassword": "[parameters('password')"
  }
]
```

If you have any alternate suggestions or workarounds, this would help my team out greatly move away from private VMs and to DevTestLabs.  Thanks!

**Comment by tanmayeekamath** [comment]
Hi!
Thanks for submitting the issue and apologies for the delay. It seems you reached out on the incorrect forum. To post questions on DevTest Labs related issues, please visit the DTL GitHub repo here: https://github.com/Azure/azure-devtestlab

Currently we have a feature in our backlog that attempts to address your issue in a different manner. 
We are investigating on ways to integrate with Azure Managed Identities to enable users bring their own user defined MSIs while running artifacts on DTL VMs. 
Here is some info on MSIs if you are not familiar: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

I would love to have a chat with you over a 30 min meeting to understand your scenario better and capture any specific requirements you have. 

Would you be willing to share your feedback through a meeting?

Thanks,
Tanmayee
