### ISSUE TITLE
Microsoft.Resources/deployments with expressions in resourceGroup shows schema error

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-resource-manager-schemas#443]
This was reported by @artisticcheese in https://github.com/Microsoft/vscode-azurearmtools/issues/37.  Here's a template snippet that shows this error:

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "AutomationaccountRGName": {
            "type": "string",
            "metadata": {
                "description": "Name of automation account"
            }
        }
    },
    "resources": [
        {
            "name": "WorkerNodeDscConfiguration",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2017-05-10",
            "resourceGroup": "[parameters('automationAccountRGName')]",
            "dependsOn": [],
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.1",
                    "resources": []
                }
            }
        }
    ]
}

**Comment by StephenWeatherford** [comment]
The error it shows in VS Code:
![image](https://user-images.githubusercontent.com/6913354/38896679-44cf0e6e-4248-11e8-82eb-39ef402a62df.png)

![image](https://user-images.githubusercontent.com/6913354/38896686-4925829a-4248-11e8-9600-64b4bcdc4e06.png)

And I believe the problem is here: https://github.com/Azure/azure-resource-manager-schemas/blob/b5ae46febcfc5f915ff1e8ec9cca3e068ff21422/schemas/2017-05-10/Microsoft.Resources.json#L29

**Comment by artisticcheese** [comment]
Same goes for Reference function. It allows 3 parametes but extension complaints about that only 2 parameters are supported (https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#reference)

![image](https://user-images.githubusercontent.com/13176884/39015080-d910e756-43e1-11e8-96b2-52e22bf72b5e.png)

**Comment by StephenWeatherford** [comment]
@artisticcheese I know this is confusing - the validation of number of arguments to a function is handled by the extension - so reference() taking 3 args was fixed by the extension for next version in https://github.com/Microsoft/vscode-azurearmtools/pull/67.  

The schema handles more general issues like validating string values in general. Since it's validating string values it has to recognize when an expression is in use (this bug).  The ARM VS Code extension does a bit more analysis of the actual syntax inside of an expression.  Thanks for being on the ball, though.

**Comment by StephenWeatherford** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/4803484

**Comment by StephenWeatherford** [comment]
This has been fixed.
