### ISSUE TITLE
Some resources in Microsoft.Network are not referenced from deploymentTemplate.json schema

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-resource-manager-schemas#445]
Taken from https://github.com/Microsoft/vscode-azurearmtools/issues/28.

It appears that some virtual network resources are not being picked up in the schema, including at least:
- Microsoft.Network/virtualNetworkGateways
- Microsoft.Network/virtualNetworks/subnets
- Microsoft.Authorization/policyAssignments
- Microsoft.Authorization/policyDefinitions

**NOTE: There are definitions for these in Microsoft.Network.json, but the are not referenced from deploymentTemplate.json like all other individual resources from Microsoft.Network.json are.**

Attached is a template file that was created from the Azure portal.  If you load it in VS Code or Visual Studio, it gives errors:

![image](https://user-images.githubusercontent.com/6913354/38904641-65cd2e6c-4260-11e8-9e59-9f307fe48b4f.png)

[virtualNetworkGatewayFromPortal.zip](https://github.com/Azure/azure-resource-manager-schemas/files/1921988/virtualNetworkGatewayFromPortal.zip)

**Comment by jabbera** [comment]
Hi,

Any update on this?

Mike

**Comment by jabbera** [comment]
Hi,

Any update on this?

Mike

**Comment by StephenWeatherford** [comment]
@bmoore-msft Do you know how to push this to get fixed?  Thx.

**Comment by bmoore-msft** [comment]
Best approach is to update your apiVersion to a published schema - export changes should be available in a few months

**Comment by StephenWeatherford** [comment]
As far as I can tell, there is *no* published schema for these resources.

**Comment by StephenWeatherford** [comment]
https://github.com/microsoft/vscode-azurearmtools/issues/254

**Comment by ifeoluwaokunoren** [comment]
@number213 @EvgenyAgafonchikov please review
@MikhailTryakhov FYI

**Comment by StephenWeatherford** [comment]
From customers:
See a similar error for Microsoft.Network/virtualNetworks/subnets

**Comment by number213** [comment]
Network part is fixed by https://github.com/Azure/azure-resource-manager-schemas/pull/653 and https://github.com/Azure/azure-resource-manager-schemas/pull/661/files

**Comment by ifeoluwaokunoren** [comment]
Microsoft.Authorization part fixed with this PR: https://github.com/Azure/azure-resource-manager-schemas/pull/685 . Policy definitions can only be created at the subscription or MG level. The schema for subscription deployment is already up to date.
