### ISSUE TITLE
Stream Analytics SQL Output not setting password correctly 

### ISSUE THREAD

**Issue by gumaflux** [Azure/azure-resource-manager-schemas#451]
This is the sample JSON for defining an Azure Stream Analytics Output in an arm template. 

```
{    
   "properties":{    
      "datasource":{    
         "type":"Microsoft.Sql/Server/Database",  
         "properties":{    
            "server":"sampleserver.database.windows.net",  
            "database":"sampleDB",  
            "table":"sampleTable",  
            "user":"user@sampleserver",  
            "password":"****************"  
         }  
      }  
   }  
}  
```
This template does not correctly set the password for the SQL output. The password resolves to null. You need to manually set the password after the deployment has completed.  

Steps to reproduce is to create an arm template with an Azure SQL Server database and an Azure Stream Analytics Job with a SQL Output to the SQL Server database. Hard code the SQL Admin password into the arm template, on the database and the ASA output. Test the ASA output which will return failed with login failed.

**Comment by ifeoluwaokunoren** [comment]
According to the SQL team - this behavior would is by design. Passwords should never be part of a GET output, and most likely this is a long running async process, where the final result is retrieved using a GET.
