### ISSUE TITLE
Feature to refer existing storage accounts while creating EventSubscription using ARM

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-resource-manager-schemas#455]
```
{
            "type": "Microsoft.Storage/StorageAccounts/providers/eventSubscriptions",
            "name": "[concat(parameters('StorageName'), '/Microsoft.EventGrid/', parameters('eventgridsubscription_name'))]",
            "apiVersion": "2018-01-01",
            "properties": {
                "destination": {
                    "endpointType": "EventHub",
                    "properties": {
                        "resourceId": "[resourceId(concat('Microsoft.EventHub/namespaces/eventhubs',parameters('namespaces_BlobReaderNamespace_name'),parameters('eventhubs_blobreadereventhub_name')))]"
                    }
                },
                "filter": {
                    "subjectBeginsWith": "",
                    "subjectEndsWith": "",
                    "isSubjectCaseSensitive": false,
                    "includedEventTypes": ""
                }
            }
        }
```

I have the following schema and I am trying to create event subscription with Storage Account as publisher and Event Hub as Subscriber. I am able to create it when using storage accounts created by the same ARM but not able to refer to existing Storage Accounts outside ARM.
I would be helpful if one can refer existing resources in ARM while creating Event Subscription.

**Comment by ahamad-MS** [comment]
Hello @himanshu219 . Thanks for reporting this issue. 

You definitely can use ARM template to create an event subscription to an "existing" storage account. Please try the following template and replace the value in [ ] with appropriate values. This will create an event subscription with an existing storage account as publisher and event hub as subscriber.

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": 
    [
        {
            "type": "Microsoft.Storage/storageAccounts/providers/eventSubscriptions",
            "name": "[StorageAccountName]/Microsoft.EventGrid/[EventSubscriptionName]",
            "apiVersion": "2018-01-01",
            "properties": 
            {
                "topic": "/subscriptions/[Subscription Id]/resourcegroups/[ResourceGroupName]/providers/Microsoft.Storage/storageAccounts/[StorageAccountName]",
                "destination":
                {
                    "endpointType": "EventHub",
                    "properties": 
                    {
		        "resourceId": "/subscriptions/[Subscription Id]/resourceGroups/[ResourceGroupName]/providers/Microsoft.EventHub/namespaces/[EventHubNameSpace]/eventhubs/[EventHubName]"
                    }
                },
		"filter": 
                {
		    "subjectBeginsWith": "abc",
	            "subjectEndsWith": "efg",
		    "isSubjectCaseSensitive": true,
		    "includedEventTypes": 
                    [
		        "Microsoft.Storage.BlobDeleted",
			"Microsoft.Storage.BlobCreated"
		    ],
		    "advancedFilters": []
		},
		"labels": [],
		"eventDeliverySchema": "EventGridSchema"            
           }
        }
    ]
}

Please let me know if you are still hitting any other issues. thanks
