### ISSUE TITLE
ARM API Management Create Versioned API with swagger 

### ISSUE THREAD

**Issue by sabbadino** [Azure/azure-resource-manager-schemas#459]
Hi, If create a new api NOT providing information regarding a swagger file , the API is correctly created as versioned. 
If, in the arm below, I remove serviceUrl and add _contentFormat_ and _contentValue_ 
the API **is not created as versioned.** 

If I create the API without swagger (so it's created as versioned) and then I rerun the arm template providing the swagger the api remain versioned and the swagger is updated.

{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "location": {
      "type": "string",
      "defaultValue": "[resourceGroup().location]",
      "metadata": {
        "description": "Location for all resources."
      }
    }
  },
  "variables": {
    "apiManagementServiceName": "xxxx"
  },
  "resources": [
    {
      "name": "[concat('xxxx', '/', 'PetStoreVersionSet')]",
      "type": "Microsoft.ApiManagement/service/api-version-sets",
      "apiVersion": "2017-03-01",
      "properties": {
        "displayName": "PetStore Name",
        "description": "PetStore Description",
        "versioningScheme": "Segment"
      }
    },
    {
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/api-version-sets', 'xxxx', 'PetStoreVersionSet')]"
      ],
      "apiVersion": "2017-03-01",
      "type": "Microsoft.ApiManagement/service/apis",
      "name": "xxxx/PetStoreSwaggerImportExample",
      "properties": {
        "displayName": "name",
        "apiRevision": "1",
        "description": "description",
        "serviceUrl": "https://www.google.com",
        //"contentFormat": "swagger-link-json",
        //"contentValue": "http://petstore.swagger.io/v2/swagger.json",
        "path": "petstore",
        "protocols": [
          "https"
        ],
        "isCurrent": true,
        "apiVersion": "v1",
        "apiVersionName": "v1 Name",
        "apiVersionDescription": "apiVersionDescription",
        "apiVersionSetId": "[concat('/','api-version-sets', '/', 'PetStoreVersionSet')]"
      }
    }
  ]
}

**Comment by akalcik** [comment]
I have the same issue, as soon as  ```contentFormat": "swagger-link-json"``` ist set, the version isn't created.

**Comment by jaq316** [comment]
Any update on this?

**Comment by KedarJoshi** [comment]
This was a known bug and fixed the in 2019-01-01 api-version for API Management.

**Comment by dirkslab** [comment]
If this were resolved, please please show me an example of creating a version set within the API template body. ref in documentation state 'Identifier for existing API Version Set. Omit this value to create a new Version Set'. Got it working, but not as expected above. You still need to create a new version set by using type "Microsoft.ApiManagement/service/apiVersionSets". Would appreciate an example, thanks very much.

**Comment by KedarJoshi** [comment]
that is by-design.  ApiVersionsets and APIs are different entity.  Creation of apiVersionSets is separate from associating an API with an existing apiVersionSet and creating that API as versioned.  so if apiVersionSet does not exists, the payload won't create that.  you should create apiVersionSet and then create versioned API by associating apiVersionSetId property.  from the original post that seemed to be the intention.

**Comment by dirkslab** [comment]
thanks for the responce. What purpose does 
    "apiVersionSet": {
      "id": "string",
      "name": "string",
      "description": "string",
      "versioningScheme": "string",
      "versionQueryName": "string",
      "versionHeaderName": "string"
    } under "type": "Microsoft.ApiManagement/service/apis" properties have. What does the Omit Id to create new in the documentation mean?

Found I had to create the version set, ref the version set using apiVersionSetId in api template as well as ref the name in "apiVersionSet": {
      "name": "string"
    }, also in the api template. This does not feel optimal, and would really appreciate an example if available.
