### ISSUE TITLE
API Management Sample JSON Containing an Array Fails Validation

### ISSUE THREAD

**Issue by ToddTaylor** [Azure/azure-resource-manager-schemas#487]
If an API Management ARM template contains sample JSON that has an array in it, the template fails validation as shown on the simplified example below (line 10):

![image](https://user-images.githubusercontent.com/25310942/42831626-6feca242-89b4-11e8-83f7-fd0854029d9c.png)

I had to put two backslashes in front of the sample string in order to get the template to pass validation.

**Comment by satls** [comment]
What was your workaround for this?

**Comment by antmarti-microsoft** [comment]
Closing as this has been answered by @satls. Please open a new issue if you are still having problems with this.
