### ISSUE TITLE
Json Schema is outdated for Network resources

### ISSUE THREAD

**Issue by dthielking** [Azure/azure-resource-manager-schemas#503]
Hello,

I am using VSCode. If I'm using network resources like `Microsoft.Network/virtualNetworks` or `Microsoft.Network/virtualNetworkGateways` I'm using apiVersion: 2018-07-01. 
Error:
__Value is not accepted. Valid values: "2016-06-01".__
__API Version of the resource type, optional when apiProfile is used on the template__

I'm using the json schema [Link to Schema](https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#) but found out, that the apiVersion: 2017-07-01 is missing. 
Maybe can someone add this apiVersion?

Or do i configure something wrong?

**Comment by MikhailTryakhov** [comment]
@number213 @EvgenyAgafonchikov  please review as well

**Comment by number213** [comment]
Yes, Network's 2018-07-01 is missing. I'll add it (and other missing API versions if I find any)

**Comment by number213** [comment]
Fixed by https://github.com/Azure/azure-resource-manager-schemas/pull/661 and https://github.com/Azure/azure-resource-manager-schemas/pull/653
