### ISSUE TITLE
Json schema URL offline

### ISSUE THREAD

**Issue by dthielking** [Azure/azure-resource-manager-schemas#504]
Hello I'm using https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json to load the schema, but it seems that the URL is offline.

**Comment by MisinformedDNA** [comment]
All links to https://schema.management.azure.com/ seem to be down.

**Comment by ifeoluwaokunoren** [comment]
Hello,
We're tracking reliability improvements internally, and we use github issues to track issues found in this repo. That being said, please do let us know if you still encounter this issue.
