### ISSUE TITLE
API version 2015-06-15 not reflecting after creation of resources

### ISSUE THREAD

**Issue by ankushtalreja** [Azure/azure-resource-manager-schemas#52]
I changed API version of virtual machine resource from 2015-05-01-preview  to 2015-06-15  in deployment JSON but after creation of VM when I checked its version on resources.azure.com, it showing me 2015-05-01-preview

**Comment by mahthi** [comment]
This should definitely not happen. Can you double check the apiVersion on all the VMs in the template again? Also, would you mind sharing the template or the VM Snippet with me?

**Comment by ankushtalreja** [comment]
Its happening with all the reosurces for which I am changing API version in JSON such as virtual network, network interfaces, storage account etc..
![resexp-vm](https://cloud.githubusercontent.com/assets/15380287/10841392/df715d78-7f0e-11e5-9b24-8c83164c2899.JPG)
![resexp-vn](https://cloud.githubusercontent.com/assets/15380287/10841391/df70f69e-7f0e-11e5-99e4-9ca7526dcf05.JPG)
![virt machine](https://cloud.githubusercontent.com/assets/15380287/10841393/df75d10a-7f0e-11e5-8ee2-bfdc99f666cd.JPG)
![vn](https://cloud.githubusercontent.com/assets/15380287/10841394/df7ab0e4-7f0e-11e5-92ba-0664c2951360.JPG)

**Comment by wenwu449** [comment]
@ankushtalreja, "2015-06-15" and "2015-05-01-preview" are api-versions, they are not resource versions. The "2015-06-15" in your template is used as api-version when creating a VM, and the "2015-05-01-preview" in the Url of resources.azure.com is the api-version used by the "resources.azure.com" service to get VM detail.
Also, as this is a collaboration repo for schema, template usage questions like this may not get attention in time. I would suggest you post template usage questions in MSDN forum to get more prompt responses.
