### ISSUE TITLE
Proposal: Merge common definitions to single file.

### ISSUE THREAD

**Issue by rhencke** [Azure/azure-resource-manager-schemas#53]
Currently, if a schema is added, it must be added in two places: schemas\2014-04-01-preview\deploymentTemplate.json and schemas\2015-01-01\deploymentTemplate.json.  It is an easy thing to miss.

If these were extracted out to a common file, say, schemas\common.json, this would ensure both deployment templates always kept up-to-date.  Also, if a new version of deploymentTemplate is added, it will simplify maintenance.

It could also serve as a home for common definitions found across files that are highly unlikely to changes (GUID definition, for example)

(I'm happy to hack on this, but wanted to see what thoughts were first)

**Comment by anthony-c-martin** [comment]
We're moving towards automatically generating schemas for all providers, and there are very few teams still manually creating PRs for schemas.

I believe as of today, this isn't much of a problem, and it should go away entirely when we've fully automated things.
