### ISSUE TITLE
Missing definition: ApplicationSecurityGroupPropertiesFormat

### ISSUE THREAD

**Issue by dowlingw** [Azure/azure-resource-manager-schemas#539]
**What happened**
It looks like the `ApplicationSecurityGroupPropertiesFormat` definition is referenced in several places but not defined.

**Expected behaviour**
All referenced types should be resolvable.

**Comment by CHDAFNI-MSFT** [comment]
I've noticed this issue as well for at least a year.

**Comment by ifeoluwaokunoren** [comment]
@number213 @EvgenyAgafonchikov please review
@MikhailTryakhov FYI

**Comment by number213** [comment]
Fixed by https://github.com/Azure/azure-resource-manager-schemas/pull/683
cc: @anthony-c-martin
