### ISSUE TITLE
ARM Schemas contain invalid byte order marker

### ISSUE THREAD

**Issue by dowlingw** [Azure/azure-resource-manager-schemas#541]
**Background**
API specifications for `2014-04-01-preview` onwards appear to contain a byte-order marking in violation of RFC7159 S8.1:

>    Implementations MUST NOT add a byte order mark to the beginning of a
>   JSON text.  In the interests of interoperability, implementations
>   that parse JSON texts MAY ignore the presence of a byte order mark
>   rather than treating it as an error.

**What was expected**
Using third party tools to manipulate schemas from this repository to be able to open and work with JSON Schema documents without error.

**What actually happened**
When working with various JSON tools, they reject schemas from this repository as invalid JSON documents.

**Comment by ifeoluwaokunoren** [comment]
Fixed with https://github.com/Azure/azure-resource-manager-schemas/pull/757
