### ISSUE TITLE
Error when deploying Stream Analytics job containing tabs with "Azure Resource Group Deployment" task

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-resource-manager-schemas#546]
I also added this issue in the "azure-stream-analytics" section because I wasn't sure what the best location should be.

When you deploy a Stream Analytics job with an "Azure Resource Group Deployment" task with a query that contains tab characters, the deployment task results in a failure.

**Comment by antmarti-microsoft** [comment]
This doesn't sound like a schema issue, and as you mentioned is being tracked by the Stream Analytics team under https://github.com/Azure/azure-stream-analytics/issues/54. Please follow up with them there.
