### ISSUE TITLE
Add Microsoft.Web/customApis for latest preview versions

### ISSUE THREAD

**Issue by jdkemme** [Azure/azure-resource-manager-schemas#551]
2016-06-01 is the latest documented template reference.  Please include the latest preview APIs.  We're trying to set 'use data gateway' option via deployment, but this option doesn't appear to be available in the 2016-06-01 api. 

"resourceType": "customApis"
"2018-07-01-preview",
"2018-03-01-preview",
"2016-06-01"

Reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2016-06-01/customapis

**Comment by ifeoluwaokunoren** [comment]
@visharm Can you please take a look at this. Thanks.

**Comment by visharm** [comment]
I am sorry what is it regarding? I have a CR out for updating Logic Apps Swagger.
Didn't get the context of this comment.

**Comment by anthony-c-martin** [comment]
Fixed by #1691

Note that the `2018-07-01-preview` & `2018-03-01-preview` APIs appear to have been retired, but the `2019-06-01` API is available.
