### ISSUE TITLE
Schema encourages array, which breaks ARM deployment with a difficult to decipher message

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-resource-manager-schemas#560]
I'll spare you a detailed description of the hours of pain this problem gifted me...

Here's the error I saw when deploying my template:

![image](https://user-images.githubusercontent.com/1901832/51155507-701aba80-18c3-11e9-9177-bbc77ca43d03.png)

As text:

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidRequestFormat\",\r\n \"message\": \"Cannot parse the request.\",\r\n \"details\": [\r\n {\r\n \"code\": \"InvalidRequestFormat\",\r\n \"message\": \"Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,System.String]' because the type requires a JSON object (e.g. {\\\"name\\\":\\\"value\\\"}) to deserialize correctly.\\r\\nTo fix this error either change the JSON to a JSON object (e.g. {\\\"name\\\":\\\"value\\\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\\r\\nPath 'properties.parameters', line 1, position 133.\"\r\n }\r\n ]\r\n }\r\n}"}]}
```

And the cause of the error? This innocuous bit of JSON:

![image](https://user-images.githubusercontent.com/1901832/51155622-cc7dda00-18c3-11e9-9670-a1aafe3bdda3.png)

And why is it specified as an array? Because when you use an object, the analysis engine tells you not to:

![image](https://user-images.githubusercontent.com/1901832/51155661-f33c1080-18c3-11e9-86f1-f1911f60b6a5.png)

**Comment by ifeoluwaokunoren** [comment]
This has now been fixed with the following PR: https://github.com/Azure/azure-resource-manager-schemas/pull/664
