### ISSUE TITLE
Failure on 1st run when deploying Microsoft.Insights/scheduledQueryRules resource in template

### ISSUE THREAD

**Issue by gavjeffrey** [Azure/azure-resource-manager-schemas#567]
I have a simple scheduled query rule that I want to be deployed. The first time it runs it fails saying that the query is invalid. The query is definitely valid though. If I run it straight after it gets deployed without any errors. 

Here is the error and subsequent success straight after -

> PS U:\> az group deployment create --resource-group armtemplate-rg --template-file C:\Source\Back-end\Deployment\Deployment\environment-resources-deploy.json
Deployment failed. Correlation ID: 7e2084d6-5109-4547-a7c1-0c5ec9a56699. {
  "error": {
    "code": "properties.search.query is not a valid log or metric query.An error occurred while sending the request.",
    "message": {
      "lang": "en-US",
      "value": "properties.search.query is not a valid log or metric query.An error occurred while sending the request."
    },
    "innererror": {
      "stacktrace": "System.ArgumentException: properties.search.query is not a valid log or metric query.An error occurred while sending the request.\r\n   at Microsoft.AppInsights.Nexus.ResourceProvider.Validation.Ensure.IsTrue(Boolean value, String message) in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Nexus\\ResourceProvider\\Validation.cs:line 235\r\n   at Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<ValidateQuery>d__43.MoveNext() in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 798\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<ValidateAlertingActionAndResultToMetricAction>d__38.MoveNext() in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 714\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<ValidateAsync>d__35.MoveNext() in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 566\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.AppInsights.Nexus.ResourceProvider.Csm.CsmResourceProvider`1.<PutResourceAsync>d__19`1.MoveNext() in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Nexus\\ResourceProvider\\Csm\\CsmResourceProvider.cs:line 418\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass13_0.<<PutResourceAsync>b__0>d.MoveNext() in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 208\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in d:\\sqrapifairfax\\Mgmt\\LogAnalytics\\SQRApi\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
    }
  }
}
PS U:\> az group deployment create --resource-group armtemplate-rg --template-file C:\Source\Back-end\Deployment\Deployment\environment-resources-deploy.json
{
  "id": "/subscriptions/.../resourceGroups/armtemplate-rg/providers/Microsoft.Resources/deployments/environment-resources-deploy",
  "location": null,
  "name": "environment-resources-deploy",

This  started happening recently and wasn't a problem before.

**Comment by antmarti-microsoft** [comment]
This sounds like an intermittent problem with the Microsoft.Insights service, and not an issue with the schemas repo itself.

If this is still occurring, please raise a support case with https://aka.ms/azuresupport
