### ISSUE TITLE
Internal Server Error while deploying staging slot 

### ISSUE THREAD

**Issue by j03Martin** [Azure/azure-resource-manager-schemas#581]
The error I received was '"message": "There was an unexpected InternalServerError.  Please try again later.'
It happens during the creation of the "Resource Microsoft.Web/sites/slots".
The error is very vague, and the template ran find two weeks ago. Is there an outages with the service, if so where are the outages reported?

**Comment by antmarti-microsoft** [comment]
This sounds like an intermittent problem with the Microsoft.Web service, and not an issue with the schemas repo itself.

If this is still occurring, please raise a support case with https://aka.ms/azuresupport
