### ISSUE TITLE
how to use "contentFormat": "swagger-json", for deploying swagger json file from ARM template APi Managment

### ISSUE THREAD

**Issue by tkumark** [Azure/azure-resource-manager-schemas#589]
I would like to know how to use `"contentFormat": "swagger-json",` I assuming when we set contentFormat as swagger-json it means that we are pointing to a file? I get the below error or am i using it wrong.
https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2018-06-01-preview/service/apis

```
        "contentFormat": "swagger-json",
        "contentValue": "D:\\tempvsts\\APISwagger\\APISwagger\\swagger.json",
```

> "message": "Parsing error(s): Unexpected character encountered while parsing value: D. Path '', line 0, position 0."

**Comment by KedarJoshi** [comment]
@tkumark, if the content format is swagger-json that means you need to provide actual JSON in the value as string (escaped for JSON).  if you want to use swagger-link-json then you can provide the json via a publically accessible URL.  

in your e.g. the local file will not work in either case.
