### ISSUE TITLE
apiVersion property does not recognize functions as a valid value

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-resource-manager-schemas#59]
For example, this:

      "apiVersion":"[variables('apiVersion')]",

Is not recognized as valid, it expects a literal string.

**Comment by wenwu449** [comment]
VS is relying on the some properties like "apiVersion", "type" to decide which schema should be picked up to do the validation. 
Technically we can define a resource with all the properties as expression, but VS will not be able to do validation on it, right?

**Comment by bmoore-msft** [comment]
ah - you might be right, @daschult is that what the schema intellisense is doing?

**Comment by daschult** [comment]
The JSON property intellisense that you get in Visual Studio is based around the JSON schema that is referenced by the drop down box at the top of the file. When you get errors around "apiVersion", that's simply the JSON schema (probably deploymentTemplate.json) indicating that the value of "apiVersion" is incorrect.
At this point VS cannot validate the contents of an expression like Brian mentioned at the top of this thread. The deploymentTemplate.json could be changed to support function expressions, but I think you'd lose a lot of validation as Wenjun mentioned.

**Comment by bmoore-msft** [comment]
ok, sounds like this is not a good suggestion then... we'll need to think about it more though if the platform makes a refinement on the property.
