### ISSUE TITLE
Schema incorrectly says that delegation name is optional

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-resource-manager-schemas#590]
This feedback is about https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-11-01/virtualnetworks#Delegation

If I omit the `name` property, I get this error:
```json
{
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": []
  }
```

**Comment by ifeoluwaokunoren** [comment]
@number213 @EvgenyAgafonchikov please review
@MikhailTryakhov FYI

**Comment by number213** [comment]
@anthony-c-martin my bad, I referenced wrong issue. I'll work on fix for this one tomorrow
