### ISSUE TITLE
CosmosDB Schema has incorrect property name maxLength

### ISSUE THREAD

**Issue by KyleMartin901** [Azure/azure-resource-manager-schemas#591]
For [Microsoft.DocumentDB.json](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-04-08/Microsoft.DocumentDB.jsonl) the **name** property has a maxLength of 50 which is invalid because you are only allowed a max of 31 due to appending the domain **.documents.azure.com** to the cosmosdb name.

![image](https://user-images.githubusercontent.com/978620/55844349-384ca780-5b80-11e9-9ecc-bb59718d364a.png)

**Comment by shurd** [comment]
Hi @KyleMartin901, thank you for raising this issue. If you do a template deployment using the schema, you can create an account with a name up to 50 characters long. Our resource provider currently validates that the regional account name and global account name are both 50 characters or less. 

When creating an account through a form on the portal, we validate that the name is at most 31 characters long. Default regional account names are created by appending "-region" to the end of the account name. With the longest region, this suffix is 19 characters long. We do not allow custom regional account names through this form, so we make sure that you can add any region when creating the account. When deploying the template or directly going through out RP, you can specify a custom regional account name, so we allow 50 characters for the global account name.

**Comment by ifeoluwaokunoren** [comment]
Change required on the service (CosmosDB) - and the service team is tracking that separately.
