### ISSUE TITLE
literal vs variables/parameters

### ISSUE THREAD

**Issue by j03Martin** [Azure/azure-resource-manager-schemas#596]
The issue: 
If you put an empty array symbol "[]" into the "resource" field of a template it will validate and run. 
Example: 

{
	"contentVersion": "1.0.0.0",
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"parameters": {
		
		
        "test": {
			"type": "array",
			"defaultValue": []
          
        } 
	},
	"variables": {
		"test" : []
	},
	"resources": []
}

If you make a parameter that equals [] and set that parameter equal to the resource field it will fail to execute, because it tries to access the first element in an empty array

{
	"contentVersion": "1.0.0.0",
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"parameters": {
		
		
        "test": {
			"type": "array",
			"defaultValue": []
          
        } 
	},
	"variables": {
		"test" : []
	},
	"resources": ["parameters('test')"]
}
Error: 'Error converting value 
"[parameters('test')]" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Templates.Schema.TemplateResource[]'. Path 'properties.template.resources[0].resources'

same thing happens if you run:
{
	"contentVersion": "1.0.0.0",
	"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"parameters": {
		
		
        "test1": {
			"type": "array",
			"defaultValue": []
          
        } 
	},
	"variables": {
		"test" : []
	},
	"resources": ["variables('test')"]
}
Error: 'Error converting value "[variables('test')]" 
to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Templates.Schema.TemplateResource[]'. Path 'properties.template.resources[0].resources'

Is this intended functionality? Normally an interpreter would resolve the value of the variable and then insert that value into the given element. Any guidance would be helpful, on what yall do?

**Comment by ifeoluwaokunoren** [comment]
Closing issue - please re-open a new issue with more details if this is still an issue.
Thanks.
