### ISSUE TITLE
Microsoft.ClassicCompute/domainNames where is it?

### ISSUE THREAD

**Issue by sjkp** [Azure/azure-resource-manager-schemas#6]
I downloaded the template Microsoft.CloudService.1.0.1 from the gallery with Save-AzureResourceGroupGalleryTemplate and would like to see the scheme for it. Specifically if it's possible to point to a cloud package and configuration from the template to have it deployed as part of creating the resource group. 

Thanks in advance.

**Comment by yangl900** [comment]
The classic compute API is intend for Azure Portal use only. The team has no plan to publish schema or document for these APIs. Please contact vmaker at Microsoft if you need develop using these APIs.

**Comment by wadhwa94** [comment]
I am not able to get any template from Gallery. Powershell 1.0
Can you provide the cmdlet for getting the templates from gallery.
To be specific i need **Template for Microsoft.ClassicCompute/domainnames i.e. (cloud Service**)

**Comment by sjkp** [comment]
You have to be in a private preview to get access to it

**Comment by wadhwa94** [comment]
Ok Thanks.
can you provide me a template for Deploying Cloud service i.e. Microsoft.ClassicCompute/domainNames -  I am getting some error related to **length** property - which i am not able to determine.
Thanks

**Comment by sjkp** [comment]
@wadhwa94 no sorry cant help, because I'm not in the private preview, and I'm not a Microsoft employee :)

**Comment by rohitvats** [comment]
@sjkp - Did you find out ARM template for deploying cloud service? 

Not able to even provision container using template - https://github.com/sjkp/azure-gallery-templates/blob/master/Microsoft.CloudService.1.0.1.json. I am using New-AzureRmResourceGroupDeployment from powershell. Would be of great help if you can direct me to correct direction.

Thanks

**Comment by sjkp** [comment]
Nope sorry, gave up on cloud services long time ago.
