### ISSUE TITLE
Request: Add Azure Environment to Subscription() function

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-resource-manager-schemas#605]
Request to add an element to Subcription() or other resource/deployment function to include the Azure Cloud environment - Ex: Azure Government, Azure Commercial

This can be used with Conditions or Naming conventions in templates which removes the need for environment to be inputted as a parameter

**Comment by bmoore-msft** [comment]
@CHDAFNI-MSFT - you can use the environment() function to get cloud information... it's new so only in public cloud right now, be a few weeks before it hits national clouds.

{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  },
  "resources": [
  ],
  "outputs": {
    "env": {
      "type": "object",
      "value": "[environment()]"
    }
  }
}
