### ISSUE TITLE
Microsoft.Resources/virtualMachines and Microsoft.Resources/virtualMachines/extensions are missing version 2019-03-01

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-resource-manager-schemas#626]
Other versions are referenced from deploymentTemplate.json, but not 2019-03-01 (probably affects other resources, too).

Reported by customer in https://github.com/microsoft/vscode-azurearmtools/issues/255

**Comment by ifeoluwaokunoren** [comment]
Resolved in this PR: https://github.com/Azure/azure-resource-manager-schemas/pull/632
By the way the title should be microsoft.compute/virtualMachines and microsoft.compute/virtualMachines/extensions
