### ISSUE TITLE
Microsoft.Network/networkInterfaces is missing version 2018-11-01

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-resource-manager-schemas#627]
Reported by customer in https://github.com/microsoft/vscode-azurearmtools/issues/255

**Comment by ifeoluwaokunoren** [comment]
Issue resolved: Schemas added in this PR: https://github.com/Azure/azure-resource-manager-schemas/pull/628

**Comment by StephenWeatherford** [comment]
Thanks!  When do we expect the changes to be visible publicly?

**Comment by ifeoluwaokunoren** [comment]
It is publicly visible now. Note, you might need to clear the schema cache for your editor if you're still getting an error.

**Comment by StephenWeatherford** [comment]
working great, thanks!
