### ISSUE TITLE
Missing auto-completion for Microsoft.Network/networkInterfaces "privateIPAllocationMethod"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#63]
I'm using Visual Studio Code 0.10.2 on Mac OS X 10.11.1 El Captian. I noticed that the `privateIPAllocationMethod` is not auto-completing for the `Microsoft.Network/networkInterfaces` Resource Type.

<img width="597" alt="screen shot 2015-11-25 at 5 04 37 pm" src="https://cloud.githubusercontent.com/assets/466713/11412200/e1efa798-9396-11e5-8ddb-36680caa4587.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by FrankSiegemund** [comment]
Thank you for reporting this issue. This has been addressed by this PR: https://github.com/Azure/azure-resource-manager-schemas/issues/63

Once the schema is refreshed and it is not reflected in VS for you, here are more instructions of how to refresh schema caches: http://blogs.msdn.com/b/webdev/archive/2014/04/11/intellisense-for-json-schema-in-the-json-editor.aspx

**Comment by FrankSiegemund** [comment]
The correct link to the PR is here: https://github.com/Azure/azure-resource-manager-schemas/pull/72

**Comment by wenwu449** [comment]
Trevor, we have fixed the issue. Please refresh your schema and check if everything is fine at your side.
Thanks again for your feedback.

**Comment by pcgeek86** [comment]
@wenwu449 Thanks, can you help me understand what you mean by "refresh your schema?"

Cheers,
Trevor Sullivan

**Comment by wenwu449** [comment]
@pcgeek86, Please check "Reload a schema" section in the link shared by Frank, (http://blogs.msdn.com/b/webdev/archive/2014/04/11/intellisense-for-json-schema-in-the-json-editor.aspx)

**Comment by pcgeek86** [comment]
@wenwu449 The link you posted only talks about Visual Studio. As mentioned in the ticket, I'm using Visual Studio Code. What are the directions to reload the schema for Visual Studio Code?

Cheers,
Trevor Sulivan

**Comment by philon-msft** [comment]
In VSCode, use Ctrl+Shift+P to view the list of commands and run the "Reload Window" command

**Comment by pcgeek86** [comment]
@philon-msft Thanks, it is `COMMAND + SHIFT + P`, but I already knew that. :) That's helpful.

**Comment by pcgeek86** [comment]
I have validated that it is working correctly. Thanks @wenwu449 

<img width="422" alt="screen shot 2015-12-03 at 3 22 11 pm" src="https://cloud.githubusercontent.com/assets/466713/11577292/ae61ecce-99d1-11e5-9d05-bf0b553cd247.png">
