### ISSUE TITLE
Missing auto-completion for Windows VM WinRM Listeners

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#64]
The ARM JSON schemas are missing auto-completion for `http` and `https` values for the `protocols` property on a Windows Remote Management (WinRM) listener.

<img width="649" alt="screen shot 2015-11-25 at 7 30 56 pm" src="https://cloud.githubusercontent.com/assets/466713/11413840/36456968-93ab-11e5-9b96-0b81f08af068.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by wenwu449** [comment]
Thanks Trevor, we will work on some improvement on this to give better

**Comment by wenwu449** [comment]
Trevor, we have fixed the issue. Please refresh your schema and check if everything is fine at your side.
Thanks again for your feedback.

**Comment by pcgeek86** [comment]
@wenwu449 Thanks, can you help me understand what you mean by "refresh your schema?"

Cheers,
Trevor Sullivan
