### ISSUE TITLE
"Bad Request" deploying NotificationHubs ARM template

### ISSUE THREAD

**Issue by joeysmeets** [Azure/azure-resource-manager-schemas#646]
There are 2 issues that inflicted us when transitioning to using ARM templates.

## Main problem -> Bad Request
When we deploy the ARM template when there is no Notification Hub (Namespace) yet on Azure, it gives us the **"Bad Request"** error.
When we deploy the same template when there is already a Notification Hub running, there is no issue.

My assumption is that there are additional properties being set when setting up the Notification Hub using the Azure Portal instead of the ARM template.

## Invalid and/or old GCM/FCM/APNS endpoints
When searching we found different endpoints to use here. Some of them are unused because of deprecation. To avoid this situation I would suggest to remove this entry in the schema and replace it for just a string based toggle of the environment the user wants to use.
This gives no opportunity to make mistakes on all the different URL's you find on the internet.

An example (look for *REMOVE* or *ADD* below):
``` json
"apnsCredential":{
   "oneOf":[
      {
         "type":"object",
         "properties":{
            "apnsCertificate":{
               "type":"string",
               "minLength":1,
               "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: A certificate (in base 64 format) provided by Apple on the iOS Provisioning Portal"
            },
            "certificateKey":{
               "type":"string",
               "minLength":1,
               "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: The Certificate Key provided by the iOS Provisioning Portal when registering the application"
            },
            "REMOVE - endpoint - REMOVE":{
               "type":"string",
               "minLength":1,
               "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: The APNS endpoint to which our service connects. This is one of two values: gateway.sandbox.push.apple.com for the sandbox endpoint or gateway.push.apple.com, for the production endpoint. Any other value is invalid."
            },
            "ADD - applicationMode - ADD": {
                "type":"string",
                "minLength":1,
                "description": "Microsoft.NotificationHubs/namespaces/notificationHubs: The environment to be connecting too. This is one of the two values: production or sandbox. Any other value is invalid"
            }
         }
      },
      {
         "$ref":"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#/definitions/expression"
      }
   ],
   "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: APNS credentials for a Notification Hub."
},
"gcmCredential":{
   "oneOf":[
      {
         "type":"object",
         "properties":{
            "googleApiKey":{
               "type":"string",
               "minLength":1,
               "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: Google API key for authenticating with GCM"
            },
            "REMOVE - gcmEndpoint - REMOVE":{
               "type":"string",
               "minLength":1,
               "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: The GCM endpoint to which our connects. Valid endpoint: https://android.googleapis.com/gcm/send . Other values are invalid."
            }
         }
      },
      {
         "$ref":"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#/definitions/expression"
      }
   ],
   "description":"Microsoft.NotificationHubs/namespaces/notificationHubs: GCM credentials for a Notification Hub."
}
```
This would solve the problem we experienced. When setting this up we found out that there are 3-4 different endpoints for APNS. To make matters worse, depending on if you use token based authentication of certificate: you need to use a different URL as endpoint. 
Same goes for Google (GCM, FCM): I found 2-3 different endpoints to use.

**Comment by jwargo** [comment]
@joeysmeets this is a good idea and probably something we could document better to help avoid issues. We can’t implement something like this right now, but I’ll add this to the feature list for some work we’re doing later this year.

**Comment by joeysmeets** [comment]
Thanks for the feedback.

Any info on the "main problem" issue?

**Comment by santo2** [comment]
any feedback on this already? same issue

**Comment by jwargo** [comment]
@joeysmeets @santo2 I don’t know, I’ve asked Engineering to take a look.

**Comment by jwargo** [comment]
Remember: The comments feature of our documentation is intended to enable customers to suggest changes to the docs or ask clarifying questions about the docs. 

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).

**Comment by jwargo** [comment]
@joeysmeets @santo2 I got some feedback from Engineering, this does sound like something we need to look into, but this isn’t something we can address through GitHub issues. Please create a support request through Azure, and that will create a path for digging into this and finding a resolution or creating a fix.

**Comment by santo2** [comment]
Thank you, I've created a ticket through Azure Portal, and linked to this page as well

**Comment by jwargo** [comment]
@santo2 thank you so much. We’ll look into this.

**Comment by ifeoluwaokunoren** [comment]
Closing issue since a support request through Azure has been created for tracking.

**Comment by varvusc** [comment]
Hello @joeysmeets  
Regarding `Main problem -> Bad Request`
Could you please give us more detail about what you exactly deployed, what you used for it: Azure portal or Azure CLI.
It will be wonderful if you can give us some samples of arm template you deployed or some related things which you remember.
