### ISSUE TITLE
Missing auto-completion for parameter metadata

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#65]
<img width="385" alt="screen shot 2015-11-25 at 7 42 46 pm" src="https://cloud.githubusercontent.com/assets/466713/11413965/c3c5d3da-93ac-11e5-95f6-f2c6dfc648c4.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by wenwu449** [comment]
Hi Trever,

Thank you for the feedback.
"metadata" can be any JSON object used as metadata for the parameter, so VS cannot give any suggestion on it.

Thanks
Wenjun

**Comment by pcgeek86** [comment]
Wenjun,

Thanks for the explanation. Is there some way to show this in Intellisense? The UI feedback doesn't really indicate what you relayed to me.

Cheers,
Trevor Sullivan

**Comment by wenwu449** [comment]
Trevor, "metadata" can be any valid JSON object, we can make some improvement on the "description" of the property to help user to understand what can be added as metadata.

**Comment by pcgeek86** [comment]
Perfect, thanks!

Cheers,
Trevor Sullivan
