### ISSUE TITLE
ACI ApiVersion 2018-10-01 Missing

### ISSUE THREAD

**Issue by stefangordon** [Azure/azure-resource-manager-schemas#657]
According to docs we should be using 2018-10-01 (in fact you must use this in many cases)
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/2018-10-01/containergroups

But it is not in the schema.

```
"type": "Microsoft.ContainerInstance/containerGroups",
"apiVersion": "2018-10-01",
```

**Comment by marckassay** [comment]
I believe the following screenshot of mine illustrates this issue:
![image](https://user-images.githubusercontent.com/459665/62553752-e9690300-b83d-11e9-850a-81daede286a5.png)

**Comment by anthony-c-martin** [comment]
Resolved with https://github.com/Azure/azure-resource-manager-schemas/pull/720
