### ISSUE TITLE
Resource Type auto-completion for child resources not showing up correctly

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#66]
When I define a child resource in Visual Studio Code, the `type` JSON property is not showing a comprehensive list of ARM Resource Providers + Types.

<img width="514" alt="screen shot 2015-11-26 at 8 51 04 am" src="https://cloud.githubusercontent.com/assets/466713/11426701/1d389844-941b-11e5-8126-860d2672722c.png">

Could this be related to my environment, or is this an issue with the ARM JSON Schema?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by wenwu449** [comment]
Hi Trever,

For a "Microsoft.Web/sites" resource, "config" and "extensions" are the two child resource types supported, We defined that in our schema and then VS only show these two resource types here.

Thanks
-Wenjun

**Comment by pcgeek86** [comment]
Wenjun,

Thanks, I didn't realize that I accidentally put it as a child of the parent resource. I thought I had put it as a top-level resource. My bad.

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
@wenwu449 I'm reopening this issue, because I actually had the right idea in the first place. What I was trying to do was define a parent-child dependency, according to this document on azure.microsoft.com:

https://azure.microsoft.com/en-us/documentation/articles/resource-group-define-dependencies/

The document states the following:

> The **resources** property allows you to *specify child resources that are related to the resource being defined*. Child resources can only be defined 5 levels deep. It is important to note that an implicit dependency is not created between a child resource and the parent resource. If you need the child resource to be deployed after the parent resource, you must explicitly state that dependency with the dependsOn property.

Cheers,
Trevor Sullivan

**Comment by wenwu449** [comment]
We need some improvement on the document to be more explicit. Can you leave a comment on that page? 

Thanks
Wenjun Wu

**Comment by pcgeek86** [comment]
@wenwu449 I added a comment to the documentation page. Thanks for clarifying, along with Philo.

Cheers,
Trevor Sullivan
