### ISSUE TITLE
TypeScript Types

### ISSUE THREAD

**Issue by alexbechmann** [Azure/azure-resource-manager-schemas#662]
It would be so handy if it was possible to get typescript types for these schemas. 

I am looking for a way to compile ARM templates using typescript so that we can write npm modules/functions to build large complex templates.

**Comment by anthony-c-martin** [comment]
Great suggestion - we'll have a think about this. I started prototyping something along these lines (https://github.com/anthony-c-martin/armtemplate-generator) recently as I was curious about what sort of autocompletion options we'd have with Typescript.

Most of these schema files are being generated by https://github.com/Azure/autorest.azureresourceschema/blob/master/src/ResourceSchemaWriter.cs, so it may be fairly trivial to output Typescript classes using something similar.

**Comment by ifeoluwaokunoren** [comment]
Hi @alexbechmann,

Thanks for this suggestion - can you kindly submit this feature request via User-Voice: https://feedback.azure.com/forums/281804-azure-resource-manager

Thanks

**Comment by bradoyler** [comment]
was anything created for this?

**Comment by anthony-c-martin** [comment]
> was anything created for this?

Nothing I'm aware of. I created https://github.com/anthony-c-martin/arm-templator-types for a prototype project which could possibly be made more robust.

**Comment by bradoyler** [comment]
@anthony-c-martin yes, saw those 👍 . Are you just converting the json schemas to ts Types?
