### ISSUE TITLE
Azure Traffic Manager Profile isn't appearing in Resource "Type"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#67]
The Azure Traffic Manager Profiles (`Microsoft.Network/trafficManagerProfiles`) are not showing up in the Intellisense for the Resource `type` property. I'm using Visual Studio Code 0.10.2 on Mac OS X El Capitan 10.11.1.

![screen shot 2015-11-26 at 8 28 12 pm](https://cloud.githubusercontent.com/assets/466713/11433595/5aa4a572-947c-11e5-890e-01aa84c55f34.png)

There are several Azure "Quick Start" samples that demonstrate the use of this Resource Type.

https://github.com/Azure/azure-quickstart-templates/search?utf8=%E2%9C%93&q=traffic

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by wenwu449** [comment]
Hi Trevor,
Thanks for your feedback.
Meanwhile Azure Traffic Manager team is working on the schema and will publish it soon.

Best Regards
Wenjun

**Comment by jtuliani** [comment]
We should be able to publish the schema next week.

**Comment by wenwu449** [comment]
We have published schema for "TrafficManagerProfile", you can use it to create template now.

**Comment by pcgeek86** [comment]
@wenwu449 Thanks!! I'll take a look next time I author an ARM JSON Template with Traffic Manager resources.

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
@jtuliani Thank you also, for your work on this!
