### ISSUE TITLE
Top-level resource's Resource Type is showing as invalid 

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-resource-manager-schemas#68]
# Problem 

While authoring a very simple ARM JSON Template in Visual Studio Code 0.10.2 on Mac OS X El Capitan 10.11.1, I came across a bug in the ARM JSON Template validation, where I'm being told that `Microsoft.Storage/storageAccounts` isn't a valid top-level ARM Resource Type, and instead, am being told that it *must* be set to `Microsoft.Network/publicIPAddresses`.

<img width="592" alt="screen shot 2015-12-01 at 2 18 10 pm" src="https://cloud.githubusercontent.com/assets/466713/11516199/c1b41f00-9836-11e5-946e-303f1b48a505.png">

# Expected Result

I would expect that this ARM JSON Template would validate, in its current form, with the exception that I may need to specify additional `properties` on the Storage Account resource itself. This template, in its current form, has nothing to do with the `Microsoft.Network` ARM Resource Provider, and really should have no reason to reference the `publicIPAddresses` Resource Type.

Should I also report this on the VSCode GitHub repository?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by philon-msft** [comment]
Yes, please report an issue on the VSCode project or add a comment to the issue they already have tracking the general problem: https://github.com/Microsoft/vscode/issues/881
