### ISSUE TITLE
2018-02-01 - Missing definition - Microsoft.Web/serverfarms

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-resource-manager-schemas#690]
The ARM schema https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json# incorrectly states that the resource type Microsoft.Web/serverfarms does not exist for API version 2018-02-01

See screenshot
![ARM_ServerFarm](https://user-images.githubusercontent.com/28310425/63139953-2c4d7800-bfae-11e9-855c-1251040a4e50.PNG)

**Comment by ifeoluwaokunoren** [comment]
Fix here: 
https://github.com/Azure/azure-resource-manager-schemas/pull/761
