### ISSUE TITLE
2018-11-01 - Missing definition for resource type Microsoft.Web/Sites

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-resource-manager-schemas#691]
Using deployment schema - https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json - An API erorr as shown in screenshot is produced for Microsoft.Web/Sites '2018-11-01' whereby it doesn't recognize the API as being valid when it should be
![ARM_Sites](https://user-images.githubusercontent.com/28310425/63140263-5bb0b480-bfaf-11e9-8929-bbfc40c4df55.PNG)

**Comment by ifeoluwaokunoren** [comment]
Fix here: 
https://github.com/Azure/azure-resource-manager-schemas/pull/761
