### ISSUE TITLE
 apiProfile does not support latest values 

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-resource-manager-schemas#702]
Reported by customer here: https://github.com/microsoft/vscode-azurearmtools/issues/279
> ### Problem
> The linter does not support the latest allowed values for the **apiProfiles** property.
> 
> ![image](https://user-images.githubusercontent.com/7881529/63770082-a5b16880-c8d4-11e9-80f7-aadba96a88cf.png)
> 
> ### Expected Behavior
> The linter should allow all possible values that are available in the Git repository for the Azure REST API (https://github.com/Azure/azure-rest-api-specs/tree/master/profile).

**Comment by jcoeltjen** [comment]
> > This profile 2019-07-01-profile is not supported from ARM's perspective. It will be used for SDKs/PowerShell.
> > @StephenWeatherford, please close this issue.
> 
> This should be documented. What is the latest version allowed in an ARM template?

You can usually find the available template versions in the ARM template reference: https://docs.microsoft.com/en-us/azure/templates/

**Comment by jihu** [comment]
> You can usually find the available template versions in the ARM template reference: 
> https://docs.microsoft.com/en-us/azure/templates/

Well, I can't really find any information about apiProfile versions there. Or am I missing something? If you can find it, maybe you can help me out with a direct link to that page?

**Comment by jcoeltjen** [comment]
> > You can usually find the available template versions in the ARM template reference:
> > https://docs.microsoft.com/en-us/azure/templates/
> 
> Well, I can't really find any information about apiProfile versions there. Or am I missing something? If you can find it, maybe you can help me out with a direct link to that page?

Of course you are correct. I confused apiProfile and apiVersions.
The ARM documentation also only points to this git repository (see link in first post).
In this case I follow your idea: It should be documented which each api profile is intended for.
