### ISSUE TITLE
square brackets in section names => become invalid URI references

### ISSUE THREAD

**Issue by zb-z** [Azure/azure-resource-manager-schemas#704]
The two I know about:

https://schema.management.azure.com/schemas/2017-11-15/Microsoft.Devices.json
https://schema.management.azure.com/schemas/2017-08-21-preview/Microsoft.Devices.json

Section name: "SharedAccessSignatureAuthorizationRule[asdAccessRightsDescription]"

Why it matters? It makes validators which are less permissive trip and for no rational reason at all. In particular it makes XmlSpy 2018 trip and it is the only tool that can actually load, use and survive ~1300 schemas referenced in deploymentTemplate.json which in turn gets referenced just about everywhere else (also for no rational reason - see bellow).

Square brackets are reserved chars in RFC3986 (https://tools.ietf.org/html/rfc3986#page-12) and one can argue to heaven and back that RFC3986 is too restrictive (since [,] are used only for the host part which is trivially separable - https://tools.ietf.org/html/rfc3986#section-3.2.2) but it explicitly forbids their use anywhere else, so unless you have the power to change RFC3986 for yesterday ... 

Also, it would be very good to separate that monster include section (deploymentTemplate.json#/properties/resources) into it's own .json and the also extract that little part that's referenced everywhere (deploymentTemplate.json#/definitions/expression) into it's own .json (maybe place it in common/...) and rewrite deploymentTemplate.json to include both and not be referenced by any other file. 

That would remove the nasty circular dependence which is always just asking for trouble per se and in this particular case explodes memory footprint for validating just about every other schema, again for no rational reason at all.

**Comment by anthony-c-martin** [comment]
As far as I can tell this has been fixed by the work to automatically generate Microsoft.Devices schemas from https://github.com/Azure/azure-rest-api-specs. Please feel free to re-open this if you still see the problem.
