### ISSUE TITLE
Documentation does not list recent Microsoft.DocumentDB schemas

### ISSUE THREAD

**Issue by AlexPiksel** [Azure/azure-resource-manager-schemas#722]
The documentation pages for the `Microsoft.DocumentDB` schema only shows the `2015-04-08` version. Looking I can see the latest is `2019-08-01`, and I know `2016-03-31` is also valid, but these are not documented.

https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/allversions

Unclear if this is the right place to report this, but the documentation page has no information about where to file bugs, and no issue tracker in the footer.

**Comment by AlexPiksel** [comment]
That makes sense mechanically, but I'm not sure it's the best approach. When we export ARM templates from the Azure Portal they include schema versions which, according to the documentation, don't exist.

This creates uncertainty about the validity of the templates, and raises questions about what has changed.

**Comment by ifeoluwaokunoren** [comment]
Hi Alex,

The documentation/schemas are generated from the [swagger specifications](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB)

I followed up with the doc teams - and they made an update to the [doc](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/allversions)

Template Exports uses the latest version number available from the resource provider's published schemas which in this case would be 2019-08-01-preview
