### ISSUE TITLE
2018-02-14 - Missing definition - Microsoft.KeyVault/vaults

### ISSUE THREAD

**Issue by mmcfadyen** [Azure/azure-resource-manager-schemas#759]
It appears the Schema for Microsoft.KeyVault/vaults version 2018-02-14 is missing from https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-01-01/deploymentTemplate.json.

According to documentation, it should exist: https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2018-02-14/vaults

**Comment by ifeoluwaokunoren** [comment]
Fix for this issue: https://github.com/Azure/azure-resource-manager-schemas/pull/762

**Comment by anthony-c-martin** [comment]
FWIW we could probably onboard KeyVault for [automatic schema generation](https://github.com/Azure/azure-resource-manager-schemas/tree/master/generator#onboarding-teams-to-autogeneration-pipeline) once https://github.com/Azure/azure-rest-api-specs/pull/11964 has been merged.

**Comment by anthony-c-martin** [comment]
Fixed by #1525
