### ISSUE TITLE
Getting Errors while generating data factory ARM template using AZ power shell 

### ISSUE THREAD

**Issue by raojk** [Azure/azure-resource-manager-schemas#773]
Hi could please let me know is it possible to generate data factory ARM template using Azure power shell . When i was tried with Az power shell to generate ARM template for required data factory I am getting below eerors.

WARNING: ExportTemplateCompletedWithErrors : Export template operation completed with errors. Some resources were not exported. Please see details for more information.
WARNING: ResourceTypeSchemaNotFound : The schema of resource type 'Microsoft.Databricks/workspaces' is not available. Resources of this type will not be exported to the template.
WARNING: ResourceTypeSchemaNotFound : The schema of resource type 'Microsoft.DataFactory/factories' is not available. Resources of this type will not be exported to the template.
WARNING: ResourceTypeSchemaNotFound : The schema of resource type 'Microsoft.Portal/dashboards' is not available. Resources of this type will not be exported to the template.

**Comment by ifeoluwaokunoren** [comment]
Hi @raojk,

What cloud environment did you try exporting from ? i.e: Public or National Clouds

ARM currently doesn't support Template Exports for Data-Factory resources - please go to https://adf.azure.com/ to export microsoft.datafactory resources

The other 2 resources (below) have schemas published for them, so you should be able to export them.
Microsoft.Databricks/workspaces
Microsoft.Portal/dashboards

Thanks.
