### ISSUE TITLE
Microsoft.Consumption/budgets properties.filters.resources can be an expression

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-resource-manager-schemas#789]
Currently, schema throws an issue if properties.filters.resources is an expression

This throws an error:
![image](https://user-images.githubusercontent.com/11078275/67607180-6f5b6280-f738-11e9-8cfe-567f6f21805b.png)

This does not:
![image](https://user-images.githubusercontent.com/11078275/67607164-65d1fa80-f738-11e9-9d7b-fd584ed1fda7.png)

**Comment by anthony-c-martin** [comment]
Should be addressed by https://github.com/Azure/azure-resource-manager-schemas/pull/795 (note, currently blocked)

**Comment by alex-frankel** [comment]
fixed
