### ISSUE TITLE
Microsoft.Network/networkSecurityGroups false positive on properties.securityRules.properties.priority

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-resource-manager-schemas#791]
This deploys successfully:
![image](https://user-images.githubusercontent.com/11078275/67607975-32449f80-f73b-11e9-8674-e1e0c1a4c5ec.png)

**Comment by number213** [comment]
@alex-frankel could you please tell which `schema` you're using and what's the error with `priority`? I can't replicate it

**Comment by alex-frankel** [comment]
I can't seem to replicate it either - will close this for now until I can repro
