### ISSUE TITLE
Microsoft.storage/storageAccounts/fileServices schema missing

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-resource-manager-schemas#793]
Originally reported here: https://github.com/microsoft/vscode-azurearmtools/issues/333

**Comment by neilpeterson** [comment]
One additional note on this. It does look like the proper schema exists for the storage account, however not the child resource `fileServices`.

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-04-01/Microsoft.Storage.json

Thanks

**Comment by anthony-c-martin** [comment]
Fixed by #1130
