### ISSUE TITLE
Microsoft.Insights/scheduledQueryRules Alert creating through ARM template but not triggering.

### ISSUE THREAD

**Issue by VikramAIS** [Azure/azure-resource-manager-schemas#804]
Hi Team, I have created an ARM template to create OMS alerts through the ARM templates using Microsoft.Insights/scheduledQueryRules. Template deployed successfully and alert created(verified from the portal). Alerts not triggering.  

If I do any modification like result count from portal and saved, then alerts started triggering. Compared both before and after modification from portal results through the REST API I don't see any difference in REST API response.

Please help me on this.

**Comment by anthony-c-martin** [comment]
Please open a ticket through https://azure.microsoft.com/en-us/support/options/ with the details and our support team can assist.
