### ISSUE TITLE
Missing definition: many versions of Microsoft.Resources schema are missing

### ISSUE THREAD

**Issue by t03apt** [Azure/azure-resource-manager-schemas#814]
### Missing definition: many versions of Microsoft.Resources schema are missing
For example:
[Microsoft.Resources deployments template@2019-08-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/2019-08-01/deployments) exists in the documentation, but its schema is missing:
https://schema.management.azure.com/schemas/2019-08-01/Microsoft.Resources.json#/resourceDefinitions/deployments

```[xml]
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:ba6b0030-401e-005a-4b4c-ab0971000000 Time:2019-12-05T09:16:28.2185121Z
</Message>
</Error>
```

**Comment by anthony-c-martin** [comment]
Addressed by https://github.com/Azure/azure-resource-manager-schemas/pull/822. Please note it will take some time for this change to be made live at schema.management.azure.com
