### ISSUE TITLE
Missing schemas Microsoft.StorageSync/*

### ISSUE THREAD

**Issue by sean-nixon** [Azure/azure-resource-manager-schemas#816]
All resource schemas for the Microsoft.StorageSync provider seem to be missing including:
- Microsoft.StorageSync/storageSyncServices
- Microsoft.StorageSync/storageSyncServices/registeredServers
- Microsoft.StorageSync/storageSyncServices/syncGroups
- Microsoft.StorageSync/storageSyncServices/syncGroups/cloudEndpoints
- Microsoft.StorageSync/storageSyncServices/syncGroups/serverEndpoints

**Comment by ifeoluwaokunoren** [comment]
Hi @sean-nixon,
The resource schemas are actually part of the auto-generated schemas that are available only in the latest root-schema, `https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"`
[Link to autogenerated resource references](https://github.com/Azure/azure-resource-manager-schemas/blob/b68a14957118807bdf3e57235dab4e40ae6018fb/schemas/common/autogeneratedResources.json#L1892)
If you are using VSCode for example, it would suggest that you should use the latest root-schema. Please note, you'd have to use the latest VS Code "Azure Resource Manager (ARM) Tools" extension

![image](https://user-images.githubusercontent.com/24998283/70574194-67287c80-1b58-11ea-8cc1-48cadfd729c0.png)
