### ISSUE TITLE
Is Azure Cloud Services dead?

### ISSUE THREAD

**Issue by 649** [Azure/azure-resource-manager-schemas#82]
Since there is no schema to create a Cloud Service with the Azure RM, one start to wonder if Azure Cloud Services are dead, and you just moved on without telling anyone about it like you did with SilverLight?

**Comment by aarsan** [comment]
Azure RM only supports V2 resources. Cloud Services are V1 (so yes, dead).

**Comment by rjmax** [comment]
This isn't the right place for such a question - we only aggregate and publish the ARM schemas.  

These are not the "you"s you're looking for :)
