### ISSUE TITLE
Azure Blueprints returns schema fetching error

### ISSUE THREAD

**Issue by SimonTheLeg** [Azure/azure-resource-manager-schemas#834]
When trying to use an ARM template in Azure blueprints, I get a strange error during template schema validation: 

<img width="554" alt="Screenshot 2020-01-03 at 17 09 49" src="https://user-images.githubusercontent.com/20774623/71734283-dd648a00-2e4b-11ea-81e4-35f462225e8d.png">

Full error message is:

```
Unable to load schema from 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json'. No schema request service available(768)
```

I've tried both changing `$schema` to another version and tried using a different ARM template all together, but no success. Any ideas? Judging from the error message it does not seem like a problem with the template itself

**Comment by AlexOQ** [comment]
Same here. Templates deploy successfully, though.
Annoying bug.

**Comment by anthony-c-martin** [comment]
Thank you for reporting this! We are tracking this work item internally, as it is technically an issue with the Azure Portal UX, and not the schemas or the schema hosting service.

As such I'm going to close this issue, but will come back with an update once the Portal work item has been completed.

**Comment by fiftin** [comment]
@anthony-c-martin You closed issue but problem still actual.

![image](https://user-images.githubusercontent.com/914224/88788007-2f854800-d1ae-11ea-84d3-37be067e9bc2.png)

Where correct place for this issue?

**Comment by smartin85** [comment]
Isn´t this just a problem with the monaco-editor on the UI?
See https://github.com/microsoft/monaco-editor/issues/1331 

I would also like to use JSON Schema in the web editor.
