### ISSUE TITLE
ARM JSON validation error

### ISSUE THREAD

**Issue by zenmah** [Azure/azure-resource-manager-schemas#840]
When defining a ARM template for the data factory v2 im coming across the JSON validation error:
resource.properties **Expression should be of type string**

According to the documentation provided [here](https://docs.microsoft.com/nl-nl/azure/templates/microsoft.datafactory/2018-06-01/factories#FactoryProperties) this JSON should be valid.

```json
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    
  },
  "resources": [
    {
      "apiVersion": "2018-06-01",
      "location": "region",
      "name": "factory",
      "type": "Microsoft.DataFactory/factories",
      "properties": {}
    }
  ]
}
```

 I would expect the JSON should be validated correctly if i'm following the documentation. 
Excluding the properties or changing it to contain a string instead of an empty object does not resolve the issue.

Many Thanks
Jeroen van Lier.

**Comment by shawnxzq** [comment]
@LijuanZ Could you please look at this issue? Thanks!

**Comment by LijuanZ** [comment]
@zenmah An empty object as properties should be valid for data factory payload. Does the issue still happen? If so, can you try again and share factory name and region so we can check what happened?  Thanks!

**Comment by shawnxzq** [comment]
@zenmah Could you please confirm whether you still have the issue? Thanks!

**Comment by shawnxzq** [comment]
@anthony-c-martin We believe this issue should be resolved and no customer response on this, could you please help close the issue? Thanks!

**Comment by anthony-c-martin** [comment]
@shawnxzq I've just tested this locally with the original repro, and it does appear to be fixed. Thanks for taking a look!
