### ISSUE TITLE
Microsoft.Insights/autoscalesettings missing from 2015-04-01

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#843]
For example, autoscale settings is shows here with a version of 2015-04-01, however is only found in 2014-04-01

https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-04-01/autoscalesettings

This is causing validation issues with the VS Code tools for ARM Templates.

![image](https://user-images.githubusercontent.com/7844635/72848653-e92cba80-3c59-11ea-8a66-fc02ab02be9c.png)

**Comment by StephenWeatherford** [comment]
@anthony-c-martin Any ETA?  It's been there a long time.  Thx.

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin Any ETA? It's been there a long time. Thx.

I've submitted https://github.com/Azure/azure-resource-manager-schemas/pull/1466 for this.

**Comment by StephenWeatherford** [comment]
Cool, thanks!  Do I need to submit a separate issue for the "statics" portion of microsoft/vscode-azurearmtools#1141?

**Comment by anthony-c-martin** [comment]
> Cool, thanks! Do I need to submit a separate issue for the "statistics" portion of [microsoft/vscode-azurearmtools#1141](https://github.com/microsoft/vscode-azurearmtools/issues/1141)?

I already fixed this with https://github.com/Azure/azure-resource-manager-schemas/pull/1463 but don't have permissions to close the vscode ARM tools issue.

**Comment by StephenWeatherford** [comment]
Thanks.  I have to actually pick up the new schemas in the extension so I'll close it after I do that.
