### ISSUE TITLE
Microsoft.Resources/deployments missing many versions and from root schema

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#844]
I am seeing two issues with the `Microsoft.Resources/deployments` resource schema.

- Many versions have not been generated.
- In some cases, a resource schema has been generated but not added to the root schema.

I understand that issue 1 is an ongoing project, but am curious if there is a way to resolve issue 2.

For context, we use these schemas for ARM template validation in ARM tools for VS Code and are trying to improve validation.

**Issue 1 - schema not generated**

I see generated schemas for `Microsoft.Resources/deployments` for the following versions.

```
2015-01-01
2016-02-01
2016-09-01
2017-05-10
2018-05-01
2019-05-01
```

The Microsoft.Resources provider reports these as valid versions.

```
az provider show --namespace Microsoft.Resources --query "resourceTypes[?resourceType=='deployments'].apiVersions | [0]" --out table
Result
------------------
2019-09-01
2019-05-01
2019-04-01
2019-03-01
2018-11-01
2018-09-01
2018-08-01
2018-07-01
2018-05-01
2018-02-01
2018-01-01
2017-08-01
2017-06-01
2017-05-10
2017-05-01
2017-03-01
2016-09-01
2016-07-01
2016-06-01
2016-02-01
2015-11-01
2015-01-01
2014-04-01-preview
```

**Issue 2 - schema is generated but not in root schema**

I've found that the following versions do have schema definitions however have not been added to the `2019-04-01` root schema.

```
2019-05-01
2018-05-01
```

Thanks a bunch.

**Comment by edburns** [comment]
I should hope that the long term vision includes auto-generating the schemas with a CI/CD pipeline that does a bunch of things like

```
az provider show --namespace Microsoft.Resources --query "resourceTypes[?resourceType=='deployments'].apiVersions | [0]" --out table
Result
------------------
2019-09-01
2019-05-01
2019-04-01
2019-03-01
2018-11-01
2018-09-01
2018-08-01
2018-07-01
2018-05-01
2018-02-01
2018-01-01
2017-08-01
2017-06-01
2017-05-10
2017-05-01
2017-03-01
2016-09-01
2016-07-01
2016-06-01
2016-02-01
2015-11-01
2015-01-01
2014-04-01-preview
```

Of course replacing `Microsoft.Resources` and `deployments` with all the many things of which the schema is composed.

**Comment by anthony-c-martin** [comment]
Addressed by https://github.com/Azure/azure-resource-manager-schemas/pull/822. Please note it will take some time for this change to be made live at schema.management.azure.com
