### ISSUE TITLE
Default custom template unable to load schema

### ISSUE THREAD

**Issue by Sindhiya24** [Azure/azure-resource-manager-schemas#848]
On creating new custom template, template auto creates with schema error:

"Unable to load schema from 'https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json'. No schema request service available
![image](https://user-images.githubusercontent.com/54301897/73237690-6c02c780-41bc-11ea-8100-e9750ba0b5ce.png)

The URL is fine as mentioned, template is default.

**Comment by anthony-c-martin** [comment]
Thank you for reporting this! We are tracking this work item internally, as it is technically an issue with the Azure Portal UX, and not the schemas or the schema hosting service.

As such I'm going to close this issue, but will come back with an update once the Portal work item has been completed.

**Comment by anthony-c-martin** [comment]
Also note, this is the same issue as https://github.com/Azure/azure-resource-manager-schemas/issues/848

**Comment by Raghavendra9289** [comment]
Hi I am getting arm ttemplate deploymnet error, any help to resolve this issue
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidRequestContent\",\r\n \"message\": \"The request content is not valid and could not be deserialized: 'Required property '$schema' not found in JSON. Path 'properties.definition', line 1, position 513.'.\"\r\n }\r\n}"}]}

**Comment by anthony-c-martin** [comment]
@Raghavendra9289 It sounds like your template is missing the `$schema` property - see https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-syntax#template-format for some info on the expected template structure.

If you're still having problems with your deployment, please could you raise a support case through the Azure Portal? We only use this repository to track items related to template authoring, not deployment.
