### ISSUE TITLE
KeyVault schemas - multiple properties don't allow expressions

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-resource-manager-schemas#85]
In the KeyVault/vauls schema here are a few properties that don't allow for expressions:

permissions>keys
permissions>secrets
sku>name
sku>family

**Comment by wenwu449** [comment]
@daschult, can you take a look why our validation tool did not catch this?

**Comment by daschult** [comment]
Sure, I'll take a look.

**Comment by wenwu449** [comment]
Fixed.
