### ISSUE TITLE
Microsoft.KeyVault/vaults missing schema for version 2018-02-14

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-resource-manager-schemas#853]
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2018-02-14

Reported in ARM tools - https://github.com/microsoft/vscode-azurearmtools/issues/461

**Comment by DrBushyTop** [comment]
Not sure if this will get fixed along side the main vaults resource, but "Microsoft.KeyVault/vaults/secrets"  is also missing the same apiVersion 2018-02-14.

**Comment by jkruis** [comment]
Duplicate of #759
