### ISSUE TITLE
Microsoft.Web/serverfarms is missing apiVersion 2019-08-01

### ISSUE THREAD

**Issue by DrBushyTop** [Azure/azure-resource-manager-schemas#861]
Hi,

as mentioned in the subject, Microsoft.Web/serverfarms is missing apiVersion 2019-08-01
See an example below for ARM extension version 0.8.4. 

![Example](https://huuhkadotnet.blob.core.windows.net/prod/images/2020/2/servefarmsschema.jpg)

**Comment by anthony-c-martin** [comment]
Thanks for reporting! We will follow up with the Microsoft.Web team.

**Comment by anthony-c-martin** [comment]
Fixed by #1691
