### ISSUE TITLE
Api app schema

### ISSUE THREAD

**Issue by aplamon** [Azure/azure-resource-manager-schemas#87]
Will there be a schema available with the new release of api app? We're using them but can't find a schema for creating them.

**Comment by wenwu449** [comment]
Is this what you are looking for?
https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-03-01-preview/Microsoft.AppService.json

**Comment by aplamon** [comment]
No, that's the preview. I'm looking for the recent release of app api.

**Comment by christav** [comment]
The new release of apiapp is no longer a separate resource type, it's now just a separate flag on webapps (a.k.a. antares). Use the existing website resource schema instead.

**Comment by aplamon** [comment]
Ok, thanks! Is there an example on how to define this? Articles I can find out there only details how to setup an API App using the old version. I'm not sure what flag and where to set.

**Comment by dermeister0** [comment]
I don't have an example, but **kind** property is the difference between Web App and API App.

> ResourceType: Microsoft.Web/sites
> Kind: api
