### ISSUE TITLE
Microsoft.Storage/storageAccounts template reference missing 2019-06-01

### ISSUE THREAD

**Issue by aholler2** [Azure/azure-resource-manager-schemas#871]
Update Request: https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/allversions

Right now the storage account ARM template reference lays out the ARM template for Microsoft.Storage/storageAccounts API version 2019-04-01, however, I'd like to see it for API version 2019-06-01 as multiple properties have been added such as RoutingPreference and BlobRestore.

**Comment by neilpeterson** [comment]
@tfitzmac where is the best place to log doc requests for updated template reference?

**Comment by tfitzmac** [comment]
azure-docs is the best place to track requests - [https://github.com/MicrosoftDocs/azure-docs/issues](https://github.com/MicrosoftDocs/azure-docs/issues)

**Comment by neilpeterson** [comment]
Thanks Tom.

@aholler2 we do have [a schema for this version](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-06-01/Microsoft.Storage.json), it's the docs reference that needs to be generated.  I will open up the issue and mention you in it for tracking purposes.

**Comment by neilpeterson** [comment]
I'm going to close this issue, we can track docs status at the below issue / repo.

https://github.com/MicrosoftDocs/azure-docs/issues/49579

**Comment by tfitzmac** [comment]
@aholler2 - thanks for this feedback. The template reference for storage was updated to include the latest version.

**Comment by neilpeterson** [comment]
Thanks @tfitzmac
