### ISSUE TITLE
parameter schema does not recognize reference paramters...

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-resource-manager-schemas#88]
e.g.

    "sqlsvrAdminLoginPassword": {
      "reference": {
        "keyVault": {
          "id": "/subscriptions/[id]/resourceGroups/[rg]/providers/Microsoft.KeyVault/vaults/[name]"
        },
        "secretName": "adminPassword"
      }
    },

**Comment by wenwu449** [comment]
Fixed. Thanks for reporting!
