### ISSUE TITLE
Reference template for child resource types should explain naming conventions

### ISSUE THREAD

**Issue by vlkuznet** [Azure/azure-resource-manager-schemas#957]
I've found this to be a pretty common pitfall for users trying to create child resources, such as subnets or configuration items. 

We already have this documentation:  https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/child-resource-name-type 

The pages of reference templates for child resource types would greatly benefit from a "note" section linking to this documentation.

**Comment by neilpeterson** [comment]
Thanks for the suggestion @vlkuznet 

In addition to adding a link to the docs, I wonder if there is anything that we can do to ensure that child resource naming is done correctly. We will look into this.

**Comment by anthony-c-martin** [comment]
@vlkuznet Do you have any specific examples of this?

As far as I'm aware, any new schemas generated with the autorest.azureresourceschema tool should be correctly defining the child type in accordance with the docs you linked.

**Comment by vlkuznet** [comment]
Hi @anthony-c-martin ,

Let me know if this is the wrong place for this inquiry - the goal here is an improvement to the documentation section collectively referred to as ARM template reference. 

As an example, this page could contain a note that states "This resource is typically used as a child resource and would be named...."

https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2019-08-01/sites/config-authsettings

**Comment by tfitzmac** [comment]
@vlkuznet - thanks for this feedback. Most of the child resources have a sentence in the property table that links to the article you mentioned. The web config types are missing that sentence because they are not generated through the standard process. I will add it to web config and experiment with how to make it easily visible.

**Comment by apclouds** [comment]
@tfitzmac let me know once the addition to the docs is done so I can close this issue

**Comment by tfitzmac** [comment]
This issue has been fixed. It can be closed now.

**Comment by anthony-c-martin** [comment]
Thanks @tfitzmac!
