### ISSUE TITLE
Microsoft.Web/sites is missing apiVersion 2019-08-01 (and 2019-03-01?)

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-resource-manager-schemas#958]
The latest currently supported in VS Code ARM tools is `2018-11-01`.

That version gives me the following error when deploying my template:

```
Resource Microsoft.Web/sites '<snip>' failed with message '{
  "Code": "BadRequest",
  "Message": "siteConfig.PreWarmedInstanceCount is invalid.  It is only supported for 2019-03-01 api-version or newer.",
```

### The 2019-08-01 version works - but no schema in VS Code

(The error message above talks about a 2019-03-01 version, which is undocumented at docs.microsoft.com, and I get a "NoRegisteredProviderFound" error when I try to use it. So either 2019-03-01 needs docs - Or the error message needs fixing).

**Comment by anthony-c-martin** [comment]
Fixed by #1691
