### ISSUE TITLE
Microsoft.Network: need schema for virtualNetworkGateways, localNetworkGateways and connections

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-resource-manager-schemas#96]
The schema for above resources are missing at this point.

**Comment by jangelfdez** [comment]
When you are typing, Visual Studio shows wrong options and confusing messages that makes difficult to know if the template is ok or not.

**Comment by enelson0179** [comment]
These schemas are missing from export and VS blocking automation , any ETA?

**Comment by animetauren** [comment]
Please an update on these schema would be so helpful, especially with networking being such a critical piece of infrastructure on azure.

**Comment by daschult** [comment]
This pull request has updates for the Microsoft.Network schema: https://github.com/Azure/azure-resource-manager-schemas/pull/161

**Comment by jangelfdez** [comment]
Hi!

anything new on this? Schema information is not available through tools like VSCode in order to help you writing templates. 

Regards

**Comment by jabbera** [comment]
This is making things not pleasant in vscode:-(

**Comment by jabbera** [comment]
Ping!

**Comment by jabbera** [comment]
For the love of all deities if you are a believer. Please update the schemas in the extension!!!!!!!

**Comment by MikhailTryakhov** [comment]
@number213 @EvgenyAgafonchikov  please review

**Comment by number213** [comment]
Fixed by https://github.com/Azure/azure-resource-manager-schemas/pull/653 and https://github.com/Azure/azure-resource-manager-schemas/pull/661
