### ISSUE TITLE
Microsoft.Resources/deployments parameters

### ISSUE THREAD

**Issue by drewkg** [Azure/azure-resource-manager-schemas#994]
When using a nested deployment, sample below, with expressionEvaluationOptions set to inner, the schema warns that the parameter, on the nested deployment, is undefined.  In this case the calue for parameter for the nested deployment is generated in the wider deployment and not a parameter on the main template.     

    {
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-08-01",
      "name": "RoleBasedAccessDeployment",
      "comments": "This adds the UAI to the management recourse group as a storage blob reader.",
      "dependsOn": [
        "uai-DevOps-AgentInstaller"
      ],
      "tags": {
        "displayName": "Role Based Access Control Deployment"
      },
      "resourceGroup": "[parameters('AgentManagementRG')]",
      "properties": {
        "expressionEvaluationOptions": {
          "scope": "inner"
        },
        "mode": "Incremental",
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
            "principalId": {
              "type": "string"
            }
           },
          "variables": { },
          "resources": [
            {
              "name": "[guid(concat(resourceGroup().name, '-uai-DevOps-AgentInstaller'))]",
              "type": "Microsoft.Authorization/roleAssignments",
              "apiVersion": "2018-01-01-preview",
              "properties": {
                "roleDefinitionId": "[concat(subscription().id, '/providers/Microsoft.Authorization/roleDefinitions/', 'b7e6dc6d-f1e8-4753-8033-0f276bb0955b')]",
                "principalId": "[parameters('principalId')]",
                "scope": "[resourceGroup().id]"
              }
            }
          ]
        },
        "parameters": {
          "principalId": {
            "value": "[reference('uai-DevOps-AgentInstaller', '2018-11-30').principalId]"
          }
        }
      }
    },

**Comment by anthony-c-martin** [comment]
@drewkg Would you mind confirming whether this issue is occurring when using the [ARM VSCode extension](http://aka.ms/armtools), or with a different schema validator?

**Comment by drewkg** [comment]
Apologies, thi is coming from the ARM VSCode extension, I only opened here as normally schema validations get passed across, happy to open in the appropriate project.

**Comment by alex-frankel** [comment]
This is a VSCode issue, not a schema issue (it is a bit confusing frankly). Basically, the VS Code ARM Language Server does not understand the new `expressionEvaluationOptions` property. There is an open issue for it here: https://github.com/microsoft/vscode-azurearmtools/issues/554

@anthony-c-martin we can close this one

**Comment by anthony-c-martin** [comment]
Closing this as it's being tracked under https://github.com/microsoft/vscode-azurearmtools/issues/554
