### ISSUE TITLE
customScriptExtension resource: warning for missing commandToExecute property

### ISSUE THREAD

**Issue by drewkg** [Azure/azure-resource-manager-schemas#995]
For a Virtual Machine Scale Set, if you add an extension resource, with the command to execute in the protected settings section, instead of in the settings section you get a missing commandToExecute warning

          "extensionProfile": {
            "extensions": [
              {
                "name": "customScript",
                "type": "extensions",
                "properties": {
                  "publisher": "Microsoft.Compute",
                  "type": "CustomScriptExtension",
                  "typeHandlerVersion": "1.10",
                  "autoUpgradeMinorVersion": true,
                  "settings": { },
                  "protectedSettings": {
                    "fileUris": [
                      "[concat('https://',parameters('CustomScriptStorageAccountName'),'.blob.core.windows.net/',parameters('CustomScriptContainerName'),'/AddAgentToVM.ps1')]"
                    ],
                    "commandToExecute": "[concat('PowerShell -ExecutionPolicy Unrestricted -File \"./AddAgentToVM.ps1\" -DevOpsTenant \"', parameters('AzureDevOpsTenantName'), '\" -windowsLogonAccount \"', parameters('adminUsername'), '\" -windowsLogonPassword \"', parameters('adminPassword'), '\" -VSTSToken \"', parameters('AgentRegistrationPAT'), '\" -poolName \"', parameters('AgentPoolName'), '\"')]",
                    "managedIdentity" : {
                      "objectsid": "[reference('uai-DevOps-AgentInstaller', '2018-11-30').principalId]"
                    }
                  }
                }
              }
            ]
          }

**Comment by StephenWeatherford** [comment]
@viabhav-agar, @avirishuv, @amjads1 Any progress on this?  Thanks.
